### ISSUE TITLE
observation fields should have UI for date/time types

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#10]
Right now they just display as text.

**Comment by alexshepard** [comment]
Is this still the case @kueda? We're using the date picker now. Or am I mis-understanding the issue?

**Comment by kueda** [comment]
Still true. This is referring to observation fields with type "date," e.g. http://www.inaturalist.org/observation_fields/15. They aren't used very much and frankly I'm not sure why I even included them in the first place. I'm pretty sure most of the projects using "original sighting date" are under the mistaken assumption it is meant to contain the date you made *this* observation and not the date you observed the same organism previously.

So yes, still a valid issue, though not a very high priority one.

**Comment by alexshepard** [comment]
@kueda I think this is working now, can you look?

**Comment by kueda** [comment]
Date field does, but I get some weird nesting in the Test Project of Unfathomable Awesomeness:
![img_8044](https://cloud.githubusercontent.com/assets/22691/17565181/2f6792c2-5eeb-11e6-86cb-0032986925d1.PNG)

None of those nested fields are editable.

**Comment by alexshepard** [comment]
done as of build 425
