### ISSUE TITLE
modal loading status while syncing obs still lets you tap on obs

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#104]
IMO, it's weird to have a modal-ish thing blocking the center of the screen when you can still tap things underneath. If we want an unobtrusive indicator that lets you know something's going on in the BG (and actually make that happens), we can can go there, but for now, since the process is essentially blocking, I think we need to go back to a truly modal notification.

**Comment by alexshepard** [comment]
we now block interaction with the tableview while sync is in-progress. @kueda can you verify?

**Comment by kueda** [comment]
Interaction with the tableview is blocked as of build 179, but interaction with the tab bar still works. Doing so doesn't interfere with sync, but it's kind of weird that I can go to different tabs and still have the progress popup over them.

**Comment by alexshepard** [comment]
fair enough, do you think we should disable interaction with the tab bar and the navigation bar (so you can't get out to settings) during sync?

**Comment by alexshepard** [comment]
did that last in 497d717e14d7764b7a9bf7efe1a0eddef578009f, which will be in 2.5.8 build 181
