### ISSUE TITLE
photos disappear after sync

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#105]
This happens intermittently, but I figured I'd start this so we can at least document some symptoms. I just uploaded 10 observations, all of which had photos. I uploaded them over wifi, and initially I had to cancel the sync b/c I tapped an underlying observation (see #104). Then I synced again and got a timeout error. The sync bar said "1 photo to sync" and then I tapped it and the sync was complete. Three of the photos were double-posted to the site, and the photos no longer appear in the app (though they are in the Camera Roll:

http://www.inaturalist.org/observations/1117424
http://www.inaturalist.org/observations/1117427

http://www.inaturalist.org/observations/1117423
http://www.inaturalist.org/observations/1117426

http://www.inaturalist.org/observations/1117425
http://www.inaturalist.org/observations/1117428

I think I saw this happening during the Mimosa Rocks bioblitz too, to someone else. I suspect it has something to do with a bad internet connection and/or timeouts, which I know are hard to replicate.

**Comment by kueda** [comment]
Did you implement the short-term never-pull-if-there-are-things-to-push strategy? B/c I just experienced this myself when my upload failed after the observations were sent but before the photos b/c it failed to submit an observation field that had no observation (a separate issue, I suspect). Later, I navigated back to the observations list and it initiated a pull and removed photos from the observations (as far as I can tell, have not investigated the state of the local db yet).

**Comment by alexshepard** [comment]
I did implement that strategy, but now that I look I think I made a mistake. 

Pull to refresh (the user initiated action) will always push before pull. However, I didn't update the automatic action in `-viewDidAppear:`. Will fix this now.

**Comment by alexshepard** [comment]
This case should be fixed in 90bba1780b5651a708724cae6b7f58c79c1d8c02.
