### ISSUE TITLE
don't show "Agree?" links for identifications that you already agree with

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#108]
We don't really do this on the website either, so we need to fix it it in both places, but at present, identifications on the Observations Activity list show an "Agree?" link next to an identification even if that ID is of the same taxon that you (the observer) have already ID'd this observation as. This confuses a lot of people and they just constantly hit "Agree?" because they agree, which results in tons of identifications, e.g. http://www.inaturalist.org/observations/1125627

**Comment by carrieseltzer** [comment]
This came up again in the google group so good to have this on the priority list somewhere. https://groups.google.com/forum/#!topic/inaturalist/F-UxgtwzvDk

**Comment by alexshepard** [comment]
in the "me" tab, done in 4f2b551488fe925e393a915bd852289e447ed7c2, should be in 2.5.8

this could use some testing, @kueda

**Comment by kueda** [comment]
Works for me in build 180. Thanks.
