### ISSUE TITLE
Build 82 of app trying to sync after each observation 

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/INaturalistIOS#112]
So I have build 82 and it is exhibiting odd behavior. First it was working normally but I then experienced that crash which happens sometimes after zooming in with the camera. I reloaded it and it immediately started syncing. Now it syncs after every observation which is a bad thing for a variety of reasons.

**Comment by naturalistcharlie** [comment]
Sorry, didn't mean to post yet. I'm on my phone. But anyway closing and reopening the app stopped the issue.

**Comment by kueda** [comment]
So it's trying to sync every time you return to the observations list?
Alex, maybe we should not automatically pull down updates (and thus trigger
an upload) when the list appears if there's anything to upload? Ie only
trigger sync when the user asks for it.

**Comment by naturalistcharlie** [comment]
Yeah but only after that other crash happened. Not sure if that tells you
anything. But yeah I think being able to choose when to sync is best. Among
other things I am often out of cell phone service and trying to sync with
bad or no service can cause problems.

On Wednesday, January 14, 2015, Ken-ichi <notifications@github.com> wrote:

> So it's trying to sync every time you return to the observations list?
> Alex, maybe we should not automatically pull down updates (and thus
> trigger
> an upload) when the list appears if there's anything to upload? Ie only
> trigger sync when the user asks for it.
>
> On Wednesday, January 14, 2015, Charlie <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Sorry, didn't mean to post yet. I'm on my phone. But anyway closing and
> > reopening the app stopped the issue.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/inaturalist/INaturalistIOS/issues/112#issuecomment-69942382>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/112#issuecomment-69947720>
> .
>


-- 
Sent from Gmail Mobile

**Comment by alexshepard** [comment]
should be fixed in later dev builds
