### ISSUE TITLE
edit location not working on ipad

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#113]
When you tap the location in the edit view, you get the choice to use current location or edit location. Choosing to edit location does nothing. iPad Mini (PD528LL/A) iOS 8.1

**Comment by alexshepard** [comment]
Warning: Attempt to present <UINavigationController: 0x7a006400>  on <ObservationDetailViewController: 0x7b876200> which is already presenting (null)

**Comment by alexshepard** [comment]
probably because the navigation controller is still presenting the Edit Location / Current Location action sheet at that point

**Comment by alexshepard** [comment]
should be fixed in b1b6400

**Comment by kueda** [comment]
Works for me in build 88.
