### ISSUE TITLE
Problems building with XCode 6.1.1 and iOS 8.1 SDK

### ISSUE THREAD

**Issue by raulagrait** [inaturalist/INaturalistIOS#119]
I followed the instructions in README.MD in the following order:

git clone git@github.com:inaturalist/INaturalistIOS.git
gem install cocoapods
pod install
cd INaturalistIOS/
cp config.h.example config.h
git submodule init
git submodule update

After doing that, I am getting the following linker errors:
https://gist.github.com/raulagrait/d4d5869ebdb4c555a1b3

This is using XCode 6.1.1 with the iOS 8.1 SDK

**Comment by alexshepard** [comment]
Hi Raul, those errors indicate that Xcode hasn't linked some required libraries into the build. Since the missing libraries are all cocoapods, my guess is that the problem is there. What was the output from the ```pod install``` command? Is there any chance you're still working in iNaturalist.xcodeproj instead of switching to iNaturalist.xcworkspace as ```pod install``` instructs?

**Comment by raulagrait** [comment]
@alexshepard Hi, thanks for the response. Here is the output of `pod install`: https://gist.github.com/raulagrait/3f31eed4c7fbca518626. It seems to be fine, and I am working with `iNaturalist.xcworkspace`. Any other ideas?

**Comment by raulagrait** [comment]
If it's helpful, here are some other linker warnings I am getting in addition to the errors: https://gist.github.com/raulagrait/7fae6a818a315d51e102

**Comment by alexshepard** [comment]
Out of curiosity, what's your build computer?

**Comment by raulagrait** [comment]
@alexshepard: MacBook Pro, Retina, 15-inch, Late 2013.

**Comment by alexshepard** [comment]
Hi Raul,

Apologies for taking so long to get back to you. We just recently switched entirely to cocoapods, migrated to 64-bit Xcode builds, and tweaked the cocoapods configurations.

Can you try again with the top of master?

Thanks,
alex

**Comment by raulagrait** [comment]
@alexshepard Just tried again with the latest, and everything is working great now. Thanks!

**Comment by alexshepard** [comment]
@raulagrait Awesome! Pull requests happily accepted! :)

**Comment by raulagrait** [comment]
Nice! I'll look through the open Github issues, let me know if there's anything in particular I can help out with.
