### ISSUE TITLE
rotation screws up camera on iPad

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#12]
The iPad's weird little inner window does not handle rotation well. I assume there's some official way around this.
![photo jan 27 5 22 11 pm](https://f.cloud.github.com/assets/22691/2015457/caeca62a-87ba-11e3-91e2-688dd054c227.png)

**Comment by alexshepard** [comment]
we're no longer using the camera-in-a-window. closing until/unless this comes back.
