### ISSUE TITLE
New observation behavior

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/INaturalistIOS#121]
One of the things I'm starting to think about is how we can use the new observation flow to encourage certain behaviors during the act of observation. Do we want more observation notes than we're currently getting, or different information in observation notes, like scale or anything? Is the way we do taxa/species guess right now working well? Should we emphasize or de-emphasize project observation fields compared to the current flow?

**Comment by loarie** [comment]
I agree with Ken-ichi that for now, probably just focusing on getting great photos is the best. Down the road it would be awesome to present some 'projecty' things to do based on what we know during the act of observation - for example, if they're marking it as a flowering plant, might be interesting to ask if its in flower - but I think we might want to shore up the stories around/use of that kind of metadata before we hardwire it to much into the flows... what do you think?

**Comment by alexshepard** [comment]
I'm not convinced the taxon/species guess field works really well. It's overloading two different fields. If there's an actual taxon identification, then it shows that. If not, it allows the user to enter and display unstructured text, and doesn't do a great job of automatically correlating/coercing that into a taxon.

It does have the benefit of working well offline,  but I think it leaves new users hanging a little bit.

**Comment by naturalistcharlie** [comment]
I think a neat approach might be popups after the fact, at least when it
comes to the app. I am not going to want to fiddle with fields or other
such stuff when out in the woods, I just want to take hte photo, maybe a
quick ID and a few notes, and leave it at that. But once it's uploaded,
having questions I could whip through like 'is it in bloom', or even 'what
color is it', 'did you see more today' etc could be really easy and fun.

On Fri, Feb 27, 2015 at 4:54 PM, Scott Loarie <notifications@github.com>
wrote:

> I agree with Ken-ichi that for now, probably just focusing on getting
> great photos is the best. Down the road it would be awesome to present some
> 'projecty' things to do based on what we know during the act of observation
> - for example, if they're marking it as a flowering plant, might be
> interesting to ask if its in flower - but I think we might want to shore up
> the stories around/use of that kind of metadata before we hardwire it to
> much into the flows... what do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/121#issuecomment-76479021>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by naturalistcharlie** [comment]
for me and most others I have talked to it is 100% essential that the app
works while offline. I can't emphasize this enough. If it means some small
speed bumps for new users, I still think it's worth it. The alternative is
making the app nearly unusable in a lot of places including much of Vermont
to say nothing for countries with less infrastructure than the US that can
really benefit from iNat.

On Fri, Feb 27, 2015 at 5:00 PM, Alex Shepard <notifications@github.com>
wrote:

> I'm not convinced the taxon/species guess field works really well. It's
> overloading two different fields. If there's an actual taxon
> identification, then it shows that. If not, it allows the user to enter and
> display unstructured text, and doesn't do a great job of automatically
> correlating/coercing that into a taxon.
>
> It does have the benefit of working well offline, but I think it leaves
> new users hanging a little bit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/121#issuecomment-76480081>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by kueda** [comment]
Don't worry, we are not going to require internet access to use the app.

**Comment by alexshepard** [comment]
Charlie, what I'm suggesting is that some of the decisions we've made to accommodate offline users could have been designed differently, so they are just as functional while offline but also work in a predictable way that doesn't present as steep of a learning curve for new users.

**Comment by naturalistcharlie** [comment]
Fair enough! I confess I don't fully see the steep learning curve as I
didn't experience that when I started using it, but of course will defer to
you since you've talked to a lot more people about it than I have. For what
it's worth it's already by far the most usable app of its type ive ever
used.

On Fri, Feb 27, 2015 at 5:13 PM, Alex Shepard <notifications@github.com>
wrote:

> Charlie, what I'm suggesting is that some of the decisions we've made to
> accommodate offline users could have been designed differently, so they are
> just as functional while offline but also work in a predictable way that
> doesn't present as steep of a learning curve for new users.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/121#issuecomment-76482447>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement
