### ISSUE TITLE
date selector hides toolbar

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#123]
When editing a synced observation, opening the date selector, changing the time, and tapping "Done" seems to hide the toolbar with the "Save" button. iPhone 5, build 97

**Comment by loarie** [comment]
Likewise on Edit observation, if the 'What did you' taxon thumb hasn't yet loaded, when it loads the 'save' toolbar which slides up from the bottom slides down and disappears.

**Comment by alexshepard** [comment]
cbd23c7d3fa8c320a8d6a3e3afb5c2555c90e534 should also fix the rest of the cases where this happens.
