### ISSUE TITLE
deleting a photo leaves you with a weird UI

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#124]
After deleting a synced photo on a synced observation I got this:

![img_5148](https://cloud.githubusercontent.com/assets/22691/6537120/a4ca205e-c408-11e4-8792-5aab703f847e.PNG)

So, toolbar floating off in a weird place. iPhone 5, build 97

**Comment by pleary** [comment]
I can replicate this in iOS8, iPhone 6, build 115

 - open an existing observation
 - add a new photo
 - open the image gallery viewer and various wonkiness appears including this UI hiccup

**Comment by alexshepard** [comment]
should be fixed as of b26f6fa980a883c43ad15ddbed5abb78e80f5555

**Comment by alexshepard** [comment]
@kueda @pleary either of you seeing this anymore?

**Comment by kueda** [comment]
Nope, seems to be fixed for me in build 126.
