### ISSUE TITLE
don't localize observed_on_string

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#128]
See https://groups.google.com/d/topic/inaturalist/8tE0QTT_kzc/discussion. I haven't replicated it, but it seems like the app is submitting values like "Sa. März 07 2015 11:59:14 GMT+0100 (MEZ)" for `observed_on_string`. We could deal with this in the Rails app with some better parsing (and maybe we should), but it seems like it might be easier to just not localize that in the app. Thoughts?

**Comment by kueda** [comment]
@pleary If you know of an easy way to handle this server side? I don't think chronic is that savvy to localization.

**Comment by alexshepard** [comment]
NSDateFormatter can take a locale, so we should be able to enforce this in the app.

**Comment by alexshepard** [comment]
should be fixed as of ddb137a
