### ISSUE TITLE
autosync under weak to no cell reception causes infinite loop of error messages

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#129]
Build 105. Unfortunately I can't replicate this in airplane mode or without cellular data, but I recorded a single observation under actual poor-to-nil cell reception today with autosync on and my observations list got stuck in a loop of trying to show an alert message and dismissing it. I couldn't even read the message, or do anything other than force quit the app. Re-opening the app under similar network conditions had the same effect, rendering the app unusable. When I re-opened the app with wifi available, the observation synced, but created a duplicate without a photo.

**Comment by alexshepard** [comment]
removing from the march-2014-app-freeze milestone since auto sync got pulled for this release.

(also, isn't it 2015?)
