### ISSUE TITLE
no alerts about no network without explicit action

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#130]
There are numerous places in the app where it will show an alert about needing a network connection even if the user hasn't done anything. One example is when starting the app fresh and showing the observations list of a signed in user. Without an Internet connection it will show an error message of not being able to load some/url.json, even though the user didn't do anything other than start the app. I think all such alerts should be suppressed, and the app should only show an alert about needing a network connection with the user explicit takes an action that requires network, like pulling to refresh, syncing an observation, searching for taxa, etc. Automatically pulling updates, autosyncing observations, loading iconic taxa in the background, etc. should not.

**Comment by alexshepard** [comment]
backing off of alerts in 25b01c9

**Comment by alexshepard** [comment]
are we still seeing this anywhere?

**Comment by naturalistcharlie** [comment]
I was seeing this happen today but maybe i bumped sync or something.

On Friday, July 10, 2015, Alex Shepard <notifications@github.com> wrote:

> are we still seeing this anywhere?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/130#issuecomment-120563882>
> .
>


-- 
Sent from Gmail Mobile

**Comment by alexshepard** [comment]
ok, i'll keep this open. if we see it anywhere, please let me know and i'll squash it!

**Comment by alexshepard** [comment]
closing since it's 2017
