### ISSUE TITLE
saving a no-photo observation brings you back to the camera

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#131]
Build 105. To replicate, tap observation icon, choose no-photo, save the observation. You'll be brought back to the camera with a blank green toolbar.

Incidentally, you also get that blank green toolbar when you cancel instead of saving the no-photo obs.

**Comment by alexshepard** [comment]
should be fixed in b61783e26f8ebe9d2cb012ec9cd0089d9e2c3503
