### ISSUE TITLE
no badge on "Me" tab if autosync is on

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#132]
Build 105. Right now when you add an observation, it adds a red badge to the "Me" tab before the new observation has been uploaded, then removes it when sync is complete. To me, the badge indicates that the user's attention and maybe action is required, but this shouldn't be the case if autosync is on.

**Comment by alexshepard** [comment]
removing the march-2014-app-freeze milestone, since autosync is on hold
