### ISSUE TITLE
new observation cancel behavior

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/INaturalistIOS#134]
@kueda wrote in chat:

> another issue that seems too subjective for an issue: when i cancel from the obs detail view, my  expectation is that it cancels the entire flow and brings me back to the obs list, not pops me back to the last controller in the stack
> 
> that could just be me, though
> 
> maybe cancel should say "Back" for that screen, and there should be a delete option somewhere?

**Comment by alexshepard** [comment]
This is in conflict with #258, which requests the opposite behavior.

**Comment by joellebel** [comment]
@kueda can you comment on https://github.com/inaturalist/INaturalistIOS/issues/258 tnx! This way we can close one of these issues ;)
