### ISSUE TITLE
add photo -> save w/o sync -> remove photo: incorrect upload/sync message

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/INaturalistIOS#135]
> One other thing related to that - if I save (and not sync), then go in and remove the photo, it tells me (incorrectly) there's 1 photo to upload

- @pleary

**Comment by pleary** [comment]
This might be a component of a larger bug, or UI issue(s).

One small thing which applies to photos and metadata: you can add a photo, save, then remove the photo and it says "Upload 1 photo". You can also add a description, save, then remove the description and it says "Upload 1 observation". Uploading the observation works fine. It changes the updated_at date on the record and presumably nothing else.

Bug (this ticket): Choosing the upload the 1 photo shows the syncing loader indicator and the "Stop sync" green button and hangs there indefinitely. I can stop the sync and the "Upload 1 photo" message goes away and all is well.

The next thing I noticed is that I never intended to save the photo in the first place, hence why I wanted to delete it. I notice that if I take a photo then do pretty much anything else but cancel (like view the image I just took, read the observation activity, or swipe to another observation) then the observation is automatically saved. Same goes with changing any other metadata - the observation seems to be saved automatically when the observation edit screen loses focus, except when the user presses Cancel.

This seems strange to me - that there is also a cancel option on the observation page, but I can do lots of things that will automatically save the record w/o asking me. When that happens I can't Cancel anymore. I wonder if it would be better to simply know if the current state of the observation is different from the saved state, and offer users a 'revert unsaved changes' option. That way all changes can be tentatively saved regardless of how the user navigates, and still lets them undo.

**Comment by naturalistcharlie** [comment]
This probably isn't related but just in case... my iNat icon shows I have
26 observations to upload always, no matter what, and has done so since I
started using the Test Flight test version.  No matter now many I actually
have... zero... fifty... it always says 26.

On Wed, Apr 1, 2015 at 3:04 PM, Patrick Leary <notifications@github.com>
wrote:

> This might be a component of a larger bug, or UI issue(s).
>
> One small thing which applies to photos and metadata: you can add a photo,
> save, then remove the photo and it says "Upload 1 photo". You can also add
> a description, save, then remove the description and it says "Upload 1
> observation". Uploading the observation works fine. It changes the
> updated_at date on the record and presumably nothing else.
>
> Bug (this ticket): Choosing the upload the 1 photo shows the syncing
> loader indicator and the "Stop sync" green button and hangs there
> indefinitely. I can stop the sync and the "Upload 1 photo" message goes
> away and all is well.
>
> The next thing I noticed is that I never intended to save the photo in the
> first place, hence why I wanted to delete it. I notice that if I take a
> photo then do pretty much anything else but cancel (like view the image I
> just took, read the observation activity, or swipe to another observation)
> then the observation is automatically saved. Same goes with changing any
> other metadata - the observation seems to be saved automatically when the
> observation edit screen loses focus, except when the user presses Cancel.
>
> This seems strange to me - that there is also a cancel option on the
> observation page, but I can do lots of things that will automatically save
> the record w/o asking me. When that happens I can't Cancel anymore. I
> wonder if it would be better to simply know if the current state of the
> observation is different from the saved state, and offer users a 'revert
> unsaved changes' option. That way all changes can be tentatively saved
> regardless of how the user navigates, and still lets them undo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/135#issuecomment-88596579>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by alexshepard** [comment]
Is this the TestFlight test version that I pushed a few minutes ago?

**Comment by naturalistcharlie** [comment]
It's been that way since I started doing the Test Flight versions and even
after i delete and reinstall. but I didn't install updates recently, I
haven't gotten any emails about it (maybe it just didn't come yet)

On Wed, Apr 1, 2015 at 3:07 PM, Alex Shepard <notifications@github.com>
wrote:

> Is this the TestFlight test version that I pushed a few minutes ago?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/135#issuecomment-88597126>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by alexshepard** [comment]
Looks like you haven't accepted the invitation to join the new TestFlight (Apple bought them and shut down the independent one). Can you accept the invite and download the latest? I can resend the invitation if you can't find it.

**Comment by naturalistcharlie** [comment]
I think I must have lost the invite somehow... I don't remember seeing it.
Sorry about that... can you resend?

I was wondering why there weren't any updates... should have figured I lost
something.

On Wed, Apr 1, 2015 at 3:20 PM, Alex Shepard <notifications@github.com>
wrote:

> Looks like you haven't accepted the invitation to join the new TestFlight
> (Apple bought them and shut down the independent one). Can you accept the
> invite and download the latest? I can resend the invitation if you can't
> find it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/135#issuecomment-88599790>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by naturalistcharlie** [comment]
Hey Alex, this isn't working right, but maybe you should email me directly
so I don't clutter this ticket.

Basically I downloaded the new app, but when I click on the link in the
email it always still directs me to the app store. I click 'open' from teh
app store and it opens test flight but says I have no apps to test. It
tells me I must click on the link in the email. So I do that again and the
same happens, it goes to the app store.

On Wed, Apr 1, 2015 at 3:24 PM, Charlie Hohn <naturalist.charlie@gmail.com>
wrote:

> I think I must have lost the invite somehow... I don't remember seeing it.
> Sorry about that... can you resend?
>
> I was wondering why there weren't any updates... should have figured I
> lost something.
>
> On Wed, Apr 1, 2015 at 3:20 PM, Alex Shepard <notifications@github.com>
> wrote:
>
>> Looks like you haven't accepted the invitation to join the new TestFlight
>> (Apple bought them and shut down the independent one). Can you accept the
>> invite and download the latest? I can resend the invitation if you can't
>> find it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/inaturalist/INaturalistIOS/issues/135#issuecomment-88599790>
>> .
>>
>
>
>
> --
> ============================
> Charlie Hohn
> Montpelier, Vermont
> coyot.es/slowwatermovement
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by naturalistcharlie** [comment]
update: it seemed to work when I used the Apple mail app rather than the
Gmail app. Thank you!

On Wed, Apr 1, 2015 at 3:40 PM, Charlie Hohn <naturalist.charlie@gmail.com>
wrote:

> Hey Alex, this isn't working right, but maybe you should email me directly
> so I don't clutter this ticket.
>
> Basically I downloaded the new app, but when I click on the link in the
> email it always still directs me to the app store. I click 'open' from teh
> app store and it opens test flight but says I have no apps to test. It
> tells me I must click on the link in the email. So I do that again and the
> same happens, it goes to the app store.
>
> On Wed, Apr 1, 2015 at 3:24 PM, Charlie Hohn <naturalist.charlie@gmail.com
> > wrote:
>
>> I think I must have lost the invite somehow... I don't remember seeing
>> it. Sorry about that... can you resend?
>>
>> I was wondering why there weren't any updates... should have figured I
>> lost something.
>>
>> On Wed, Apr 1, 2015 at 3:20 PM, Alex Shepard <notifications@github.com>
>> wrote:
>>
>>> Looks like you haven't accepted the invitation to join the new
>>> TestFlight (Apple bought them and shut down the independent one). Can you
>>> accept the invite and download the latest? I can resend the invitation if
>>> you can't find it.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/inaturalist/INaturalistIOS/issues/135#issuecomment-88599790>
>>> .
>>>
>>
>>
>>
>> --
>> ============================
>> Charlie Hohn
>> Montpelier, Vermont
>> coyot.es/slowwatermovement
>>
>
>
>
> --
> ============================
> Charlie Hohn
> Montpelier, Vermont
> coyot.es/slowwatermovement
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by carrieseltzer** [comment]
Just to chime in here for other possible testers, I too like Charlie have found the app from which I read email on my phone to be fickle about responding to test flight invitations. Mailbox is working for me. Gmail web view in a single sign on app doesn't. 



—

**Comment by alexshepard** [comment]
this original issue isn't relevant anymore, since all of the sync/upload messaging has changed.
