### ISSUE TITLE
Clarify alert language on signout and trigger only when Sync button is presented

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#14]
This issue applies to Version 2.4.0, build 37

Alert on sign out currently reads: "Are you sure? This will delete all your observations on this device. It will not affect any observations you've uploaded to iNaturalist."

Suggest changing to: "Are you sure? This will destroy any changes/additions you've made from this app that haven't been synced with iNaturalist.org"

To clarify that un-synced edits/comments/IDs are also lost. And to skirt confusion for people who don't understand the distinction of local storage on the device and storage on the web, by emphasizing syncing.

Also suggest this alert is only presented when changes are made (e.g. when the Sync button is visible)

**Comment by loarie** [comment]
Checking up on this issue I made last year. As of this post, looks like alert is shown although there are no local changes, so not closing this

**Comment by alexshepard** [comment]
Should we still show an alert, just without the "delete all your observations" text?

Both instagram and twitter prompt with an "are you sure?" message when you tap sign out, and there are no local changes to consider there.

**Comment by kueda** [comment]
Yes, basically all apps have a prompt before sign out. I think we should keep it, regardless of whether there are local changes to consider.

**Comment by alexshepard** [comment]
OK, I'm having trouble understanding what's being proposed in this issue then.

**Comment by alexshepard** [comment]
@loarie @kueda it seems to me that the proposal here is to remove  
>This will delete all your observations on this device.

from the sign out popup. Is this what we want?

**Comment by alexshepard** [comment]
change alert text to "Are you sure? This will destroy any changes/additions you've made from this app that haven't been synced with iNaturalist.org"

**Comment by alexshepard** [comment]
fixed in 1c59cb078e0620b2082f20d91e41fc275f1e3a9f
queued for release in 2.7.11
