### ISSUE TITLE
Trouble Signing in with Facebook

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#141]
Could not sign in with FB after removing iNat from my FB account until the third try. By third try I mean removing iNat and then attempting to login. This process was not successful until the third attempt. (Perhaps I was not waiting long enough to sign in after removing the app from FB?). Ultimately, I was able to sign in though. 
![fb_signin_failed](https://cloud.githubusercontent.com/assets/11527994/7056381/fbca6772-ddff-11e4-8905-ccb71a3ef120.png)

**Comment by alexshepard** [comment]
This is working for me. You said that you were denying some of the permissions the first time you tried to auth with FB, maybe this is something to do with that?

**Comment by joellebel** [comment]
I think I figured it out... I am now able to log in with denying my FB group information. I am also able to login without denying any info. However, I cannot log out and log back in via FB without deleting the app and removing it from FB apps. (I may be a bit of an edge case though... typically users won't be logging in and out a lot).

**Comment by alexshepard** [comment]
Hm, I am able to logout and back in via facebook without any trouble. Maybe something to do with per-account facebook privacy settings? My facebook account is a development-only test account with completely vanilla out-of-the-box privacy settings and no friends. :foreveralone:

**Comment by alexshepard** [comment]
not sure what I can do without a reproducible case.
added analytics for failed logins in 20e0433b3340fadb21a8c6e32e3503cc908ab11d to try to see if real users are running into this.
