### ISSUE TITLE
iOS7 Tabbar turns black

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#144]
For example returning from stats to explore
![](https://slack-files.com/files-tmb/T02F8QXTG-F048ACXQW-5547ae4297/3__tabbar_turns_black_720.png)

**Comment by alexshepard** [comment]
hopefully fixed as part of 04c2ff9a708a5140f62eabf92c6955b186f707f9

**Comment by loarie** [comment]
fixed in 2.5.4(123)!

**Comment by alexshepard** [comment]
repro case:
1. open explore tab
2. create new observation
3. cancel new observation

**Comment by loarie** [comment]
@alexshepard - are you also using this issue to track top navbar turning black? If so, here's a case in build 139 thats triggering a black navbar for me:
1. open guide detail view
2. tap on photo to open photo viewer
3. '< Back Photos for XXX' is black and tapping 'Back' results in black top navbar
