### ISSUE TITLE
iOS 7 Transparent tab bars  hard to read when overflow  

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#146]
![screen shot 2015-04-09 at 10 29 08 am](https://cloud.githubusercontent.com/assets/598026/7072715/4b4102ae-dea3-11e4-821f-b97bec786e37.png)

**Comment by alexshepard** [comment]
@loarie is this fixed for you?

**Comment by loarie** [comment]
mostly - still trying to find the view controller that still resets this...

**Comment by carrieseltzer** [comment]
Head ellq

**Comment by carrieseltzer** [comment]
Eek sorry guys. Toddler got the iPad and had her say!

**Comment by alexshepard** [comment]
repro case:
1. open explore tab
2. create new observation
3. cancel new observation
