### ISSUE TITLE
editing observation description doesn't save

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#147]
I have an observation that was downloaded from the website (not created on the device), with a description. When I edit the description and hit "Save", it appears to save, but when I edit the observation again the description is back to its prior state. Also, the sync button does not appear after save.

Build 126

**Comment by alexshepard** [comment]
I'm having trouble reproducing this. Is the behavior consistent?

**Comment by alexshepard** [comment]
is there any chance the edited description had the exact same number of characters?

**Comment by alexshepard** [comment]
if the edited text is the same number of characters as the original text, this test doesn't work:
https://github.com/inaturalist/INaturalistIOS/blob/master/INaturalistIOS/ObservationDetailViewController.m#L189

**Comment by alexshepard** [comment]
Just looking at the code, I believe the same is true for all of the string comparison && string length comparison `if` statements in `-uiToObservation`

I'm not sure why those string length tests were added here? https://github.com/inaturalist/INaturalistIOS/commit/1b31076e8b64c3da0031dd94931f3694ba7efc44

**Comment by kueda** [comment]
Yeah, I'm editing http://www.inaturalist.org/observations/1390109 and trying to change

`Turns out Hesse moths love black safe`
to
`Turns out these moths love black sage`

So same number of chars. I probably added those as a dumb way to detect change before attempting to update the CoreData record.

**Comment by alexshepard** [comment]
should be fixed in ff561020a5aac6c28e83f02a7f2c285a0b70a254
