### ISSUE TITLE
Searching for projects without places pans to 0,0 at max zoom, should show min zoom

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#150]
Currently, searching for projects without places pans to 0,0 at max zoom (all ocean), a min zoom (ie one showing the global extent of these projects) might be clearer
![photo 19](https://cloud.githubusercontent.com/assets/598026/7149485/d58d2654-e2c2-11e4-8a1b-46f40c65050f.PNG)

**Comment by alexshepard** [comment]
should be fixed in 5646dc696eef0ca5e247c259ad1ea0754fb68c0e

projects on the node api don't return coordinates or place ids, so the explore tab won't show places for any projects at all until we have a way to get the place information in the api.
