### ISSUE TITLE
Pan on place search not always working

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#152]
If I search for place=Texas and orient the pan/zoom such that CA is not within the map bounds and then search for place=Pepperwood, the map does not pan to the centroid of Pepperwood as expected
![photo 3 6](https://cloud.githubusercontent.com/assets/598026/7149501/0f3608b2-e2c3-11e4-92a3-f43bb42de872.PNG)
![photo 4 5](https://cloud.githubusercontent.com/assets/598026/7149503/1e5c4a2c-e2c3-11e4-96ce-405cd2040199.PNG)

**Comment by alexshepard** [comment]
this worked for me sometimes, but scott's specific case definitely fails

**Comment by alexshepard** [comment]
Released in 2.7
