### ISSUE TITLE
build 129 has photo orientation problem for photos added later

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#155]
When you add a photo to an existing observation, it does not correctly interpret camera orientation. This incorrect orientation is also passed to iNat after syncing.

To replicate:
Start new observation from camera roll photo.
Select vertically oriented photo.
Etc.
Save observation
Tap on observation to edit
Add another vertically oriented photo form the camera roll
Observe that the photo displays horizontally instead of vertically.
Sync to iNaturalist. 
Observe incorrect orientation of second photo on iNaturalist as well. (e.g. http://www.inaturalist.org/observations/1395815)

**Comment by alexshepard** [comment]
Looks like the QBImagePicker is a bit out of date already.

First step to fix this, I'll try updating to the latest. :)

**Comment by carrieseltzer** [comment]
I'm Still having this problem in build 131. Happens on both 8.1.2 (iPhone) and 8.3 (iPad). 



—

**Comment by alexshepard** [comment]
Appears fixed for me as of the latest build 132, released Thursday afternoon.

**Comment by carrieseltzer** [comment]
Yes, I agree!

On Thu, Apr 16, 2015 at 9:00 PM, Alex Shepard <notifications@github.com>
wrote:

> Appears fixed for me as of the latest build 132, released Thursday
> afternoon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/155#issuecomment-93870833>
> .
>



-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org

**Comment by alexshepard** [comment]
Thanks for the report! Closing for now.
