### ISSUE TITLE
iPad Observation Tooltip Wrong Location

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#159]
### Steps to Reproduce
* Download app
* While tooltip is active, rotate orientation

### Expected Behavior
* Tooltip should remain directly above capture button

### Actual Behavior 
* Tooltip hovers over armpit of observer
<br>

![image](https://cloud.githubusercontent.com/assets/11527994/7377348/ae0f6b22-ed9a-11e4-9d52-9d2343a447e4.png)

**Comment by alexshepard** [comment]
fixed in a4d7593029e7e6f7717b7d333336d22c370d29ba

**Comment by alexshepard** [comment]
safe to close, @joellebel ?
