### ISSUE TITLE
App crashes when clicking on guides with no wifi

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#16]
To replicate:
1. With wifi connection launch iNat (2.4.0, build 39), go to Guides tab and use 'refresh' icon to load in some guides

2. Set app to airplane mode

3. Return to app and guides tab and click on a guide that has not been downloaded for offline use

4. Alert: Failed to download guide
the internet connection appears to be offline
OK

5. Crash

6. On restart:
Whoops!
Looks lie there was an error: The client is unable to contact the resource at https://www.inaturalist.org/guides.json?longitude=-122.423238&latitude=37.756315&locale=en=US

**Comment by alexshepard** [comment]
@loarie ?

**Comment by loarie** [comment]
testing

**Comment by loarie** [comment]
looks fixed
