### ISSUE TITLE
Edit Observation Screen, "What did you see" field wrong button graphic

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#162]
On the Edit Observation screen in the "What did you see" there is a search icon button that when tapped deletes the field content.

### Steps to Reproduce
* Tap on observation with iNat ID
* Tap the "What did you see?" field search icon
* Field content is deleted

### Expected Behavior
* The "What did you see?" field search icon is a delete button.

### Actual Behavior 
* The "What did you see?" field delete icon is a search icon.

<br>

Version 2.5.4, build 134

**Comment by carrieseltzer** [comment]
Yes! This totally explains what I saw happen to my boss when I walked him through adding an observation. Definitely a bug. Thanks for finding this. 



—

**Comment by alexshepard** [comment]
These buttons are gone now, closing.
