### ISSUE TITLE
adding observations from project list should use photo-first flow

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#164]
Currently it takes you to the observation detail view, which means if you are importing a photo, it will not use the photo's metadata. See https://groups.google.com/d/topic/inaturalist/jU2WYSJRKHs/discussion

This also implies that tapping the "Add" buttons next to the taxa should launch the photo-first flow and retain the taxon choice when they land on the obs detail view.

**Comment by alexshepard** [comment]
interesting. do you think this is worth trying to squeeze into the bugfix build?

**Comment by kueda** [comment]
If you can, yes. Or resurrect the "Import from metadata" popup.

**Comment by kueda** [comment]
As far as I can tell this is fixed as of build 139.
