### ISSUE TITLE
'Add' buttons from Project view do not select project in observation form

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#165]
Step 1: tap on a project you've joined
Step 2: click 'Add'
Step 3: complete observation flow up to Observations detail view
Step 4: **notice no project chosen**
Step 5: Save and Sync
Step 6: **notice no serverside project observation created**

**Comment by joellebel** [comment]
The project-specific observation fields also are not showing up.

**Comment by joellebel** [comment]
The project rules are also not being enforced.

**Comment by alexshepard** [comment]
should be fixed in latest

**Comment by alexshepard** [comment]
@loarie safe to fix?

**Comment by alexshepard** [comment]
@loarie @joellebel closing this, please re-open if this is still an issue
