### ISSUE TITLE
Search term clearing not working

### ISSUE THREAD

**Issue by pleary** [inaturalist/INaturalistIOS#167]
v2.5.5 (139), iPhone 6

In the explore tab, when I enter a search term in the search bar I see an (x) icon, but it isn't responding

**Comment by alexshepard** [comment]
still happening on build 245

**Comment by alexshepard** [comment]
something buggy with how we're setting up the view hierarchy for iOS, it looks like. maybe need to add the search bar _after_ the view has finished loading and appeared?

**Comment by naturalistmellis** [comment]
@alexshepard is this still an issue? I cannot reproduce in 2.7.1 build 464 (iPhone 7 Plus iOS 10.1.1),
