### ISSUE TITLE
Duplicate requests to ObservationFieldValue::create

### ISSUE THREAD

**Issue by pleary** [inaturalist/INaturalistIOS#168]
Looking through Kibana I noticed many cases of repeated requests to the same action, by the same user all appearing to use the iOS app. Here are some selected headers from one of these duplicate requests:

`{
  "end_time": "2015-05-13T12:40:03.856-07:00",
  "controller": "ObservationFieldValuesController",
  "action": "create",
  "params": {
    "observation_field_value": "{\"observation_field_id\"=>\"2646\", \"observation_id\"=>\"1468181\", \"value\"=>\"shoreline\"}"
  },
  "format": "json",
  "method": "POST",
  "path": "/observation_field_values",
  "status": 422,
  "HTTP_USER_AGENT": "iNaturalist/2.5.4 (iOS iPhone OS 8.1.2 iPhone)",
  "X_MOBILE_DEVICE": "iPhone",
  "ssl": "true",
  "start_time": "2015-05-13T12:40:03.835-07:00",
  "controller_action": "ObservationFieldValuesController::create"
}`

Alex noticed the status 422, and I haven't yet tried to duplicate this request to see what the response is. Here's a quick chart of how many times individual users are hitting ObservationFieldValuesController::create

![screen shot 2015-05-13 at 6 34 20 pm](https://cloud.githubusercontent.com/assets/48566/7622575/dbb56f6c-f99e-11e4-84bf-9339a4d017e2.png)

**Comment by alexshepard** [comment]
In at least some of these cases, project observation field allowable values were changing from underneath the app's cached project definition.

1. app downloads the project definition, including fields and their allowable values
2. project definition changes, removing an allowable value from a field 
3. concurrent with step 2, user creates a project observation, using the cached project definition, and selects that value that the server has removed (but is still in the cached project definition)
4. during observation sync, the server responds that this isn't an allowed field.

Fixes for this could include:
 * be more aggressive about keeping cached project definitions, observation fields, and allowable values in sync with the server. wouldn't eliminate this error in all cases.
 * respond more appropriately to this specific sync error (422 on project observation field sync)
  * re-fetch the project definition from the server
  * clear any now invalid project observation fields
  * inform the user that the project definition has changed and what they now need to do
 * simply explain to the user what happened and hope they can fix it

**Comment by alexshepard** [comment]
check to make sure that obs field values can trigger the observation upload failure alert UI on the Me Tab. if so, this is probably good enough.

**Comment by alexshepard** [comment]
@pleary is there any evidence that this is still happening?

**Comment by pleary** [comment]
None that I can see looking back at the last 3 months. This can be closed
