### ISSUE TITLE
Reset Password Not Working

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#169]
I do not receive an email after submitting my email address to change my password.

**Comment by kueda** [comment]
To elaborate this *does* work on the website, but in iOS, you complete the webview form, the window closes, everything seems ok, but the email doesn't seem to get sent. I was able to replicate this but didn't go much further to see if the website wasn't responding correctly. Maybe the webview is getting closed before the form has a chance to submit? Not sure if this will be made irrelevant by the new signup / log in flow.

**Comment by kueda** [comment]
As far as I can tell this is not fixed as of build 161. Not a requirement for this upcoming release, but I'd like to get it fixed for the next one.

**Comment by alexshepard** [comment]
should be fixed in fe7f0e32ecd2d2824ee36a2ca4ef1168646f1a8a
in build 168 or later

**Comment by alexshepard** [comment]
is this still broken for you @kueda and @joellebel ?

**Comment by kueda** [comment]
Works for me.
