### ISSUE TITLE
Error when refreshing 'Your Guides' when logged in

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#17]
Tapping the 'curved arrow' refresh button in the upper right
'Whoops! Looks like there was an error: The operation couldn't be completed. (org.restkit.RestKit.ErrorDomain error4.)'

**Comment by alexshepard** [comment]
should be fixed in 38606a6f41fde7ca303f02b71ae7dfaef8f1cdac

**Comment by alexshepard** [comment]
should be fixed in 38606a6f41fde7ca303f02b71ae7dfaef8f1cdac

**Comment by loarie** [comment]
looks fixed to me
