### ISSUE TITLE
new photos displayed with wrong aspect ratio, throws off obs detail layout

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#171]
![img_6130](https://cloud.githubusercontent.com/assets/22691/7844210/90f02c7c-0463-11e5-8850-da325341618a.PNG)

species guess field is right up against the photo carousel thing, too.

**Comment by kueda** [comment]
Addendum that I assume is related: I can't scroll the detail view down far enough to tap on the "Choose projects" button. The scrollview just slides back up and covers the button.

**Comment by alexshepard** [comment]
@kueda this should be fixed as of a little while back, unless you're still seeing it?
