### ISSUE TITLE
Download guide for offline use button often inaccessible due to overlapping tabbar

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#173]
when lots of tags as in Hawaii Plants guide
![img_0796 1](https://cloud.githubusercontent.com/assets/598026/7974473/b52ddf90-0a16-11e5-8fca-18f04f3171bd.PNG)

**Comment by kueda** [comment]
Another one where this is happening: http://www.inaturalist.org/guides/1445

**Comment by alexshepard** [comment]
should be fixed in 211e2d8567e9181954899db3895eb6ee74a50ac6, which will be in the next 2.5.8 build
