### ISSUE TITLE
"Choose projects" hidden/unusable when editing observations

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#174]
Once an observation has been submitted on the iOS app, you effectively cannot add observations to a project from the app because you can't click on the button because it's covered by the delete/save/notifications/share bar. You can see that the option is there, but you can't scroll to it and click on it.

See attached screen shot.

![can t-see-projects](https://cloud.githubusercontent.com/assets/7501183/8064026/112339d8-0ea6-11e5-952a-4dae2e7bdc82.PNG)

**Comment by loarie** [comment]
potentially related to #173

**Comment by alexshepard** [comment]
d'oh! looking into this

**Comment by carrieseltzer** [comment]
Still happening for me in build 161.

**Comment by alexshepard** [comment]
i should have this fixed this afternoon

**Comment by alexshepard** [comment]
this should be fixed in 2.5.6 and 2.5.7 (in the app store). 

@carrieseltzer can you close if you can confirm that it's fixed?

**Comment by carrieseltzer** [comment]
Yes! Looks great in 2.5.7. I'm on my phone now so can't close the issue but can when I get home or you can go ahead. 



—

**Comment by alexshepard** [comment]
thanks carrie!
