### ISSUE TITLE
App should display common names according to device lexicon

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#176]
the device lexicon should influence the display of the lexicon of common names throughout (already happening on project checklist but not on the following):
1. explore tab (e.g. grid/list view and header/identifications on obs detail
2. taxon details page
3. species chooser

Logic should be to show common name in lexicon if it exists, if not english, if not next available common name

**Comment by alexshepard** [comment]
explore tab is now using locale

**Comment by alexshepard** [comment]
Taxon chooser and Projects are doing this. Only thing to check is Taxon details.

**Comment by alexshepard** [comment]
need to check taxon details

**Comment by alexshepard** [comment]
taxon details is using device locale
