### ISSUE TITLE
TestFlight Current Ap Version: Can Not Add Observations to Project

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/INaturalistIOS#178]
In the current test version of the iOS app (build 160)... once an observation is uploaded, you can not go back and add it to a project because the 'save' button blocks the 'add project' button.

**Comment by carrieseltzer** [comment]
I noticed this too and opened an issue the other day: https://github.com/inaturalist/INaturalistIOS/issues/174

**Comment by naturalistcharlie** [comment]
Oops! I will chose this one, sorry!
