### ISSUE TITLE
Option to deactivate sync unless over wifi?

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/INaturalistIOS#179]
Ever since the 'sync' button became very large and near the save button I keep accidentally pressing it.  This often happens when I am in the field with little or no cellular connection, and either way I very rarely if ever want to sync over the phone network. When I bump the button it often dumps a bunch of observations on before I notice and can stop it so then the photoless observations just sit there until I get home...  Is it possible to have an option to deactivate the sync unless on wifi?

**Comment by kueda** [comment]
We are in the process of rethinking and redesigning how we do "sync," including automatically syncing in the background and a relocation of where that button is, so we'll see if this is really still necessary when we've gotten through that. I'll leave this open for now, though.

**Comment by naturalistcharlie** [comment]
Makes sense, thanks. Looking forward to seeing what you come up with. If
you do automatic sync my strong request would be to make it optional. I can
see some times one would want it, like some bioblitzes, but let's just say
autosync is a main reason I stopped using a different app I used before
Inat.

On Thu, Jun 18, 2015 at 4:35 PM, Ken-ichi <notifications@github.com> wrote:

> We are in the process of rethinking and redesigning how we do "sync,"
> including automatically syncing in the background and a relocation of where
> that button is, so we'll see if this is really still necessary when we've
> gotten through that. I'll leave this open for now, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/179#issuecomment-113282089>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by kueda** [comment]
It will be optional. It will be the default for new users, but probably not turned on for existing users.

**Comment by carrieseltzer** [comment]
If there's a way to make it auto sync but only when connected to wifi I
think that would be ideal.

On Thu, Jun 18, 2015 at 4:37 PM, Charlie <notifications@github.com> wrote:

> Makes sense, thanks. Looking forward to seeing what you come up with. If
> you do automatic sync my strong request would be to make it optional. I can
> see some times one would want it, like some bioblitzes, but let's just say
> autosync is a main reason I stopped using a different app I used before
> Inat.
>
> On Thu, Jun 18, 2015 at 4:35 PM, Ken-ichi <notifications@github.com>
> wrote:
>
> > We are in the process of rethinking and redesigning how we do "sync,"
> > including automatically syncing in the background and a relocation of
> where
> > that button is, so we'll see if this is really still necessary when we've
> > gotten through that. I'll leave this open for now, though.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/inaturalist/INaturalistIOS/issues/179#issuecomment-113282089
> >
> > .
> >
>
>
>
> --
> ============================
> Charlie Hohn
> Montpelier, Vermont
> coyot.es/slowwatermovement
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/179#issuecomment-113282382>
> .
>



-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org

**Comment by naturalistcharlie** [comment]
I'd worry that defaulting it as on could cause a lot of problems:

-functionality (frustrating jerkyness could happen where cellphone service
is absent or poor)

-Bandwidth - a new user could burn through a lot of their bandwidth without
realizing it. I know this matters less as phone plans expand but... still a
concern

-geoprivacy - I worry less about this than many but still, it creeps me out
to have a public'pac man' path following me around in real time that anyone
can see. Not that anyone cares or will harass me, maybe I'm just weird,
but... yeah. Also possible people might do it unknowingly. It could really
cut down on the ability of younger people to use the app (I know under 13
they aren't supposed to but... maybe some do).

 The combination of the above three are why I stopped using Project Noah
almost as fast as I started. An option to turn off is good but I personally
am not sure if I would have made it past the initial frustration and gotten
there at all. I know you all do a lot of user research and testing and
stuff, and I trust your judgement and I don't think this is an app-ruiner
or anything. But personally I can't think of any reason why one would want
to have it turned on as default. I know there must be a reason.. but I
can't imagine it. Anyone else like to weigh in?

C

On Thu, Jun 18, 2015 at 4:41 PM, carrieseltzer <notifications@github.com>
wrote:

> If there's a way to make it auto sync but only when connected to wifi I
> think that would be ideal.
>
> On Thu, Jun 18, 2015 at 4:37 PM, Charlie <notifications@github.com> wrote:
>
> > Makes sense, thanks. Looking forward to seeing what you come up with. If
> > you do automatic sync my strong request would be to make it optional. I
> can
> > see some times one would want it, like some bioblitzes, but let's just
> say
> > autosync is a main reason I stopped using a different app I used before
> > Inat.
> >
> > On Thu, Jun 18, 2015 at 4:35 PM, Ken-ichi <notifications@github.com>
> > wrote:
> >
> > > We are in the process of rethinking and redesigning how we do "sync,"
> > > including automatically syncing in the background and a relocation of
> > where
> > > that button is, so we'll see if this is really still necessary when
> we've
> > > gotten through that. I'll leave this open for now, though.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/inaturalist/INaturalistIOS/issues/179#issuecomment-113282089
> > >
> > > .
> > >
> >
> >
> >
> > --
> > ============================
> > Charlie Hohn
> > Montpelier, Vermont
> > coyot.es/slowwatermovement
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/inaturalist/INaturalistIOS/issues/179#issuecomment-113282382
> >
> > .
> >
>
>
>
> --
> Carrie E. Seltzer, Ph.D.
> National Geographic's Great Nature Project
> www.greatnatureproject.org
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/179#issuecomment-113283265>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by carrieseltzer** [comment]
Those are good points Charlie. I think the biggest plus for auto sync is that people already expect it to. They think they are done when they hit save. My mom told me that she didn't realize the big green sync bar was a button she had to press. We suspect some people at the recent Hawaii bioblitz made observations and never synced them. Just a couple of anecdotes. I think the auto sync on wifi would address all of your concerns (if it's possible to implement). 



—

**Comment by naturalistcharlie** [comment]
Yeah if the auto sync were wifi only I'd probably turn it on. The only
exception would be very flaky wifi connections.

On Thu, Jun 18, 2015 at 5:08 PM, carrieseltzer <notifications@github.com>
wrote:

> Those are good points Charlie. I think the biggest plus for auto sync is
> that people already expect it to. They think they are done when they hit
> save. My mom told me that she didn't realize the big green sync bar was a
> button she had to press. We suspect some people at the recent Hawaii
> bioblitz made observations and never synced them. Just a couple of
> anecdotes. I think the auto sync on wifi would address all of your concerns
> (if it's possible to implement).
>
>
>
> —
> Sent from Mailbox
>
>
> On Thu, Jun 18, 2015 at 4:53 PM, Charlie <notifications@github.com> wrote:
>
> > I'd worry that defaulting it as on could cause a lot of problems:
> > -functionality (frustrating jerkyness could happen where cellphone
> service
> > is absent or poor)
> > -Bandwidth - a new user could burn through a lot of their bandwidth
> without
> > realizing it. I know this matters less as phone plans expand but...
> still a
> > concern
> > -geoprivacy - I worry less about this than many but still, it creeps me
> out
> > to have a public'pac man' path following me around in real time that
> anyone
> > can see. Not that anyone cares or will harass me, maybe I'm just weird,
> > but... yeah. Also possible people might do it unknowingly. It could
> really
> > cut down on the ability of younger people to use the app (I know under 13
> > they aren't supposed to but... maybe some do).
> > The combination of the above three are why I stopped using Project Noah
> > almost as fast as I started. An option to turn off is good but I
> personally
> > am not sure if I would have made it past the initial frustration and
> gotten
> > there at all. I know you all do a lot of user research and testing and
> > stuff, and I trust your judgement and I don't think this is an app-ruiner
> > or anything. But personally I can't think of any reason why one would
> want
> > to have it turned on as default. I know there must be a reason.. but I
> > can't imagine it. Anyone else like to weigh in?
> > C
> > On Thu, Jun 18, 2015 at 4:41 PM, carrieseltzer <notifications@github.com
> >
> > wrote:
> >> If there's a way to make it auto sync but only when connected to wifi I
> >> think that would be ideal.
> >>
> >> On Thu, Jun 18, 2015 at 4:37 PM, Charlie <notifications@github.com>
> wrote:
> >>
> >> > Makes sense, thanks. Looking forward to seeing what you come up with.
> If
> >> > you do automatic sync my strong request would be to make it optional.
> I
> >> can
> >> > see some times one would want it, like some bioblitzes, but let's just
> >> say
> >> > autosync is a main reason I stopped using a different app I used
> before
> >> > Inat.
> >> >
> >> > On Thu, Jun 18, 2015 at 4:35 PM, Ken-ichi <notifications@github.com>
> >> > wrote:
> >> >
> >> > > We are in the process of rethinking and redesigning how we do
> "sync,"
> >> > > including automatically syncing in the background and a relocation
> of
> >> > where
> >> > > that button is, so we'll see if this is really still necessary when
> >> we've
> >> > > gotten through that. I'll leave this open for now, though.
> >> > >
> >> > > —
> >> > > Reply to this email directly or view it on GitHub
> >> > > <
> >> >
> >>
> https://github.com/inaturalist/INaturalistIOS/issues/179#issuecomment-113282089
> >> > >
> >> > > .
> >> > >
> >> >
> >> >
> >> >
> >> > --
> >> > ============================
> >> > Charlie Hohn
> >> > Montpelier, Vermont
> >> > coyot.es/slowwatermovement
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> > <
> >>
> https://github.com/inaturalist/INaturalistIOS/issues/179#issuecomment-113282382
> >> >
> >> > .
> >> >
> >>
> >>
> >>
> >> --
> >> Carrie E. Seltzer, Ph.D.
> >> National Geographic's Great Nature Project
> >> www.greatnatureproject.org
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/inaturalist/INaturalistIOS/issues/179#issuecomment-113283265
> >
> >> .
> >>
> > --
> > ============================
> > Charlie Hohn
> > Montpelier, Vermont
> > coyot.es/slowwatermovement
> > ---
> > Reply to this email directly or view it on GitHub:
> >
> https://github.com/inaturalist/INaturalistIOS/issues/179#issuecomment-113286176
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/179#issuecomment-113290579>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by naturalistcharlie** [comment]
and the only reason I'd turn it off then is I don't like to have all my
observations uploaded and then leave the wifi before the photos get to
upliad

On Thu, Jun 18, 2015 at 5:13 PM, Charlie Hohn <naturalist.charlie@gmail.com>
wrote:

> Yeah if the auto sync were wifi only I'd probably turn it on. The only
> exception would be very flaky wifi connections.
>
> On Thu, Jun 18, 2015 at 5:08 PM, carrieseltzer <notifications@github.com>
> wrote:
>
>> Those are good points Charlie. I think the biggest plus for auto sync is
>> that people already expect it to. They think they are done when they hit
>> save. My mom told me that she didn't realize the big green sync bar was a
>> button she had to press. We suspect some people at the recent Hawaii
>> bioblitz made observations and never synced them. Just a couple of
>> anecdotes. I think the auto sync on wifi would address all of your concerns
>> (if it's possible to implement).
>>
>>
>>
>> —
>> Sent from Mailbox
>>
>>
>> On Thu, Jun 18, 2015 at 4:53 PM, Charlie <notifications@github.com>
>> wrote:
>>
>> > I'd worry that defaulting it as on could cause a lot of problems:
>> > -functionality (frustrating jerkyness could happen where cellphone
>> service
>> > is absent or poor)
>> > -Bandwidth - a new user could burn through a lot of their bandwidth
>> without
>> > realizing it. I know this matters less as phone plans expand but...
>> still a
>> > concern
>> > -geoprivacy - I worry less about this than many but still, it creeps me
>> out
>> > to have a public'pac man' path following me around in real time that
>> anyone
>> > can see. Not that anyone cares or will harass me, maybe I'm just weird,
>> > but... yeah. Also possible people might do it unknowingly. It could
>> really
>> > cut down on the ability of younger people to use the app (I know under
>> 13
>> > they aren't supposed to but... maybe some do).
>> > The combination of the above three are why I stopped using Project Noah
>> > almost as fast as I started. An option to turn off is good but I
>> personally
>> > am not sure if I would have made it past the initial frustration and
>> gotten
>> > there at all. I know you all do a lot of user research and testing and
>> > stuff, and I trust your judgement and I don't think this is an
>> app-ruiner
>> > or anything. But personally I can't think of any reason why one would
>> want
>> > to have it turned on as default. I know there must be a reason.. but I
>> > can't imagine it. Anyone else like to weigh in?
>> > C
>> > On Thu, Jun 18, 2015 at 4:41 PM, carrieseltzer <
>> notifications@github.com>
>> > wrote:
>> >> If there's a way to make it auto sync but only when connected to wifi I
>> >> think that would be ideal.
>> >>
>> >> On Thu, Jun 18, 2015 at 4:37 PM, Charlie <notifications@github.com>
>> wrote:
>> >>
>> >> > Makes sense, thanks. Looking forward to seeing what you come up
>> with. If
>> >> > you do automatic sync my strong request would be to make it
>> optional. I
>> >> can
>> >> > see some times one would want it, like some bioblitzes, but let's
>> just
>> >> say
>> >> > autosync is a main reason I stopped using a different app I used
>> before
>> >> > Inat.
>> >> >
>> >> > On Thu, Jun 18, 2015 at 4:35 PM, Ken-ichi <notifications@github.com>
>> >> > wrote:
>> >> >
>> >> > > We are in the process of rethinking and redesigning how we do
>> "sync,"
>> >> > > including automatically syncing in the background and a relocation
>> of
>> >> > where
>> >> > > that button is, so we'll see if this is really still necessary when
>> >> we've
>> >> > > gotten through that. I'll leave this open for now, though.
>> >> > >
>> >> > > —
>> >> > > Reply to this email directly or view it on GitHub
>> >> > > <
>> >> >
>> >>
>> https://github.com/inaturalist/INaturalistIOS/issues/179#issuecomment-113282089
>> >> > >
>> >> > > .
>> >> > >
>> >> >
>> >> >
>> >> >
>> >> > --
>> >> > ============================
>> >> > Charlie Hohn
>> >> > Montpelier, Vermont
>> >> > coyot.es/slowwatermovement
>> >> >
>> >> > —
>> >> > Reply to this email directly or view it on GitHub
>> >> > <
>> >>
>> https://github.com/inaturalist/INaturalistIOS/issues/179#issuecomment-113282382
>> >> >
>> >> > .
>> >> >
>> >>
>> >>
>> >>
>> >> --
>> >> Carrie E. Seltzer, Ph.D.
>> >> National Geographic's Great Nature Project
>> >> www.greatnatureproject.org
>> >>
>> >> —
>> >> Reply to this email directly or view it on GitHub
>> >> <
>> https://github.com/inaturalist/INaturalistIOS/issues/179#issuecomment-113283265
>> >
>> >> .
>> >>
>> > --
>> > ============================
>> > Charlie Hohn
>> > Montpelier, Vermont
>> > coyot.es/slowwatermovement
>> > ---
>> > Reply to this email directly or view it on GitHub:
>> >
>> https://github.com/inaturalist/INaturalistIOS/issues/179#issuecomment-113286176
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/inaturalist/INaturalistIOS/issues/179#issuecomment-113290579>
>> .
>>
>
>
>
> --
> ============================
> Charlie Hohn
> Montpelier, Vermont
> coyot.es/slowwatermovement
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement
