### ISSUE TITLE
photos not storing position

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#180]
![screen shot 2015-06-19 at 9 12 11 pm](https://cloud.githubusercontent.com/assets/22691/8265975/32ee4ed4-16c8-11e5-99f7-5888a85a291d.png)
![img_6316](https://cloud.githubusercontent.com/assets/22691/8265980/e3fc11ca-16c8-11e5-8e97-2e33acdc78ef.PNG)
http://www.inaturalist.org/observations/1649507

Build 163

**Comment by alexshepard** [comment]
The bug is in Models/Observation+AddAssets.m, line 26

Rather than set the op.position to the idx of of the new observation in the list of new observations being added, instead the position should be calculated as the initial count of observationPhotos + the idx.

**Comment by alexshepard** [comment]
fixed in 852acc7560ea0dc6f0d765d623c70c9a9de25959

**Comment by kueda** [comment]
Works for me. Thanks.
