### ISSUE TITLE
Username Change On Web Not Working on Mobile

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#182]
When I change my username on the web app and then pull to refresh on mobile, this is the error message I get. 

![img_0994](https://cloud.githubusercontent.com/assets/11527994/8293937/67a6a87a-18ed-11e5-835c-37659ff77fcd.PNG)

**Comment by alexshepard** [comment]
Cool, thanks for the bug report.

This is happening because we're fetching the user data via /users/<username>.son
In order to fix this, we'll need to start fetching via /users/<userid>.json
But since we haven't been stashing the userid reliably in NSUserDefaults, we can't do that (yet).

**Comment by alexshepard** [comment]
Fixed in the 2.6.15.
