### ISSUE TITLE
upload user profile pic from the app

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#183]
You should be able to upload a user profile photo from within the app. We get this question on the support email from time to time, and I usually send people to http://www.inaturalist.org/users/edit. Will basically look like `PUT /users/:user_id?user[icon]=:multipart_file_data`

**Comment by alexshepard** [comment]
:+1: 

@joellebel what do you think about this? for starters, maybe just tapping on the user photo could present a user icon? further along it might be great to be able to edit my profile, doing stuff like changing my real name and username, altho I'm not sure how often real users do that.

**Comment by joellebel** [comment]
Sounds good to me. Please let me know where we would like this to fall in the timeline so I can design it. Additionally, it would be cool if we had 4-5 different default profile icons that a user could choose from if they do not want to upload their own. Each user would get a random default profile icon when they sign. This way we don't have a sea of the same old boring avatars. 

Here's some ideas for profile icons I think would be fun:

* Scientist
* Hiker
* Person with butterfly catcher
* Scuba diver
* Birder
* Camper with headlamp 
* Safari person with safari hat. Inspiration: (https://s3.amazonaws.com/picollecta-pics-large/M1087/PIC1001831609/AGYVPQYVDX.JPG)
* Adventurer (Indiana Jones type)
* boy with raccoon hat
* girl scout or boy scout

For example, here's what Virgin America offers for account holders. (I am not at all advocating for this style or content for the icons, just wanted to show an example)

![image](https://cloud.githubusercontent.com/assets/11527994/8657013/f7b1a254-294f-11e5-9f11-1a7601c10202.png)

**Comment by alexshepard** [comment]
That looks cool. I would think that would be something that'd be tied to your account, right?

**Comment by joellebel** [comment]
Yes, would be tied to your account, but you would always have the option to upload your own profile pic, of course.

**Comment by alexshepard** [comment]
OK, in that case I'd move that part of this issue over to the general inaturalist github for conversation there, as it's not something we'd be implementing in the iOS app.

**Comment by joellebel** [comment]
Sure thing.

**Comment by kueda** [comment]
FWIW, we're getting about 1 request a week for this at the moment.

**Comment by alexshepard** [comment]
Happy to work on this.

As I said above I think a simple solution could just be the ability to tap on your photo, get an action sheet asking if you'd like to change/add/delete your photo, then if you choose to add or change, take a photo or choose from library and upload to the website.
