### ISSUE TITLE
No Notification When Camera / Photo Access Is Off

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#184]
Currently, if photo or camera is off in the settings menu there is no alert to the user when attempting to upload a photo or use the camera. Therefore, the app may appear broken. 

Here's two solutions. It would be nice to have the ability to enable camera or photo access right from the dialogue box.

![dialogue_box_camera_access](https://cloud.githubusercontent.com/assets/11527994/8362702/4abf775c-1b2f-11e5-85fd-83e1c24e052f.jpg)
![dialogue_box_camera_settings](https://cloud.githubusercontent.com/assets/11527994/8362701/4abcc7be-1b2f-11e5-8dab-6217fb1a6b37.jpg)

The same would go for "Photos". It would be the same messaging except "Camera" is replaced with "Photos":

Photos Access: Please allow iNaturalist access to Photos to proceed

**Comment by alexshepard** [comment]
Done last year.
