### ISSUE TITLE
Deletes wrong photo when an observation has multiple photos

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#188]
If you try to delete 4th photo, it deletes 3rd. If you try to delete 3rd, it deletes 2nd. If you try to delete 2nd, it deletes 1st. If there's only one photo, it deletes it.

To reproduce:
Make a new observation. Select 2-4 photos from the camera roll. Confirm. Select any taxon, or skip. Tap back into photos and go to last photo. Select trash can to delete. Selected photo remains, but photo in position preceding is deleted. 

Version 2.5.7. Build 179

**Comment by alexshepard** [comment]
thanks, should be fixed in 8628a78b68fa7aa792515d3f8c8aacc2eb38857b, will be in the next 2.5.8 beta release

**Comment by carrieseltzer** [comment]
Looks like this is indeed fixed.
