### ISSUE TITLE
Project rules interfering with photo syncing

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#189]
When adding a new observation to a project with the rule "must have media" (or "must have photo"), photos fail to sync and the "Observation already added to this project" error appears (even though it hasn't been added to the project). It's important to note here that <b>if any one observation in a sync operation fails here, all of them appear to fail and the result is observations uploaded without photos, without a clear way for people to understand why their photos aren't syncing.</b>

Steps to replicate:
1. Join this project: http://www.inaturalist.org/projects/weirdwildwonders
2. Open app, add a new observation with a photo, add it to Weird Wild Wonders project, then save.
2s. Add it to another project that doesn't require media.
2b. (For additional testing, add a second observation with a photo that is ONLY added to a project without the media rule)
3. Sync.
4. Observe first error (see first screen shot at end)
5. Observe second error (see second screen shot)
6. See photos for associated observation(s) in limbo ("Upload X photos" highlighted in green sync field, but trying to sync repeats second error about observation already added to a project).  (see third screen shot).
7. Log in to iNaturalist in browser. See observations uploaded without photos, and NOT added to the project with "must have media" rule (even though the error given in the app is "already added to project". Observations ARE added to projects without the media rule. See my two observations:
![screen shot 2015-07-13 at 11 11 08 am](https://cloud.githubusercontent.com/assets/7501183/8653387/109b16d6-2952-11e5-83ea-6773cd9c7c83.png)

User workaround:
-Open observation in app, tap "choose projects" again and then deselect ALL projects for ALL observations tied up in this sync. It doesn't work to just remove the project with the media rule. Sync. 
-Reopen observations after syncing to add to projects, save, and sync again.
Pretty arduous, especially if you've got many observations.

Note: I just tested this on the "has photo" rule too and the same thing happens. To test that, you can use this project: http://www.inaturalist.org/projects/natgeo-gnp-global-snapshot 
Unfortunately, this might explain why there were a few hundred people who submitted observations during the global snapshot without photos (obviously people didn't have to add it to this project for it to be counted, but it might have actually caused them trouble if they tried). I'll dig into this a little more and report back.

Possible solution:
-Sync observation data, photos, and THEN add to projects for new observations.
-Make photo syncs proceed even with these errors.

In summary, there are a few related issues here:
1. Submission to a project in the app happens before photos are added, so additions to projects with photo/media rules fail.
2. Users are told their observation was already added to a project, but it wasn't (because the it fails the rule without media).
3. <b>These errors prevent syncing of photos for already synced observations.</b>
4. Photo syncing for all observations in a batch are hampered by a single observation with a single failed project rule.
5. Unsynced photos are stuck in limbo without clear error messaging for users to know how to get their photos to sync.

Version 2.5.7 build 179

![img_5212](https://cloud.githubusercontent.com/assets/7501183/8653349/e74b3a22-2951-11e5-96c1-e8eca6ab05a3.PNG)

![img_5213](https://cloud.githubusercontent.com/assets/7501183/8653357/f0dfd0c0-2951-11e5-86c7-3c177b96f3ce.PNG)

![img_5214](https://cloud.githubusercontent.com/assets/7501183/8653364/f7d1a6d8-2951-11e5-9d0c-20c459f380f8.PNG)

**Comment by carrieseltzer** [comment]
This is still happening in 2.6 build 204 and prevents an observation from being uploaded at all and holds up other observations. The only way around this is to quit the app and reopen, remove the project from the observation, and then upload again. Now I can confirm that taxon rules also interfere in addition to media rules. See details above for replication.

**Comment by kueda** [comment]
Carrie, is this only happening in the app or can you replicate any part of it on the web?

**Comment by carrieseltzer** [comment]
Good question. On the site you almost always create an observation before trying to add it to a project. However, if you try to add an observation to a project that doesn't meet the rules, it creates the observation but gives a project add error (e.g. http://www.inaturalist.org/observations/1888316). 

![screen shot 2015-08-24 at 3 23 43 pm](https://cloud.githubusercontent.com/assets/7501183/9449963/f27f0d9a-4a73-11e5-862a-69fd6281e169.png)

**Comment by carrieseltzer** [comment]
Sorry, I think I should add that what instead of uploading all observations and then failing on the photo part of the upload, the process now fails to finish the upload and move on to the next observation. So one observation failing a project rule can still hang up the process, but it presents slightly differently in this version of the app (thanks to the change to upload one entire observation at a time). The steps to replicate this error should still work.

**Comment by carrieseltzer** [comment]
I think someone in the Google group is having this problem. I hope there's enough detail here for you to troubleshoot, but let me know if you need clarification. 

https://groups.google.com/forum/#!topic/inaturalist/yAcKhbXKcO0

**Comment by alexshepard** [comment]
Hi Carrie,

Can you try again with build 214 (uploading to TestFlight right now)?

Thanks,
alex

**Comment by alexshepard** [comment]
Or I should say with build 215, as 214 had an odd TestFlight issue for me and at least one other where it wouldn't install.

Thanks, alex

**Comment by carrieseltzer** [comment]
Awesome! I clearly see the error when it fails a project rule for media or location. Failing a taxon rule doesn't give an error but successfully uploads and adds it to the project. I think this is ok since it probably doesn't happen very often and others can remove an inappropriate observation from a project.

If you have more than one observation to upload, a prior one failing still prevents the others if you try to do them all, but you can easily do them individually so hopefully people will figure that out. It's also not necessarily clear when you get an error message related to failing a rule that it has to do with a project, but this is a HUGE improvement and hopefully people can figure it out. 

One small thing--when you stop (or it stops) an upload, the green button stays on the X and doesn't change back to the upload again. Let me know if you want a new issue opened for that.

P.S. I also had that issue with 214 failing to install.

**Comment by alexshepard** [comment]
Alex: make sure that photos upload before projects.
@carrieseltzer is this still happening for you?

**Comment by carrieseltzer** [comment]
Now it gives a clear error message that the observation needs attention. However, in the app it says, "1 observation to upload" with the message if you click into it "Could not be added to project WeirdWildWonders. Didn't pass rule: must have media." But it has been uploaded already and I can see it on the website. 

It would be nice if tapping the error message brought you to the project rules page. 

While testing for this, I discovered a major location bug so I'll make a new issue for that.

**Comment by carrieseltzer** [comment]
What a time capsule! :-) This is no longer happening.
