### ISSUE TITLE
network activity during autorotation

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/INaturalistIOS#190]
looks like there's network activity happening during autorotation, which can trigger a "network not available" alert and is also apparently triggering a RestKit crash for @loarie

**Comment by loarie** [comment]
In the field I was using the app in a no Wifi area and autorotation was crashing the app for me on the me tab. To reproduce the 'no network' alert autorotation trigger, put your phone in nowifi nocelldata mode and go to any non explore tab and rotate and you should get the 'no network' alert

**Comment by alexshepard** [comment]
@loarie, does this only happen if you've opened the explore tab?

ie - 

1. kill the app and start from scratch
2. don't open the explore tab
3. rotate the phone

do you still see the 'no network' alert?

trying to isolate what's causing the alert...

**Comment by loarie** [comment]
Correct, it does this only happen if you've opened the explore tab. So for example:

1. kill the app and start from scratch
2. don't open the explore tab
3.  rotate the phone
nada
4. open the explore tab and see alert #1 
5. go to me tab
6. rotate and see alert #2

**Comment by alexshepard** [comment]
no longer reproducible for ken-ichi or i. @loarie can you re-open if you can reproduce.
