### ISSUE TITLE
Don't waste so much storage

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/INaturalistIOS#195]
As cameras in phones get better, our permanent storage of full size originals is more and more problematic. The only way to recover storage space is to log out and back in.

Better would be for ImageStore to intelligently manage the size of its cache, keeping track of which images have been uploaded and scheduling them for cleanup. This could even include a user setting for size of cache to use.

This has come up in the Google Group as well as in our App Store reviews, so it's fair to say this is a real user concern.

**Comment by naturalistcharlie** [comment]
I've been running into this problem a lot lately. If it comes up where I
can't sync I can't log out without losing all my obs. Personally I'd prefer
the photos only be on the cloud/site after upload. But maybe an option to
toggle if others disagree.

On Saturday, August 1, 2015, Alex Shepard <notifications@github.com> wrote:

> As cameras in phones get better, our permanent storage of full size
> originals is more and more problematic. The only way to recover storage
> space is to log out and back in.
>
> Better would be for ImageStore to intelligently manage the size of its
> cache, keeping track of which images have been uploaded and scheduling them
> for cleanup. This could even include a user setting for size of cache to
> use.
>
> This has come up in the Google Group as well as in our App Store reviews,
> so it's fair to say this is a real user concern.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/195>.
>


-- 
Sent from Gmail Mobile

**Comment by carrieseltzer** [comment]
Another user reported deleting observations to make space in the Google group. 
https://groups.google.com/forum/#!topic/inaturalist/ogBvCbH-LVA

Two possible short-term solutions:
-When you can't add more observations because you've run out of space, use the popup message to instruct people to log out and log back in to clear some space.
-Create a "clear cache" option in settings that has the effect of logging out and in without the hassle.

**Comment by naturalistcharlie** [comment]
yeah, this really needs to get fixed... also one of the admins may want to
reach out to her to help her recover them... she seemed frustrated,
understandably so.

On Fri, Mar 25, 2016 at 10:03 AM, carrieseltzer <notifications@github.com>
wrote:

> Another user reported deleting observations to make space in the Google
> group.
> https://groups.google.com/forum/#!topic/inaturalist/ogBvCbH-LVA
>
> Two possible short-term solutions:
> -When you can't add more observations because you've run out of space, use
> the popup message to instruct people to log out and log back in to clear
> some space.
> -Create a "clear cache" option in settings that has the effect of logging
> out and in without the hassle.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/195#issuecomment-201295118>
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by alexshepard** [comment]
The iOS app now is much more aggressive in clearing cached photos (only once they've been uploaded to the server, of course).

**Comment by stragu** [comment]
@alexshepard did something change since this fix? I had to use the log out / log back in workaround because my app data swelled up to 1 GB (all observations already uploaded). It seems to be a current problem on both Android and iOS (I use iOS).
https://forum.inaturalist.org/t/limit-cache-size-or-allow-cache-clearing-for-apps/2059/28

Using:
iNaturalist 2.8.7
iOS 13.3.1

**Comment by marcelhospers** [comment]
On the forum is a recent user were iNaturalist takes 20GB
https://forum.inaturalist.org/t/advice-on-data-storage-on-inaturalist/29110

**Comment by stragu** [comment]
I have an issue that might not be the same: the app itself doesn't swell up too much, but I feel like anytime I make use of the app, it keeps making the "Other" section of the iOS storage bigger and bigger. The "Other" section (in iOS's Settings > General > iPhone Storage) is currently at about a third of my 16 GB, and I am pretty sure it only expands when I use iNaturalist.
I had to reset my phone to factory settings to clear that up, but it's happening again.

iOS version 14.8
iNaturalist version 3.2.4
