### ISSUE TITLE
"Acc." should be right-aligned

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#196]
Seems left-aligned in build 189.

![img_6778](https://cloud.githubusercontent.com/assets/22691/9049316/892ca4b2-39f5-11e5-82a8-c2c3e72f5a2e.PNG)

**Comment by joellebel** [comment]
Just curious why "Acc." should be right aligned? To be visually consistent, it should be left aligned, as well as the "m". The "m" should also be black, but that's not as big of a deal. (But maybe I'm misunderstanding something?)

**Comment by alexshepard** [comment]
Interesting, @eldadohana this appears to be because you chose NSTextAlignmentNatural for that label in your LTR auto layout pull request. There doesn't appear to be a NSTextAlignmentUnnatural, any suggestions on how to get this to align as originally designed?

**Comment by kueda** [comment]
"5" and "m" should definitely be adjacent, and I don't feel that strongly about the alignment beyond that, frankly. I think it just was right aligned before b/c it leaves a weird gap to the right if it's left aligned and there's only one or two figures.

**Comment by joellebel** [comment]
Ok. The weird space on the right is ok because all other fields are left aligned.

**Comment by eldadohana** [comment]
You are right, It doesn't looks good. We can add the "m" to the acc. string and remove the label.
