### ISSUE TITLE
always fetch location on obs detail for new obs w/ no or poor coordinate precision ("acc")

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#197]
On recent builds, when I start a new obs, take a photo, then land on the obs detail page, the "Acc." (coordinate precision) is often absent or very poor, and the app has stopped fetch new, potentially more precise coordinates. I think when you land on that page from the new obs flow and you have coordinate precision that is over 5 m or absent the app should fire up the GPS again and continue retrieving coordinates until it gets to 5 m or passes the time threshold.

**Comment by naturalistcharlie** [comment]
I just noticed today that some of my recent observations had very poor
location accuracy or even no location. For the ones with poor accuracy they
seem to mostly be in the right place but just with a too-large uncertainty
circle. I will keep an eye on it.

On Mon, Aug 3, 2015 at 6:40 PM, Ken-ichi <notifications@github.com> wrote:

> On recent builds, when I start a new obs, take a photo, then land on the
> obs detail page, the "Acc." (coordinate precision) is often absent or very
> poor, and the app has stopped fetch new, potentially more precise
> coordinates. I think when you land on that page from the new obs flow and
> you have coordinate precision that is over 5 m or absent the app should
> fire up the GPS again and continue retrieving coordinates until it gets to
> 5 m or passes the time threshold.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/197>.
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by kueda** [comment]
@naturalistcharlie, please also report the build number (I realize I failed to do this too). @alexshepard is this fixed as of build 204? Seems like it to me.

**Comment by naturalistcharlie** [comment]
Oops, sorry! In any event I am now on build 204 and I think the problem has
gone away. I haven't tested as extensively as usual, lately, but will let
you know what I find.

On Tue, Aug 11, 2015 at 1:08 PM, Ken-ichi <notifications@github.com> wrote:

> @naturalistcharlie <https://github.com/naturalistcharlie>, please also
> report the build number (I realize I failed to do this too). @alexshepard
> <https://github.com/alexshepard> is this fixed as of build 204? Seems
> like it to me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/197#issuecomment-129971399>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by alexshepard** [comment]
I tweaked the way location fetching is started in b05b198b2cd8fccf349de26552238e59cc8090f0, which went out starting with the 2.6 builds, around the same time that the main app got depth-first-upload and single-item-upload.

However, while my tweaks are more "correct" than the earlier code, I'm not sure they fixed this issue because I haven't seen it myself and didn't do an in-depth bug hunt.

**Comment by alexshepard** [comment]
closing for now
