### ISSUE TITLE
never settle for zero accuracy / precision

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#200]
As of build 202 I'm frequently landing on the observation detail screen and seeing that the location has stopped updating and the accuracy is at zero. I'm pretty sure location services never reports zero accuracy, so I'm guessing that's a bug. IMO if the app sees zero accuracy it should start fetching location again until it gets a non-zero accuracy of 5 m or the time threshold is met. I was only testing in places without cell service, not sure if that's relevant.

![img_6916](https://cloud.githubusercontent.com/assets/22691/9204289/3669328c-4011-11e5-8a58-dad440794719.PNG)

**Comment by alexshepard** [comment]
Pretty sure that 0 accuracy in the current builds means "we have no accuracy data" since I re-wrote how that label is constructed since the RTL merge. What should it say in that situation?

**Comment by kueda** [comment]
I think it used to say "???" So that would work. Or "Unk" or an empty space.

**Comment by alexshepard** [comment]
should be fixed in 24f7c11976ad297379549ba50e79828b324a08e7
