### ISSUE TITLE
observations not showing up on species map

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/INaturalistIOS#209]
I noticed that some newer observations are not showing up on species maps, for instance, this black oak observation: http://www.inaturalist.org/observations/1918359 does not show up on the species range map at http://www.inaturalist.org/taxa/49006-Quercus-velutina . It does, however, show up here: http://www.inaturalist.org/observations?taxon_id=49006 . Also true for http://www.inaturalist.org/observations/1918469 and probably anything else I saw that day. It may just be some sort of indexing lag or something but I thought it was worth reporting especially since it's been six days. 

I use these species maps a lot, not sure how much others do, but I love them thus me noticing these small delays. Thank you!!!

**Comment by pleary** [comment]
Thanks for the report Charlie. There was an issue with some data replication and restarting the replication seems to have fixed the problem. Does it all look OK now?

(Also - perhaps you mistakenly reported this to the wrong project, but regardless of how observations are entered, problems with maps on the website should probably get reported to https://github.com/inaturalist/inaturalist, or if you know it's a backend problem with the mapserver to https://github.com/inaturalist/iNaturalistAPI)

**Comment by naturalistcharlie** [comment]
Oops! I moved it from the windshaft page on Ken-Ichi's request but accidentally moved it to the wrong place.
And yeah... working now, thanks.
