### ISSUE TITLE
observation confirmation screen

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#210]
As per https://github.com/inaturalist/design/issues/7, we're adding a new, more concise screen to the end of the new observation flow that replaces the observation edit screen. Alex has it mostly working as of build 221-ConfirmObs. Some remaining issues

- [x] can't back out of a new observation if you add a photo
- [x] location not getting set for observation without a photo
- [x] canceling out of observations without photos doesn't add anything to the observation list but changes the ui to say "2 observations to upload," and when you upload, they appear in the list
- [x] canceling out of an observation seems to create one anyway
- [ ] can't set a placeholder taxon name (intentional?)
- [ ] text of notes section very small, good for people with decent eyesight, but bad for everyone else, I think
- [x] cannot dismiss the keyboard after editing the notes section
- [x] captive / cultivated needs to be added to the obs edit view
- [x] captive / cultivated not getting set on the website

**Comment by alexshepard** [comment]
- [ ] projects not implemented
- [ ] project observation fields not implemented

**Comment by alexshepard** [comment]
- [ ] delete buttons are really small. too small to reliably tap?
- [ ] default/set default not implemented as per design
- [ ] ID Please and Captive/Cultivated text doesn't fit
- [ ] black bar above Save button
- [ ] tableview section headers are aligned incorrectly

**Comment by alexshepard** [comment]
- [ ] new obs, then add another photo, then tap library, nothing happens

**Comment by joellebel** [comment]
- [ ] new ob, get to final screen, tap back then confirming the photo again creates a duplicate ob. The more you tap Back from the final screen, the more duplicates are created.

**Comment by joellebel** [comment]
- [ ] Text in header is overlapping the spinner. Also, spinner and text should not go outside of Projects and Guides button

![img_5658](https://cloud.githubusercontent.com/assets/11527994/9869881/614c84e0-5b3c-11e5-9d81-0847c93b4b13.PNG)

- [ ] I propose not having the profile photo change at all during auto-upload. There is currently 2 spinners, and 2 messages telling the user of the upload. That should do the trick.

Question: Do we need users to be able to cancel during auto-upload? Most of the time they will not have ample time to cancel.

**Comment by joellebel** [comment]
- [ ] Please use the ion icons ion-ios-calendar-outline icon
- [ ] There is a black border above the Save button
- [ ] Please make "Save" button all caps
- [ ] The section heads need the standard left padding
- [ ] "More" title should not show up if there are no "More" fields
- [ ] The witch for the Cultivated/Captive field is a bit unconventional for this scenario. Typically it is for turning an action On/Off and not Yes/No. Is this because by default an ob has no "Wild or Captive" attribute? "No" by default with a chevron next to it, would be more customary as in the original mock up. We can talk more about it tomorrow.
- [ ] Please make the text for the Notes... text field and all other text fields 15pt.
- [ ] Please use the ion-ios-close-empty for the x on the thumbnails
- [ ] Please make the "Default" text 13pt
- [ ] For setting the default pic, was there a reason the checkbox were not used?
- [ ] I need to work on the lifesaver. Where did you get the icon?

![image](https://cloud.githubusercontent.com/assets/11527994/9872390/f46c9286-5b4d-11e5-83ce-b7860fcec0b6.png)

**Comment by alexshepard** [comment]
if possible, it'd be helpful to keep duplicates out of these "punch lists"

**Comment by alexshepard** [comment]
non iOS 6 the text doesn't fit with icons, title and switch

![ios simulator screen shot sep 15 2015 10 07 35 am](https://cloud.githubusercontent.com/assets/515947/9883892/b5f9403c-5b91-11e5-981c-359d2cc73dc4.png)
![ios simulator screen shot sep 15 2015 10 07 38 am](https://cloud.githubusercontent.com/assets/515947/9883893/b6138eba-5b91-11e5-9f68-ac2d79db8dc1.png)

**Comment by joellebel** [comment]
oops. Sorry about the duplicates. Erasing now.

**Comment by joellebel** [comment]
From a UX perspective I am liking the set up of this final screen. It's a laid out in a pretty digestible format with most important information prioritized first. It also meets all iOS conventions. What do you folks think?

It would be nice if tapping on the photos opens the same slideshow you get when tapping on a photo of ob in the ob detail view. This is another way people can delete a photo. 

I will also work on the photo delete buttons. How time consuming is it to make the touch targets larger than the actual button? I know this is something that will come in handy in the future. 

Also, is it an easy coding thang to make longer bits of text go to two lines. If so, I will mock it up it. Just curious to see what it looks like. (We could also truncate the "Is it captive or cultivated?" to simply "Captive or cultivated".)

**Comment by alexshepard** [comment]
Re the layout: just keep in mind that it doesn't include projects or project field values, which could easily double the scrollable height for just a project or two based on the number of fields. However, with that said, I like it a lot, certainly more than the view we have now.

**Comment by alexshepard** [comment]
Re: photo & delete tapping: I don't think we can realistically have both bigger photo delete targets (which would overlap the photo) and tappable photos.

**Comment by joellebel** [comment]
True about projects but those are not the majority or the main target audience. People who belong to projects will expect more input fields. As long as the Save button is locked to the bottom of the screen, we're golden.

I'll take a look at the delete buttons, but honestly I'm not having trouble tapping them and I have pretty chunky fingers.

**Comment by alexshepard** [comment]
Re: two lines - it's very easy to just make the label wrap. 

However, it doesn't look great:
![ios simulator screen shot sep 15 2015 11 10 38 am](https://cloud.githubusercontent.com/assets/515947/9885539/84ecc55a-5b9a-11e5-860f-ff87a75174c1.png) 
Adjusting the table view cell height to accommodate at-runtime decided one or two lines (based on screen width, text, language) isn't so easy.

Another option is shrinking the text to fit.
![ios simulator screen shot sep 15 2015 11 13 40 am](https://cloud.githubusercontent.com/assets/515947/9885598/d6ffc9fa-5b9a-11e5-95a2-25210f6d9058.png)

Shortening the english text would work, but that doesn't solve the case for other languages.

**Comment by alexshepard** [comment]
> True about projects but those are not the majority or the main target audience

Can you explain that a little bit? 

Totally anecdotally, our "hardcore" users (ken-ichi, charlie, etc) seem to use projects a lot.

Also keep in mind that projects are a hook that allow partners to pull in new users - "download inaturalist, sign up, and join my _xyz_ project".

**Comment by naturalistcharlie** [comment]
I used to add to projects a lot. Now I usually let the projects add my
observations. I never ever assign observations to the project using the app
and doubt I would as it's just another thing to click. If I want stuff in a
project that doesn't add it I will bulk add it from the website. So as far
as my own personal preference goes I don't care about seeing projects on
the app at all.
Of course other hardcore users may be different.
I actually think casual/new users may use the project app feature more.

On Tuesday, September 15, 2015, Alex Shepard <notifications@github.com>
wrote:

> True about projects but those are not the majority or the main target
> audience
>
> Can you explain that a little bit?
>
> Totally anecdotally, our "hardcore" users (ken-ichi, charlie, etc) seem to
> use projects a lot.
>
> Also keep in mind that projects are a hook that allow partners to pull in
> new users - "download inaturalist, sign up, and join my *xyz* project".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/210#issuecomment-140490822>
> .
>


-- 
Sent from Gmail Mobile

**Comment by alexshepard** [comment]
Good to know, thanks @naturalistcharlie!

**Comment by carrieseltzer** [comment]
I think Charlie might be right about new users using projects more, but I've realized it can be very useful if you add to a project that has lots of extra fields because it automatically adds those so you can do them in the field. From the perspective of a project admin, project accessibility from the app is very important. 






—

**Comment by joellebel** [comment]
@alexshepard the text should be 17pt. as is the iOS standard. Looks like it is now, correct?

**Comment by alexshepard** [comment]
Yep, the text is standard. I just posted the flexible text sizing in order to show another option for dealing with text that doesn't fit.

**Comment by joellebel** [comment]
Here's a polishing of the ob detail screen:

* I enlarged the delete buttons to match the size of the delete buttons used on the iOS home screen. The X being used is the "close.svg"

* Can we fix the top and bottom padding of when a label goes to two lines? See below...

* I moved up the Captive/Cultivated row. There's really no need for it to be separated. 

* I also took a look at what would happen if we separated out project fields by project. Duplicate fields could get updated when one is updated. 

* The divider lines now follow the iOS format of being flush with the text as opposed to going to the edge of the screen on the left side.


![image](https://cloud.githubusercontent.com/assets/11527994/9949591/97cd9a3a-5d63-11e5-98de-80dba8320d3b.png)

**Comment by alexshepard** [comment]
When you say "what should say Choose Project" do you mean the "Add to a Project" row?

The current obs detail screen has a list of active projects rows, and a "choose projects" row. The choose projects row allows you to add/remove an observations from the project. Tapping project names on the current obs details screen does nothing other than flash a deselection.

Will the confirm screen have this same interaction model, with project rows being effectively un-tappable?
