### ISSUE TITLE
Hyperlinks in comments don't appear on iPad version

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#219]
While testing for #218, I realized that hyperlinks don't show up at all in comments on my iPad but they do on my iPhone. See attached screen shots. Both running version 2.6.2 build 234.

![ipadv2 6 2b234](https://cloud.githubusercontent.com/assets/7501183/10682014/2ee996ac-78fe-11e5-8132-d996fdb9d3f9.PNG)
![iphonev2 6 2b234](https://cloud.githubusercontent.com/assets/7501183/10682015/2ef2c3e4-78fe-11e5-8b3e-3fb6ee540438.PNG)

**Comment by alexshepard** [comment]
Hi Carrie,

My guess is that this has more to do with the length of the text, and us incorrectly calculating how tall the cell needs to be on the iPad.

However, noted! :)

We're working on a refresh of the Observation Activity stuff (as part of a general refresh of Observation Details).

Thanks,
alex

**Comment by carrieseltzer** [comment]
Ah ha, that makes sense. Just wanted to log that somewhere for the record. I know it's a very uncommon circumstance and definitely low priority! Thanks Alex.

**Comment by alexshepard** [comment]
these UI elements aren't there anymore, and the replacements show HTML linked.
