### ISSUE TITLE
'current map area' filter not always displaying on Explore tab

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#221]
to replicate:
1) search for a user from Explore->mapview
![img_3272](https://cloud.githubusercontent.com/assets/598026/10890992/4b38c81e-8150-11e5-87bd-c91aa66a7372.PNG)
2) wait until search finishes
![img_3273](https://cloud.githubusercontent.com/assets/598026/10890993/4b4e11e2-8150-11e5-8e04-b91f3a1dc446.PNG)
3) switch to grid view and note no 'current map area' filter
![img_3275](https://cloud.githubusercontent.com/assets/598026/10890994/4b55f6a0-8150-11e5-99b2-c23e55581521.PNG)
4) switch to list view and note 'current map area' filter
![img_3276](https://cloud.githubusercontent.com/assets/598026/10890996/4b57cb74-8150-11e5-92db-ddfa70f0e913.PNG)

filter should display on (3)

**Comment by alexshepard** [comment]
Released in 2.7
