### ISSUE TITLE
build 253: Erratic display issues

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/INaturalistIOS#226]
On Build 253, i took a few observations. I used the plain text tag instead of the search, not sure if that matters. Anyway after taking all the observations, not all of them showed up on the observation screen. For instance I had three observations and the upload button said three to upload but only one of them showed up as needing upload. They appear to have uploaded properly, but they did not display on my observations app page until quite some time later.
Sorry this is kind of a poorly worded description of the issue, does it make sense?

**Comment by kueda** [comment]
Hey Charlie, sorry for not getting to this *literally* for years, but this is not happening any more right? This was an old, old build.

**Comment by naturalistcharlie** [comment]
ha! Yeah assuming i understand it right... i think it was a badge issue (the little number?) and they don't even work the same way any more so yeah the issue is gone.  i do think the app no longer shows a number when uploads are needed because it does that only for notifications right? It might be something to consider looking at since i remember when i wanted rid if the auto upload thing i don't like you told me a large number of uses don't know how to upload at all, without the badge they might do it even less?  but in short yeah this appears to be fixed.

**Comment by kueda** [comment]
The badging is pretty screwed up at the moment: https://github.com/inaturalist/INaturalistIOS/issues/349. Like a lot of things, the iOS permissions structure ties our hands a little. Anyway, sounds like this is closable.
