### ISSUE TITLE
Iconic Taxa on Taxa Chooser Screen

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#227]
A user was confused that they picked "Plants" which had an icon on the categorize screen and then it had a fern photo on the confirmation screen. She thought she had IDed the ob as a fern. Proposal: 1) Use iconic taxa universally. 2) If there is a place where "Plants" needs to be a picture, it should be a picture of many plants. 

Although, we are getting rid of the Categorize screen, I think it would still be helpful to use the iconic taxa on the below screen instead of photo thumbnails...

![image](https://cloud.githubusercontent.com/assets/11527994/11026492/66482c30-865f-11e5-8ee9-bba667be5489.png)

It looks like the taxon chooser is pretty far down the road according to the iOS roadmap. Wondering if changing the photo thumbnails on the above screen to the iconic taxa is something easy to change.

**Comment by alexshepard** [comment]
Like the "I don't know" case, I think this is something that the categorize screen did a good job of solving.

Changing the photo images for just iconic taxa is easy. 

However, obviously many taxa contain other taxa. For example, one level below "Plants" is "Vascular plants" which further contains a lot of different kinds of plants. If displaying a potentially misleading photo for a non-leaf taxon is a problem, that's a system-wide iNat issue that isn't particular to the iOS app.

For example, here's what's shown when you add an identification on the web.
<img width="672" alt="screen shot 2015-11-08 at 10 02 36 pm" src="https://cloud.githubusercontent.com/assets/515947/11026907/b0a68ee8-8664-11e5-8ab8-2eb1ed7e1d47.png">

There's no such thing as a Primate that isn't also something else, so there's no way to show a photo for the Primate order without choosing something more specific.

**Comment by joellebel** [comment]
> If there is a place where "Plants" needs to be a picture, it should be a picture of many plants.

Yep. Sorry that was leftover from my observer notes. I will bring that up in the inaturalist repo

**Comment by joellebel** [comment]
Glad to hear changing the iconic taxa simple.

**Comment by naturalistcharlie** [comment]
Interesting. I can see how that would be confusing ,but it's also hard to
imagine a thumbnail that would represent all plant diversity. One option
for the highest level classification could be the nice icons iNaturalist
already uses when something doesn't have a picture. But one might want ot
create a few more of them, maybe a pine cone for gymnosperms, a little fern
one etc. Just a thought.

On Mon, Nov 9, 2015 at 1:19 AM, joellebel <notifications@github.com> wrote:

> Glad to hear changing the iconic taxa simple.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/227#issuecomment-154956334>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by kueda** [comment]
I don't think this is relevant any more since we don't have the categorize screen and the taxon chooser is now pretty different (and will become even more different).
