### ISSUE TITLE
Proposed Observation Screen

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#228]
# Table of Contents

- [Intro] (#Intro)
- [Background] (#Background)
- [New Functionality] (#New_Functionality)
- [Proposed Observation Detail Screen] (#Overview)
   - [Notes] (#Note)
   - [Captive / Cultivated Flag] (#Captive)
- [Info Tab] (#Info_Tab)
   - [Species Name States] (#Species)
   - [Data Quality States] (#Data)
   - [Location Detail Screen] (#LD)
   - [Location States] (#Location)
- [Activity Tab] (#Activity_Tab)
- [Faves Tab] (#Faves_Tab)
- [Alternatives] (#Alternatives)

 

<br />
# <a name="Intro">Intro</a>

Fellow iNaturalists - 

Please take a moment to look at the proposed new observation detail screen for iOS and give your feedback. All feedback is welcome, but here are some forms of feedback that are particularly helpful:

* Please specify how your feedback applies to your own use case. For example, if you do not like a button in a particular place, please let us know why and how that placement inhibits which task you are trying to perform. 
* If you find something confusing tell us what it is and why
* Please specify how often you use the app
* If you like something, don't forget to let us know that too ;)

Please disregard the fact that I used real usernames and some are mismatched with their profile photos. Often times I will repeat content which wouldn't happen in real life just for the sake of mocking things up quicker.

I did not mock up every single screen associated with the Observation Detail screen, but did include most. Please let me know if you have any questions.

[Back To Top](#)
<br /><br />

# <a name="Background">Background</a>

Here's a screenshot of the current Observation (edit) Screen that is being redesigned:

![image](https://cloud.githubusercontent.com/assets/11527994/11028383/04d586c8-8673-11e5-90d1-f309a2c94398.png)

### Here's a list of issues with this screen: 

* Currently there is no way to view your own observation from the Me tab without being on an observation EDIT screen. This can be confusing to folks because quite often they would simply like to view their observations without editing them. In fact, after an observation is made the observations IDs and comments become the most important aspect. There is also the risk of accidentally editing your observation. Lastly, if you do not edit your observation, it is unclear whether or not "Save" must be tapped before exiting. 

* The order of the content is a bit disorganized. For example, all location related material could be together. 

* Many new users miss the Need ID Help switch and often do not understand that the purpose of the app is get help identifying something that is unknown to you. 

* The icons and typography need a clean up. There are also unnecessary titles which take up room and make for more scrolling. 

* Could use more iconography which can help users find what they are looking for faster. 

* It does not include faving

* The pictures in the photo gallery are very small and the black background looks inconsistent with the rest of the styling of the screen

* Comments and IDs which are equally as important as the observation info need to come to the forefront. The current icon for them can be easily overlooked.

[Back To Top](#)
<br /><br />

# <a name="New_Functionality">New Functionality</a>

The following redesign will also involve some new functionality:

* View who faved your observation
* Fave or un-fave your own observation
* Delete or edit your own comments/IDs on your own observation
* Flag or delete other people's comments/IDs on your own observation

[Back To Top](#)
<br /><br />

# <a name="Overview">Proposed Observation Detail Screen</a>

The below design allows the user to view their own observation as others would see it. Tapping the "Edit" button in the upper right will bring up a new screen where one can edit notes, date, location, etc. Like the current app, only you can edit your own observation. 

See the below mock up of the proposed screen. The right screenshot is the same as the left, but includes notation numbers. See the corresponding notes below the screenshots.

 **You are looking at anudibranchmom's ob as anudibranchmom** (I chose a "anudibranchmom" only because she has a longer username and I wanted to see how that would look)

![image](https://cloud.githubusercontent.com/assets/11527994/10923295/18a77838-8235-11e5-950f-30623deb9293.png)

### <a name="Note">Notes:</a>

You'll notice there are three tabs (denoted with icons) below the community ID: 1) Info 2) Activity 3) Faves

The info tab contains all basic information about the observation. The activity tab contains IDs and comments and the faves tab displays who has faved your observation and allows you to fave an observation.

1. **Observer's username:** Char. limit: 25
1. **Ob Date:** Months are abbreviated using their 3-letter abbreviations. Year is only present it is a year different from the present. Note: There is no space between the AM/PM and time.
1. **Share:** Share link that initiates an action sheet with the following options in the following order from top down: 1) Share  2) View on iNaturalist.org
1. **Gallery Viewer:** Photos can be scrolled through by swiping left and right. Tapping a photo opens the photo viewer UI we currently have. I will revisit this down the road, but it's ok for now. If there are over 15 dots they will clipped and which in my opinion is fine. It's an edge case and I don't think it's worth doing a custom ui for. <br /><br />  If a photo is smaller than 320w px x 200h px it is simply centered in the view box. No scaling is performed. Large enough photos must fill the view box and should be scaled as such. For example, vertical photos are scaled down to fit the width of 320pts and are vertically middle-aligned with the view box. Anything on the top and bottom extending over the view box is clipped. Vice versa for horizontal photos. <br /> <br /> No matter what the view box should always retain it's dimensions of 320x200 on iPhone 5. I will come out with other specs for the iPhone 6 and tablet dimensions. Let's first see how this looks on all devices. <br /> <br /> Some photos will be cropped in odd ways, but bear in mind these are just previews. If folks want to see the full photo they can click on it to open it the current photo viewer ui.<br /><br />

1. **Community ID:** Tapping on this opens the taxon screen which slides in from the left

1. **Tabs:** Screen always defaults to displaying the info tab except when their is new activity in the Activity tab or new faves in the Fave tab. If there is new activity/faves in both the Activity and Faves tab, default to displaying the Activity tab since the information there is more important than the Faves tab.<BR /> <BR /> Notification numbers that are displayed next to the tab icons cap out at 99+. For example, if someone has 100 faves, "99+" will be displayed.

1. **Location Map:** Tapping anywhere on the location map (including the place label) opens the "Location" screen which slides in from the right. 

1. **Projects:** Projects button only shows up when there are projects associated with the ob.<br /><br /> Tapping button opens Projects screen which slides in from the right.
1. **More Info section:** This is where questions disassociated with projects go. The "More Info" only appears when there are More Info questions. 
1. **Species Name:** Tapping on that opens the taxon screen which slide in from the right like it currently does. See below for different states. 
1. **Research Grade:** Research grade or Needs ID 
<br />

<br />

### <a name="Captive">Captive / Cultivated State</a>

This is what occurs when an observation is marked as Captive / Cultivated

![image](https://cloud.githubusercontent.com/assets/11527994/10927217/b9c75ee6-8252-11e5-80cf-919256b3def5.png)

* Info icon opens a message with the text found here: http://www.inaturalist.org/pages/help#captive "What does captive / cultivated mean?" is the title for the dialogue box. It has one button: OK

[Back To Top](#)
<br /><br />

# <a name="Info_Tab">Info Tab</a>

#### Taxon

![image](https://cloud.githubusercontent.com/assets/11527994/10925476/53f22920-8243-11e5-961e-cf0c181f70a0.png)

#### Something...

Yet to come...

<br />
##  <a name="Data">Data Quality States</a>
<br />
#### Research Grade
![image](https://cloud.githubusercontent.com/assets/11527994/10922830/56a76fd8-8232-11e5-969f-fc2158722b25.png)
<br />
#### Needs ID
![image](https://cloud.githubusercontent.com/assets/11527994/10922817/3cc3df3e-8232-11e5-8269-5ae301693113.png)

<br /><br />

## <a name="LD">Location Detail Screen</a>

* Location screen character limits for the Lat and Lon values are 7. Accuracy value has a character limit of 3.

![image](https://cloud.githubusercontent.com/assets/11527994/10923097/e31c1c2e-8233-11e5-9956-751f138f74e5.png)

## <a name="Location">Location States</a>
<br />
#### Unable to Acquire Location

![image](https://cloud.githubusercontent.com/assets/11527994/10922898/bd8bc302-8232-11e5-911f-aa86e7dbc72a.png)

<br />
#### Open Location

![image](https://cloud.githubusercontent.com/assets/11527994/10922922/e774441e-8232-11e5-86a7-efb98bf5f2fd.png)

<br />
#### Private Location

![image](https://cloud.githubusercontent.com/assets/11527994/10922943/0215ab0a-8233-11e5-8563-c8e90899f835.png)

<br />
#### Obscured Location

![image](https://cloud.githubusercontent.com/assets/11527994/10922935/f7befc7e-8232-11e5-9949-f76c4da4788c.png)

<br />
[Back To Top](#)
<br /><br />
# <a name="Activity_Tab">Activity Tab

![image](https://cloud.githubusercontent.com/assets/11527994/10925810/4987003e-8246-11e5-8f78-f5bf896a8400.png)

1. **Username:** This eventually will link to the user's profile screen
1. **Date/Time:** Anything under 30 days gets the truncated version in minutes, days and weeks. (For example, 2m, 3d, 3w.) Anything over 30 days and of the present year gets the abbreviated month and day (ie. MAR 29). Anything not of this year needs to have the year included (ie. MAR 23, 2014)
1. **More Menu:** Tapping the more menu icon brings up the more menu in the form of an action sheet. (Here's an example of an [action sheet] (http://i.stack.imgur.com/TD6w9.png))  A user looking at their own ob has the following options for their own comments and IDs: Edit, Remove, Flag. They can remove of flag other people's comments and IDs. 
1. **ID Taxon:** Tap to open taxon page which slides in from the right.
1. **Agree Button:** Tapping this agrees with the ID

<br />
[Back To Top](#)
<br /><br />
# <a name="Faves_Tab">Faves Tab

![image](https://cloud.githubusercontent.com/assets/11527994/10926353/488250e4-824b-11e5-845b-fdaec3b820d8.png)

1. Number reflects the amount of faves

<br /><br />

#### Unfaved

![image](https://cloud.githubusercontent.com/assets/11527994/10926331/15f81e42-824b-11e5-99bb-01cd39a5bf04.png)

#### Faved

![image](https://cloud.githubusercontent.com/assets/11527994/10926325/0e06ab9a-824b-11e5-876d-a0b7270300c0.png)

<br />
[Back To Top](#)
<br /><br />
# <a name="Alternatives">Alternatives We Looked At</a>

### Alternative 1

As you can see this is a more condensed version of the above Observation screen. 

* Tapping the "Comments / IDs" opens the comments/IDs screen.
* Faving icon is located in the upper right of the photo. You cannot see who faved the observation. You only have the ability to fave or unfave. 
* Share button is at the very bottom

![image](https://cloud.githubusercontent.com/assets/11527994/11027730/ec2e088a-866c-11e5-8dbe-7d035a2770ec.png)

### Alternative 2

Same as above alternative, but has a map screenshot for the location. Tapping this would open the location detail screen as featured [above] (#LD)

![image](https://cloud.githubusercontent.com/assets/11527994/11027820/c74e8b74-866d-11e5-864a-92aae4fd01a5.png)

<br /><br />
If you've made it this far we want to sincerely thank you for your time and look forward to hearing from you!

<br /><br />

[Back To Top](#)

**Comment by naturalistcharlie** [comment]
Thanks Joellebel! 
In case you don't know I am a super obsessive power user :) And I apparently use the iOs app more than anyone else, even Ken-Ichi. So the things I would prefer or dislike in the app are very different than the casual user but I can present at least my use case for what it is worth. 

In general I like these proposed changes, but it also depends on how it fits with the rest of the app. For those of us with a large number of obs, the screen that shows all our obs under 'me' is one of the most important features. I wouldn't be in favor of getting rid of that (not that you proposed to).

Char limit 25: We have an account at fish and wildlife, Vermont_Natural_Heritage_Inventory . Perhaps a name that huge was a poor choice. Truncating it at 25 would be fine though.

Gallery viewer: Seems fine. A cropping feature might be useful to have , though I think more so on the website than anything.

Activity tab: what would be really awesome is if there were a tab for all notifications (like facebook) - or at least all notifications on my projects. As someone with 15000 observations or whatever, the current screen doesn't work that well because I an only see the top few. A tab that only showed notifications and perhaps sorted agrees from disagrees from comments would be awesome. But maybe outside what you are looking at here.

Accuracy: Limit of three characters seems like it might be problematic because many observations have 1000 or 10000 meter uncertainty. Will you just switch to KM? Could work but might also be confusing.

I like the different icons for open, obscured, and private.

Activity Tab: I like this.

Faves Tab: I like and use the feature on the website, but I don't see any compelling reason why it needs its own tab, myself. It doesn't bother me that it might exist, but without more interface relating to using the app to review other people's observations it seems unnecessary. I never need to see who faved my observation so urgently that i need to see it on the app, and if we had a general notifications center it could include that. I also don't think faves get used all that much though putting in the app might change that.

Maps: Would you include a map that would also show other places said species has been observed (like the website?)  That would be awesome, i love love love those maps. and it would be really neat if you observed a white oak in the field to see where others had observed white oaks nearby.  I have been perhaps the most vocal opponent to auto update but features like that might soften my dislike of it. How neat would that be?

Thanks and hope this helps! Apologies to all that i have such strong and weird opinions about the app. My hope is to maintain functionality to do things like http://www.inaturalist.org/journal/charlie/4934 . perhaps that is not the main desired purpose of the app but i love love love being able to do that.

**Comment by joellebel** [comment]
Just a note that I added a section regarding new functionality right after the Background section so the distinction between new functionality and new UX design is more clear. 

@naturalistcharlie Thanks for the response! I will get back to your questions soon.

**Comment by joellebel** [comment]
Hi Charlie. Thanks for the feedback! Please see my responses below. 

> In general I like these proposed changes, but it also depends on how it fits with the rest of the app. For those of us with a large number of obs, the screen that shows all our obs under 'me' is one of the most important features. I wouldn't be in favor of getting rid of that (not that you proposed to).

Yes, we all really like that screen too. I don't think it's going anywhere anytime soon. ;)

> Char limit 25: We have an account at fish and wildlife, Vermont_Natural_Heritage_Inventory . Perhaps a name that huge was a poor choice. Truncating it at 25 would be fine though.

The average character length of iNat usernames is 10.569 so we thought a limit of 25 would be accommodating for most. "Vermont_Natural_Heritage_Inventory" will show up as "Vermont_Natural_Heritage_..." so folks will be able to get the gist of the of username. Bear in mind usernames are almost always accompanied by a profile picture (throughout the app), so people can also use that to recognize your username. For organizations or projects, I recommend having a profile pic that is very recognizable at small sizes.  

> Gallery viewer: Seems fine. A cropping feature might be useful to have , though I think more so on the website than anything.

Sounds like a neat feature. Since folks can do this within the iOS Photos app, we probably wouldn't take on something like it for awhile.

> Activity tab: what would be really awesome is if there were a tab for all notifications (like facebook) - or at least all notifications on my projects. As someone with 15000 observations or whatever, the current screen doesn't work that well because I an only see the top few. A tab that only showed notifications and perhaps sorted agrees from disagrees from comments would be awesome. But maybe outside what you are looking at here.

Yes, I am looking forward to this as well! Stay tuned.

> Accuracy: Limit of three characters seems like it might be problematic because many observations have 1000 or 10000 meter uncertainty. Will you just switch to KM? Could work but might also be confusing.

What's more important to you: The long/lat or the accuracy? (If you had to pick) @kueda @loarie Any thoughts?



> Faves Tab: I like and use the feature on the website, but I don't see any compelling reason why it needs its own tab, myself. It doesn't bother me that it might exist, but without more interface relating to using the app to review other people's observations it seems unnecessary. I never need to see who faved my observation so urgently that i need to see it on the app, and if we had a general notifications center it could include that. I also don't think faves get used all that much though putting in the app might change that.

Thanks for your input. This is something that will evolve over time as we gain a bigger variety in users. 
I personally would like to see us triple our user base before coming to any conclusions about it. 

> Maps: Would you include a map that would also show other places said species has been observed (like the website?) That would be awesome, i love love love those maps. and it would be really neat if you observed a white oak in the field to see where others had observed white oaks nearby. I have been perhaps the most vocal opponent to auto update but features like that might soften my dislike of it. How neat would that be?

Yes, at the moment it's a lower priority since you can search for a taxa in the Explore section. Yes, it's more cumbersome, but the functionality is there. Perhaps, in the mean time we can put a link on the location detail screen to that query in the Explore tab. Tapping on it will take you to the Explore tab showing the results. I will consult with my team.

> Thanks and hope this helps! Apologies to all that i have such strong and weird opinions about the app. My hope is to maintain functionality to do things like http://www.inaturalist.org/journal/charlie/4934 . perhaps that is not the main desired purpose of the app but i love love love being able to do that.

Many thanks for your help!

**Comment by naturalistcharlie** [comment]
Thanks! One other quick thing, to me seeing accuracy is way more important
than lat lon because the map already indicates the location.  Lots of
things get added with very low accuracy and it's important to know that
when looking at a location. That being said if size is an issue I could see
having a "<999m" grab bag for all the less precise ones because once it's
that high it doesn't matter much beyond that

Thanks again,

C

On Wed, Nov 11, 2015 at 4:01 PM, joellebel <notifications@github.com> wrote:

> Hi Charlie. Thanks for the feedback! Please see my responses below.
>
> In general I like these proposed changes, but it also depends on how it
> fits with the rest of the app. For those of us with a large number of obs,
> the screen that shows all our obs under 'me' is one of the most important
> features. I wouldn't be in favor of getting rid of that (not that you
> proposed to).
>
> Yes, we all really like that screen too. I don't think it's going anywhere
> anytime soon. ;)
>
> Char limit 25: We have an account at fish and wildlife,
> Vermont_Natural_Heritage_Inventory . Perhaps a name that huge was a poor
> choice. Truncating it at 25 would be fine though.
>
> The average character length of iNat usernames is 10.569 so we thought a
> limit of 25 would be accommodating for most.
> "Vermont_Natural_Heritage_Inventory" will show up as
> "Vermont_Natural_Heritage_..." so folks will be able to get the gist of the
> of username. Bear in mind usernames are almost always accompanied by a
> profile picture (throughout the app), so people can also use that to
> recognize your username. For organizations or projects, I recommend having
> a profile pic that is very recognizable at small sizes.
>
> Gallery viewer: Seems fine. A cropping feature might be useful to have ,
> though I think more so on the website than anything.
>
> Sounds like a neat feature. Since folks can do this within the iOS Photos
> app, we probably wouldn't take on something like it for awhile.
>
> Activity tab: what would be really awesome is if there were a tab for all
> notifications (like facebook) - or at least all notifications on my
> projects. As someone with 15000 observations or whatever, the current
> screen doesn't work that well because I an only see the top few. A tab that
> only showed notifications and perhaps sorted agrees from disagrees from
> comments would be awesome. But maybe outside what you are looking at here.
>
> Yes, I am looking forward to this as well! Stay tuned.
>
> Accuracy: Limit of three characters seems like it might be problematic
> because many observations have 1000 or 10000 meter uncertainty. Will you
> just switch to KM? Could work but might also be confusing.
>
> What's more important to you: The long/lat or the accuracy? (If you had to
> pick) @kueda <https://github.com/kueda> @loarie
> <https://github.com/loarie> Any thoughts?
>
> Faves Tab: I like and use the feature on the website, but I don't see any
> compelling reason why it needs its own tab, myself. It doesn't bother me
> that it might exist, but without more interface relating to using the app
> to review other people's observations it seems unnecessary. I never need to
> see who faved my observation so urgently that i need to see it on the app,
> and if we had a general notifications center it could include that. I also
> don't think faves get used all that much though putting in the app might
> change that.
>
> Thanks for your input. This is something that will evolve over time as we
> gain a bigger variety in users.
> I personally would like to see us triple our user base before coming to
> any conclusions about it.
>
> Maps: Would you include a map that would also show other places said
> species has been observed (like the website?) That would be awesome, i love
> love love those maps. and it would be really neat if you observed a white
> oak in the field to see where others had observed white oaks nearby. I have
> been perhaps the most vocal opponent to auto update but features like that
> might soften my dislike of it. How neat would that be?
>
> Yes, at the moment it's a lower priority since you can search for a taxa
> in the Explore section. Yes, it's more cumbersome, but the functionality is
> there. Perhaps, in the mean time we can put a link on the location detail
> screen to that query in the Explore tab. Tapping on it will take you to the
> Explore tab showing the results. I will consult with my team.
>
> Thanks and hope this helps! Apologies to all that i have such strong and
> weird opinions about the app. My hope is to maintain functionality to do
> things like http://www.inaturalist.org/journal/charlie/4934 . perhaps
> that is not the main desired purpose of the app but i love love love being
> able to do that.
>
> Many thanks for your help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/228#issuecomment-155908567>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by alexshepard** [comment]
@joellebel what should the photo page control show if you've only got one photo?

**Comment by alexshepard** [comment]
@joellebel with the obvious exception of the accessory indicator on the right side (clear button vs chevron) can we please share the taxa rows between the confirm screen and the obs detail screen?

![screen shot 2015-11-18 at 12 49 46 pm](https://cloud.githubusercontent.com/assets/515947/11254001/601bb3a4-8df3-11e5-9326-60eff4d6147e.png)
![screen shot 2015-11-18 at 12 50 30 pm](https://cloud.githubusercontent.com/assets/515947/11254002/6035cc26-8df3-11e5-8544-fc490d0a58cb.png)

**Comment by alexshepard** [comment]
@joellebel now that I've got a bunch of the core functionality working, it's occurring to me: what's the mechanism for adding your own comment or identification?

**Comment by carrieseltzer** [comment]
Hi Joelle,

These are exciting design changes! I love all of the thought and care that has gone into this. Most of my feedback is clarification questions.

Background on me: I almost solely use the app now for adding recent observations. I use the site for adding photos from my backlog and for interacting with other people's observations. I have joined a LOT of projects for a variety of reasons but don't add to most of them on the app. I use the app several times a week but not quite every day. I tend to take a bunch of photos and then upload them later rather than use the app in the field. I am professionally invested in the app being easy to use for both the project I manage as well as the upcoming NPS centennial bioblitzes.

Overarching questions:
-How will the "edit" view look different? I think if I were looking at my own observation, I'd assume that I could edit it from tapping on a particular field in this view. Sounds like that will already be the case for location, but would be nice for Notes too.

Data Quality States:
-Casual is missing from the list of states (only needs id and research grade are shown).

Location Detail Screen:
-Will the default view still be hybrid map (rather than standard as shown here)?
-Will there be a default accuracy if you don't edit it when pulling from an existing photo, or will it remain "???" as it is now? (@alexshepard this might be a question more for you).
-Can #160 be implemented with these changes to make editing locations/precision easier? If I don't know an area well I don't even try to zoom in on the map because I know I'll lose my original point, which is usually quite accurate in my experience so far.
-I would love for there to be some kind of "done" button to tap when I'm done with a location (this exists when editing an observation but not when adding a new observation as of build 258). 

Location States:
-How will someone know they can edit the location state in the proposed layout? Seems like you'd have to know to tap on that bar. What if you at least used an eye without the slash across it rather than no symbol at all?

Activity Tab:
-I hope that you can still only agree once with the same id--the mocks currently make it look like you could agree twice with the same id. I'm guessing this wasn't intentional. :-)
-How do you add a new (unique) id or comment?

Misc note about projects (not covered here directly but related):
-Similar to my request for a done button on the location screen, I'd also really like one on the projects screen when I'm first adding an observation. It feels awkward to me to have to use the "back" arrow in the upper left for that purpose.

Finally one big question that's tangentially related to this: What's the likely timeline on unifying the appearance and functionality of Android and iOS apps? I know the Android work isn't in-house but it would be such a huge help for training people how to use the app to have uniform design. 

Thanks for your hard work on this!

**Comment by naturalistcharlie** [comment]
I think for me I would only use the app extensively to look at other
people's obs or do ID help if there were a bunch more functionality added
to that. Also... I'd pay more attention to notifications on there if I
could see all of them. Right now I only see the top few (as someone with a
million observations) so it isn't really worth looking at except the rare
case i upload something in the field and want to see if it got an ID right
away.

On Wed, Nov 18, 2015 at 10:54 PM, carrieseltzer <notifications@github.com>
wrote:

> Hi Joelle,
>
> These are exciting design changes! I love all of the thought and care that
> has gone into this. Most of my feedback is clarification questions.
>
> Background on me: I almost solely use the app now for adding recent
> observations. I use the site for adding photos from my backlog and for
> interacting with other people's observations. I have joined a LOT of
> projects for a variety of reasons but don't add to most of them on the app.
> I use the app several times a week but not quite every day. I tend to take
> a bunch of photos and then upload them later rather than use the app in the
> field. I am professionally invested in the app being easy to use for both
> the project I manage as well as the upcoming NPS centennial bioblitzes.
>
> Overarching questions:
> -How will the "edit" view look different? I think if I were looking at my
> own observation, I'd assume that I could edit it from tapping on a
> particular field in this view. Sounds like that will already be the case
> for location, but would be nice for Notes too.
>
> Data Quality States:
> -Casual is missing from the list of states (only needs id and research
> grade are shown).
>
> Location Detail Screen:
> -Will the default view still be hybrid map (rather than standard as shown
> here)?
> -Will there be a default accuracy if you don't edit it when pulling from
> an existing photo, or will it remain "???" as it is now? (@alexshepard
> <https://github.com/alexshepard> this might be a question more for you).
> -Can #160 <https://github.com/inaturalist/INaturalistIOS/issues/160> be
> implemented with these changes to make editing locations/precision easier?
> If I don't know an area well I don't even try to zoom in on the map because
> I know I'll lose my original point, which is usually quite accurate in my
> experience so far.
> -I would love for there to be some kind of "done" button to tap when I'm
> done with a location (this exists when editing an observation but not when
> adding a new observation as of build 258).
>
> Location States:
> -How will someone know they can edit the location state in the proposed
> layout? Seems like you'd have to know to tap on that bar. What if you at
> least used an eye without the slash across it rather than no symbol at all?
>
> Activity Tab:
> -I hope that you can still only agree once with the same id--the mocks
> currently make it look like you could agree twice with the same id. I'm
> guessing this wasn't intentional. :-)
> -How do you add a new (unique) id or comment?
>
> Misc note about projects (not covered here directly but related):
> -Similar to my request for a done button on the location screen, I'd also
> really like one on the projects screen when I'm first adding an
> observation. It feels awkward to me to have to use the "back" arrow in the
> upper left for that purpose.
>
> Finally one big question that's tangentially related to this: What's the
> likely timeline on unifying the appearance and functionality of Android and
> iOS apps? I know the Android work isn't in-house but it would be such a
> huge help for training people how to use the app to have uniform design.
>
> Thanks for your hard work on this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/228#issuecomment-157943718>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by joellebel** [comment]
Hi Carrie. Thanks so much for the input. See my answers below...

> Overarching questions:
-How will the "edit" view look different? I think if I were looking at my own observation, I'd assume that I could edit it from tapping on a particular field in this view. Sounds like that will already be the case for location, but would be nice for Notes too.

Edit is a separate functionality from this so I left it out. However, the edit screen will look very much like the new ob confirmation screen which will be released soon.

> Data Quality States:
-Casual is missing from the list of states (only needs id and research grade are shown).

We're still working on this. 

> Location Detail Screen:
 -Will the default view still be hybrid map (rather than standard as shown here)?

Yes.

> -Will there be a default accuracy if you don't edit it when pulling from an existing photo, or will it remain "???" as it is now? (@alexshepard this might be a question more for you).

Yes, this is a question for @alexshepard 

> -Can #160 be implemented with these changes to make editing locations/precision easier? If I don't know an area well I don't even try to zoom in on the map because I know I'll lose my original point, which is usually quite accurate in my experience so far.

This is something for down the road.


> Location States:
-How will someone know they can edit the location state in the proposed layout? Seems like you'd have to know to tap on that bar. What if you at least used an eye without the slash across it rather than no symbol at all?

This can be edited in the Edit view (which is not in the above proposal). 

> Activity Tab:
-I hope that you can still only agree once with the same id--the mocks currently make it look like you could agree twice with the same id. I'm guessing this wasn't intentional. :-)

Yes. Was not intentional.

> -How do you add a new (unique) id or comment?

Buttons will be there. Just not in the mock up. 



> Misc note about projects (not covered here directly but related):
-Similar to my request for a done button on the location screen, I'd also really like one on the projects screen when I'm first adding an observation. It feels awkward to me to have to use the "back" arrow in the upper left for that purpose.

Will think this over.

> Finally one big question that's tangentially related to this: What's the likely timeline on unifying the appearance and functionality of Android and iOS apps? I know the Android work isn't in-house but it would be such a huge help for training people how to use the app to have uniform design. 

Hard to give a timeline. Bear in mind since iOS and Android are different platforms with their own UX patterns, the two apps may never look exactly the same. For example, a bottom navbar is not very customary on Android. 

Thanks again!

**Comment by carrieseltzer** [comment]
Thanks for taking the time to respond to each of these, Joelle! Keep up the
great work!

On Wed, Dec 2, 2015 at 4:33 AM, joellebel <notifications@github.com> wrote:

> Hi Carrie. Thanks so much for the input. See my answers below...
>
> Overarching questions:
> -How will the "edit" view look different? I think if I were looking at my
> own observation, I'd assume that I could edit it from tapping on a
> particular field in this view. Sounds like that will already be the case
> for location, but would be nice for Notes too.
>
> Edit is a separate functionality from this so I left it out. However, the
> edit screen will look very much like the new ob confirmation screen which
> will be released soon.
>
> Data Quality States:
> -Casual is missing from the list of states (only needs id and research
> grade are shown).
>
> We're still working on this.
>
> Location Detail Screen:
> -Will the default view still be hybrid map (rather than standard as shown
> here)?
>
> Yes.
>
> -Will there be a default accuracy if you don't edit it when pulling from
> an existing photo, or will it remain "???" as it is now? (@alexshepard
> <https://github.com/alexshepard> this might be a question more for you).
>
> Yes, this is a question for @alexshepard <https://github.com/alexshepard>
>
> -Can #160 <https://github.com/inaturalist/INaturalistIOS/issues/160> be
> implemented with these changes to make editing locations/precision easier?
> If I don't know an area well I don't even try to zoom in on the map because
> I know I'll lose my original point, which is usually quite accurate in my
> experience so far.
>
> This is something for down the road.
>
> Location States:
> -How will someone know they can edit the location state in the proposed
> layout? Seems like you'd have to know to tap on that bar. What if you at
> least used an eye without the slash across it rather than no symbol at all?
>
> This can be edited in the Edit view (which is not in the above proposal).
>
> Activity Tab:
> -I hope that you can still only agree once with the same id--the mocks
> currently make it look like you could agree twice with the same id. I'm
> guessing this wasn't intentional. :-)
>
> Yes. Was not intentional.
>
> -How do you add a new (unique) id or comment?
>
> Buttons will be there. Just not in the mock up.
>
> Misc note about projects (not covered here directly but related):
> -Similar to my request for a done button on the location screen, I'd also
> really like one on the projects screen when I'm first adding an
> observation. It feels awkward to me to have to use the "back" arrow in the
> upper left for that purpose.
>
> Will think this over.
>
> Finally one big question that's tangentially related to this: What's the
> likely timeline on unifying the appearance and functionality of Android and
> iOS apps? I know the Android work isn't in-house but it would be such a
> huge help for training people how to use the app to have uniform design.
>
> Hard to give a timeline. Bear in mind since iOS and Android are different
> platforms with their own UX patterns, the two apps may never look exactly
> the same. For example, a bottom navbar is not very customary on Android.
>
> Thanks again!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/228#issuecomment-161235533>
> .
>



-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org

**Comment by joellebel** [comment]
@carrieseltzer Thanks!

**Comment by alexshepard** [comment]
> Will there be a default accuracy if you don't edit it when pulling from an existing photo, or will it remain "???" as it is now? (@alexshepard this might be a question more for you).

iOS doesn't record positional accuracy when it saves photos. So anything else that we put in there would be totally made up.

**Comment by alexshepard** [comment]
> Info icon opens a message with the text found here: http://www.inaturalist.org/pages/help#captive "What does captive / cultivated mean?" is the title for the dialogue box. It has one button: OK

I'm going to edit this text down a fair amount, because here is what it looks like now on a 5s.

![simulator screen shot dec 9 2015 2 58 06 pm](https://cloud.githubusercontent.com/assets/515947/11701617/6cac12ec-9e85-11e5-9515-7fd00d09de5c.png)

The text continues for quite a while, so you have to keep scrolling. Unfortunately you can't set the text alignment in a standard alert view on iOS.

**Comment by joellebel** [comment]
Thanks for sharing. Ya it would be great if we could trim this down to 8-10 lines or less. If we have to go more than that, it should definitely be left-aligned. Also, there could be less examples and they don't need to be on separate line unless we want to get into bullets which I know these messages are pretty tough to customize so having them simply separated by commas would do.

**Comment by naturalistcharlie** [comment]
I don't know if this would work or not but you could also consider a link
to a place on the main website that explains that.

On Wednesday, December 9, 2015, joellebel <notifications@github.com> wrote:

> Thanks for sharing. Ya it would be great if we could trim this down to
> 8-10 lines or less. If we have to go more than that, it should definitely
> be left-aligned. Also, there could be less examples and they don't need to
> be on separate line unless we want to get into bullets which I know these
> messages are pretty tough to customize so having them simply separated by
> commas would do.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/228#issuecomment-163446431>
> .
>


-- 
Sent from Gmail Mobile

**Comment by joellebel** [comment]
Thanks for the idea, Charlie. When possible I recommend trying to keep folks in the app. It's a more seamless user experience and results in less confusion.

**Comment by joellebel** [comment]
Closing out this issue because it was originally meant for feedback and we have all the feedback we need.Thanks to everyone who contributed!
