### ISSUE TITLE
Updates not loading on 261

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#230]
To reproduce:
1. Sign into your account and tap on an update icon (the chat bubbles with numbers in them)
2. See the loader in the status bar at the top spin briefly then stop. No updates load:
![img_3363](https://cloud.githubusercontent.com/assets/598026/11135821/b9a9c144-895d-11e5-93dd-5b7ec6c4a255.PNG)
3. Refreshing doesn't seem to help
![img_3365](https://cloud.githubusercontent.com/assets/598026/11135822/b9ab5d60-895d-11e5-83c3-c31eb98e1d07.PNG)
4. Clicking back and then returning does cause the updates to appear
![img_3364](https://cloud.githubusercontent.com/assets/598026/11135823/b9abb378-895d-11e5-874e-5e1174d2eea1.PNG)

**Comment by alexshepard** [comment]
Closing as we don't have the activity screen anymore.
