### ISSUE TITLE
My observations not displaying on 261

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#231]
To reproduce:
1. log out of the app and note the binoculars guy on the me tab
2. Log in and note that binoculars guy is still there (scrolling down reveals things are loaded just not displayed)
![img_3366 1](https://cloud.githubusercontent.com/assets/598026/11135880/46bcf2b8-895e-11e5-8300-890980664080.PNG)
3. Clicking elsewhere and returning to the Me tab causes them to display

**Comment by alexshepard** [comment]
Should be fixed, right @loarie?
