### ISSUE TITLE
Edit location in recent test build not working. 

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/INaturalistIOS#232]
There isn't an option to confirm so I can't edit location.

**Comment by carrieseltzer** [comment]
What version/build?

**Comment by naturalistcharlie** [comment]
261

On Tuesday, November 24, 2015, carrieseltzer <notifications@github.com>
wrote:

> What version/build?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/232#issuecomment-159483044>
> .
>


-- 
Sent from Gmail Mobile

**Comment by alexshepard** [comment]
Should be fixed in the latest
