### ISSUE TITLE
Build 273: two small issues/comments

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/INaturalistIOS#234]
so far i really like the new observation edit screen. Two things:

In the screen below you can see a case where I saw a nest and identified it as 'birds' and then Susan Elliot posted an ID of Vireos and I agreed. The problem to me is that it looks out of order. When I look at the screen shot below to me it looks like I initially had ID of vireos and changed it to birds. I think it would be easier with time stamps and/or the feature like on the main site where the older ID is crossed out.

![img_2257](https://cloud.githubusercontent.com/assets/7171475/11987223/2b8a0d8a-a9a9-11e5-9456-c4701d5cc64a.jpg)

Issue 2, just a small bug. See below. I go to edit my observation (which hadn't been uploaded yet) and it says 'nobody' at the top, for some reason. after I sync it changes to 'charlie' like it should. Not a major issue but a bit odd.

![img_2313](https://cloud.githubusercontent.com/assets/7171475/11987234/80e0af00-a9a9-11e5-819b-9284324f5365.jpg)

One other thing, I think it would be nice if when you go to the map browsing screen if you got the new observation view instead of the old, because i like it better (See! I don't always hate change!) but I am guessing you may get to that in time.

It would also be awesome to be able on the app to filter observations the way you can in ID please (not by me, not reviewed) and to be able to mark them as reviewed. Probably a longer term request... but i find it's really fast to add IDs on the app and so it would be fun to do more of it!

**Comment by joellebel** [comment]
@naturalistcharlie Thanks for sharing. If your first ID was "Birds" then it should remain "Birds" as your first ID in the timeline. Is this maybe a bug? Maybe I'm not seeing the whole screen?

**Comment by alexshepard** [comment]
Joelle in her design/spec had a relative date for activity, which I'll be putting in soon using [YLMoment](https://github.com/yannickl/YLMoment). Depending on how long ago the activity happened, this would be cleared up (20 mins ago vs 25 mins ago, 3 days ago vs 5 days ago). 

However, if the multiple IDs occur close enough to each other relative to how long ago the activities happened, they will have the same relative date: (3 hours ago, 4 days ago, last month). 

Without always including the absolute date and time, there is potential for this "which activity was first" confusion. More so for comments, which don't supersede each other.

I can easily add the ~~strikethrough~~ on non-active IDs if folks want it.

**Comment by alexshepard** [comment]
Another thought: in my experience, I often see "add new content" UI next to the most recent content that other people added. I think it helps the user infer the order of the existing content.

**Comment by naturalistcharlie** [comment]
Hi Joelle! Birds was my first ID and then there was Susan Elliott's more
detailed ID and I agreed with it. Part of the issue was to me it looked
like Birds was most recent. But what Alex says makes sense

On Thu, Dec 24, 2015 at 2:21 PM, Alex Shepard <notifications@github.com>
wrote:

> Another thought: in my experience, I often see "add new content" UI next
> to the most recent content that other people added. I think it helps the
> user infer the order of the existing content.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/234#issuecomment-167151241>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by alexshepard** [comment]
We swapped the order of the comments and IDs in the activity section in the release build, so hopefully this is no longer an issue.
