### ISSUE TITLE
Out of place serif font in build 277

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#235]
Notes I've added to an observation that has been uploaded appear in a serif font while everything else in the app is in a sans serif font. It looks out of place and considerably smaller than the other fonts. See screen shot. Build 277 on iOS 8.1.2. 

![photo jan 05 9 44 42 pm](https://cloud.githubusercontent.com/assets/7501183/12133802/c7898826-b3f6-11e5-9b6a-bd9a24ba99c8.png)

**Comment by alexshepard** [comment]
Will be fixed in the next build.

**Comment by alexshepard** [comment]
Thanks!

**Comment by carrieseltzer** [comment]
Great! I found it in another place too. Comments use serif font when you look at it under the chat bubble, but they appear sans serif if you click into an observation with new activity. See screen shots for comparison. Also might be nice to unify those two views. I prefer the "new activity" version of it, which unfortunately I can't get back to unless a new comment or id happens.

![photo jan 06 3 59 44 pm](https://cloud.githubusercontent.com/assets/7501183/12154705/1bf3f8cc-b48f-11e5-82c2-38a0ad3e4383.png)
![photo jan 06 4 00 08 pm](https://cloud.githubusercontent.com/assets/7501183/12154704/1bf3c10e-b48f-11e5-945e-a8849edf9f21.png)

**Comment by alexshepard** [comment]
That new activity screen is going away in this next build.

**Comment by alexshepard** [comment]
fixed in build 278, which will be out today
