### ISSUE TITLE
TestFlight Build 280 Bugs and Styling Revisions

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#237]
Please disregard all items you are currently working on. All my testing was done on iPhone 6
# Bugs on Ob Detail Screen
- [x] Taxon links not working in IDs. Expected behavior: Open taxon page. Current behavior: Nothing happens
- [ ] Community ID scientific name missing: Did we decide to get rid of the scientific name under the Community ID?
- [ ] Suggested IDs' scientific name missing: Did we decide to get rid of this? Having the scientific name allows for a bigger photo and more distinction from the profile pic and the suggested ID. Here's a screenshot of the design for reference... 
  ![image](https://cloud.githubusercontent.com/assets/11527994/12215079/e5c5fe92-b661-11e5-9fea-6ef0e072a3ca.png)
- [x] Did we decide to get rid of the geoprivacy icons? They are not showing up for me. 
- [x] Is the tab indicator 3pts?
- [x] Add Comment screen looks like this... 
- [ ] Lat/Long/Acc is currently not showing up on the Location screen. Perhaps, that's not a high priority for this release?
  - [ ] No Location Bug: I can't figure out why the map says "No Location" when the ob has a location. Here's a screenshot... Here's a link to it: http://www.inaturalist.org/observations/2363429  Is it because it only has lat/long and no location name indicated in the web app edit screen? However, it has a place name in the edit screen of the iOS app. Maybe this is a corner case. 
    ![image](https://cloud.githubusercontent.com/assets/11527994/12215046/283c69b6-b660-11e5-9d8c-6fee9d3aa2e9.png)
- [x] Location screen formatting issue: This is the screen in landscape mode...
  ![image](https://cloud.githubusercontent.com/assets/11527994/12215057/baab8e08-b660-11e5-9a8d-0c7eaf54468c.png)
- [x] Location Edit screen formatting issue: This is the Location edit screen... 
  ![image](https://cloud.githubusercontent.com/assets/11527994/12215061/d6b8692c-b660-11e5-9d36-7d22b09d4e1d.png)
- [x] Agree icon is missing.
- [x] Add comment formatting issue...
  ![image](https://cloud.githubusercontent.com/assets/11527994/12215103/e9825c28-b662-11e5-9480-64bb6b2d95cb.png)
- [ ] Add Identification issue: After choosing a taxon from the taxon chooser I come to this screen and tapping the magnifying glass deletes the taxon which is unexpected. There either needs to be a delete button in there or the magnifying glass takes you back to the taxon chooser. The mag. glass is also too far to the left. Here's a screenshot...

![image](https://cloud.githubusercontent.com/assets/11527994/12215113/3dd5d12e-b663-11e5-8b64-eccadbdbdc3e.png)
# Overlay with TCel just for reference

![image](https://cloud.githubusercontent.com/assets/11527994/12214976/3e5a67c8-b65d-11e5-945c-bafb0c66763b.png)
# Styling High Priority (This release would be nice. Please let me know what's time consuming and I can make changes.)
- [x] Please give about 10pt of space above the "Data Quality" title. It's currently unclear what it is referring to. 
- [x] Please remove the "NOTES" title as I think it's unnecessary. Please also give it as much top and bottom padding as it is as far from the left. Here's what it would look like with the correct padding... 
  ![image](https://cloud.githubusercontent.com/assets/11527994/12214964/e3f7e814-b65c-11e5-8ae3-d7caae96dca6.png)
- [x] Tab indicators: Are the tab indicators 3 pts high? They look like need to be about double the thickness. I'm concerned folks will miss them at their current thickness. Here's a screenshot of the current build (on left) next to the design....
  ![image](https://cloud.githubusercontent.com/assets/11527994/12214977/610ea130-b65d-11e5-9383-76282091fd17.png)
- [x] Tab Icons: Can we make the tab icons a little smaller and lessen the space between the tops of the icons and the bottom of the Community ID? You can see the differences in the above screenshots. It doesn't need to be exactly like the design... just a little closer.

![image](https://cloud.githubusercontent.com/assets/11527994/12214977/610ea130-b65d-11e5-9383-76282091fd17.png)
- [x] Please make the Data Quality time line thinner by 3pts.
- [x] The text of the location label on the map needs about 3 more points of top and bottom padding. Here's a screenshot for reference of the desired padding... 
  ![image](https://cloud.githubusercontent.com/assets/11527994/12215028/5296db70-b65f-11e5-996c-869d135a1c1e.png)
# Styling Low Priority (Next release is fine)
- [x] Map marker: Since the location label is not above the map marker, can we lower the map marker a bit so it's centered?
- [ ] Username and Date need to come down 1pt size. 
  - [ ] Is it possible to make the inactive photo indicators a little less transparent so it's more clear there are multiple photos? 
- [x] Location label corner radius. What is the current corner radius of this? If it's 1pt, can we make it .5pt. It's currently too round. 
- [ ] Just wondering if we can do something closer to the design for obs without photos. Here's the design... 
  ![image](https://cloud.githubusercontent.com/assets/11527994/12215086/40468cb0-b662-11e5-999d-cf359925b71b.png) Except the wording should be "No Photo"
  - [ ] Photo area border: Can we make these borders go all the way to the left? Here's what they look like now... 
    ![image](https://cloud.githubusercontent.com/assets/11527994/12215100/c0537d82-b662-11e5-8fa2-546c42667424.png)
- [ ] Share icon: Can we make this a few points bigger and the background circle should be black at 80% transparency

**Comment by alexshepard** [comment]
Ok, I'll start looking at these.

> [scientific name missing]

I asked about this back in November. I would love it if we could use a single implementation of the taxon row in these two newest screens.

https://github.com/inaturalist/INaturalistIOS/issues/228#issuecomment-157860563

> Did we decide to get rid of the geoprivacy icons?

Nope, I just haven't yet implemented them.

> Add Comment screen looks like this...

Like what?

> Add comment & add ID screens

Nothing about these has changed in ages. I can start working fresh on these, but it'll just delay the release further.

**Comment by alexshepard** [comment]
are comments here being posted to :slack:?

**Comment by alexshepard** [comment]
> the tcel overlay doesn't fit with the implementation

The navigation bar in the implementation is totally iOS standard, but the overlay shows it being off by ~20 points. The photo row height is implemented at 200 points tall for iPhone 5 and smaller, 253 points tall for iPhone 6 and larger, but your tcel overlay shows the height being different.

So I'm not sure how to interpret this.

**Comment by alexshepard** [comment]
> Share icon: Can we make this a few points bigger and the background circle should be black at 80% transparency

do you want the icon bigger within the circle? or just the circle bigger? or both?

currently it's an 18pt glyph with a 29pt circle.

**Comment by alexshepard** [comment]
> Is it possible to make the inactive photo indicators a little less transparent so it's more clear there are multiple photos?

I can set the inactive and active tint colors on the page control dots, they're currently just the defaults. What colors would you like them to be?

**Comment by alexshepard** [comment]
> Username and Date need to come down 1pt size.

in the first row (the username and date associated with the observation) or in the activity rows or both?

**Comment by joellebel** [comment]
> [scientific name missing]

I asked about this back in November. I would love it if we could use a single implementation of the taxon row in these two newest screens.


Ok, I'll start looking at these.

> [scientific name missing]

I asked about this back in November. I would love it if we could use a single implementation of the taxon row in these two newest screens.

https://github.com/inaturalist/INaturalistIOS/issues/228#issuecomment-157860563

> Did we decide to get rid of the geoprivacy icons?

Nope, I just haven't yet implemented them.

> Add Comment screen looks like this...

Like what?

> Add comment & add ID screens

Nothing about these has changed in ages. I can start working fresh on these, but it'll just delay the release further.


> the tcel overlay doesn't fit with the implementation

The navigation bar in the implementation is totally iOS standard, but the overlay shows it being off by ~20 points. The photo row height is implemented at 200 points tall for iPhone 5 and smaller, 253 points tall for iPhone 6 and larger, but your tcel overlay shows the height being off.

So I'm not sure how to interpret this.


> Share icon: Can we make this a few points bigger and the background circle should be black at 80% transparency

> >  do you want the icon bigger within the circle? or just the circle bigger? or both?

currently it's an 18pt glyph with a 29pt circle.


> Is it possible to make the inactive photo indicators a little less transparent so it's more clear there are multiple photos?

I can set the inactive and active tint colors on the page control dots, they're currently just the defaults. What colors would you like them to be?

**Comment by joellebel** [comment]
oops don't read the above post yet. I was just copying and pasting your questions in one post and somehow it posted. Will let you know when it's ready.

**Comment by joellebel** [comment]
@alexshepard ok. The above post is ready. @loarie @kueda  There are also a few questions in there for you.

**Comment by alexshepard** [comment]
> [Scientific name]

I don't have a problem with showing the scientific name, and I was a little surprised that it wasn't included in the confirm screen. But for consistency of implementation, I'd love it if every time we have a tableview row that's showing a taxon, we make it and show it the same way.

> [Geoprivacy icons]

They're in the latest release (282), but only on the obs details screen.  Haven't gotten them into the edit/confirm screen yet.

> [Add comment & add ID screens]

I fixed the add comment ID width because it's an easy layout change. It's in 282. 

Your add ID concerns seem more functional and will be more work, so I'm going to hold off making changes to those for now.

> [Tcel and tab selector icons]

In the latest build I dropped the icon point size down from 35 to 30, and also dropped the spacing between the bottom of the icon and the bottom of the view from 8 to 6 points.

> [increase share icon size by 2pts]

ok, will do.

> [page control transparency]

Unfortunately, all I know is that they're whatever the apple defaults are. When I try to inspect those colors in code, the values are empty. Maybe make an observation with a fake photo that's all white or all black, then eyedrop a screenshot? Sorry.

**Comment by joellebel** [comment]
Just a note if we decide to leave out scientific names the taxon links may eventually need some re-alignment or resizing in the Activity tab. Right now I'm not liking how the taxon thumbnail is the same size as the profile pic.

**Comment by kueda** [comment]
IMO, always include the scientific name if a common name is present. Useless to noobs, hopefully not offputting, extremely useful to experienced users. "Add ID" screen looks fine to me. "Add Comment" has a big gray bar above the keyboard on iPhone 5 but otherwise seems fine:

![img_7623](https://cloud.githubusercontent.com/assets/22691/12279613/0ed4d5c8-b93d-11e5-954d-f99546f81117.PNG)

**Comment by loarie** [comment]
I don't have a preference about sciname or not

re: comments/ids - will defer to alex. The only glaring issue for me is the iPhone6 comment bug
![img_3940](https://cloud.githubusercontent.com/assets/598026/12279631/2d97176e-b93d-11e5-9dfd-500ccb412be7.jpg)
but if its really been broken for a while I guess its not getting any worse

**Comment by loarie** [comment]
I agree with ken-ichi that 'IMO, always include the scientific name if a common name is present. ' - I thought the question was, when a common name IS present, whether to also include a sci-name to which I have no strong feelings

**Comment by alexshepard** [comment]
OK @joelle, then if I'm going to redo the taxon row for the observation detail screen to add a scientific name, can I reuse that for the confirm/edit screen?

**Comment by joellebel** [comment]
@alexshepard yes!

**Comment by joellebel** [comment]
(The only reason I originally didn't have have the sci name on the conf. screen was because I was trying to make it as wordless as possible and not push too much content down. When testing on newbs the conf. screen seemed slightly overwhelming.) 

Not a problem to include it there though.

**Comment by joelle** [comment]
Hi,
You have the wrong Joelle!
Thanks,

Joelle

On Thursday, January 14, 2016, joellebel <notifications@github.com> wrote:

> (The only reason I originally didn't have have the sci name on the conf.
> screen was because I was trying to make it as wordless as possible and not
> push too much content down. When testing on newbs the conf. screen seemed
> slightly overwhelming.)
>
> Not a problem to include it there though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/237#issuecomment-171801941>
> .
>


-- 
_________________________________
* j o e l l e  a l c a i d i n h o

http://www.joellewrites.com
@joelle_writes

**Comment by alexshepard** [comment]
Sorry @joelle!

**Comment by joelle** [comment]
No problem, best of luck with your project:)

On Thursday, January 14, 2016, Alex Shepard <notifications@github.com>
wrote:

> Sorry @joelle <https://github.com/joelle>!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/237#issuecomment-171802722>
> .
>


-- 
_________________________________
* j o e l l e  a l c a i d i n h o

http://www.joellewrites.com
@joelle_writes

**Comment by alexshepard** [comment]
testflight build 280 was a long time ago. closing this, @joellebel, if there are outstanding issues in this that apply to the current build, please open them as individual items.
