### ISSUE TITLE
More Tab Functional and Styling Spec

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#239]
# Functional Spec

The More tab will contain links the Projects and "Field Guides" sections. Here's [more info] (https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Bars.html#//apple_ref/doc/uid/TP40006556-CH12-SW52) on how the "More" tab bar functionality works.

![image](https://cloud.githubusercontent.com/assets/11527994/12336347/f5395bca-bab8-11e5-9958-613dff072926.png)

I'm also proposing to change "Guides" to "Field Guides" as it is more explicit. "Guides" could mean people.

# Styling Spec

* Projects Icon: ios-briefcase-outline.svg
* Field Guides Icon: ios-book-outline.svg

More to come... will let you know when the styling spec portion of this issue is ready.

**Comment by alexshepard** [comment]
since this is a default iOS provided screen, I dunno how much customization is possible.

also, are we going to change Guides to Field Guides everywhere?

**Comment by joellebel** [comment]
> since this is a default iOS provided screen, I dunno how much customization is possible.

Sounds good. Was actually going to ask you if you needed any further styling specs. I also might change those icons to inat green. Do you need the dimensions of the icons?

> also, are we going to change Guides to Field Guides everywhere?

Yes, I'd like to and will create an issue about it in the inat repo for us all to discuss. So I guess for now you can just leave it as "Guides"

**Comment by alexshepard** [comment]
> Sounds good. Was actually going to ask you if you needed any further styling specs. I also might change those icons to inat green. Do you need the dimensions of the icons?

The icons are set in code to be grey and green, but when they appear on this More screen (instead of on the Tab Bar where they used to be) they're changing to Blue. So I'm not sure how much we can even influence that.

**Comment by joellebel** [comment]
NP.

**Comment by joellebel** [comment]
Done
