### ISSUE TITLE
Taxon chooser should close completely when user taps "Cancel"

### ISSUE THREAD

**Issue by pleary** [inaturalist/INaturalistIOS#24]
I was adding a new observation, entered the name Fungi, hit the magnifying glass to search taxa, got my results as expected, then hit 'cancel'. I was expecting to be back on the add observation page, but instead I was given the same default list of taxa I would see if I hadn't entered a search term and hit the magnifying glass. Most confusingly for this instance is Fungi was at the top of both lists.

The other small problem is when hitting cancel and being shown the default taxa list, there is a search bar at the top of the list which cut off by the "Search species" header, making it look more like a bug.

If this is a feature, then the only action would be to fix the truncation of the search bar after hitting cancel, and maybe renaming 'cancel' to something like 'browse taxa'. Otherwise, I would expect that anytime I hit a button that says 'cancel' I should be returned to the last screen I was looking at.

**Comment by alexshepard** [comment]
This doesn't apply to the new taxa search UI and edit observation screens, so closing.
