### ISSUE TITLE
Projects Section 2.0 Functional spec

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#240]
All Functional specs are contained in the below google doc. Please leave all comments/questions in this issue. 

https://docs.google.com/document/d/1uKSVmMRBFKf9nLRRcSlVj4dG2z0yPjZMfn2GL3KpVVw/edit?usp=sharing

**Comment by joellebel** [comment]
@alexshepard Still working on this...

**Comment by carrieseltzer** [comment]
It seems problematic to automatically have people join projects if they have terms to agree to (maybe you're only talking about projects that don't have terms?). Also, does it make sense for people outside the U.S. to join the nps project? I like this concept but worried about the details. 



—

**Comment by joellebel** [comment]
@alexshepard The functional spec is ready! See above google doc.

**Comment by joellebel** [comment]
@carrieseltzer Good points. 

@alexshepard is it possible to only target users from who download the app from the US iTunes market?

**Comment by alexshepard** [comment]
A few questions:

Project posts on the web can have comments. Are we going to support them on iOS?

What happens when you tap the "Start Browsing" button on the No Projects version of the page?

Since the featured projects section will include some nearby projects, do we still need the nearby project section?

The current implementation of the project list view has a pull to search. Is that expected to be in this version as well? If so, how do you think it should function?

Some stuff that would be nice to show in the project info screen instead of just description text: project curators/managers/admins/creator, creation date, terms, associated place, field requirements.

**Comment by alexshepard** [comment]
> is it possible to only target users from who download the app from the US iTunes market?

If people have their geo enabled and have given us permission to view it, we should be able to tell whether a user is currently within the US. However, there's no way for us to know which app store they downloaded our app from. 

At what point will users be joined to these projects? During account creation? Or when they first visit the project or news page?

**Comment by alexshepard** [comment]
That last comment raises another question for me: what do we do for users who haven't logged in yet? In the current public release, we don't show the projects part of the app until they signed in.

In the not-logged-in case, what do we show for the news list view? How about the project list view(s)?

**Comment by joellebel** [comment]
For the Projects list I would think you could still see them even if you're not logged in so you can get a sense of them find them as one more reason to sign up for iNat. When attempting to join one and not logged in the user can get a prompt to sign up/log in. If the user has not accepted app location permissions when they go to the Nearby toggle, they would get the location permission prompt.

> Project posts on the web can have comments. Are we going to support them on iOS?

From a user standpoint I think it would be informative to see the comments and even more engaging to be able to comment. From an engineering standpoint how complicated is this? As for the UX of the commenting flow I would envision comments appearing below the post and there would be a comment button which would activate a flow similar to that of the Activity Tab commenting flow.  If this is something that can be implemented and we all think it's a good idea. I can design it. 

> What happens when you tap the "Start Browsing" button on the No Projects version of the page?

Was thinking it would put you in the Featured tab. 


> The current implementation of the project list view has a pull to search. Is that expected to be in this version as well? If so, how do you think it should function?

I think it's confusing to the user that the search is not limited to the active segment. Originally, I was trying to change as little as possible with this section due to the deadline. 

Question: Do we need that refresh button in the navbar? If not, we could put a search button up there since the current search functionality isn't faceted anyways. Later on we can add a more sophisticated search if needed or a scope bar. This would also make it easier on project admins when informing users how to find their projects. They could simply say "Go to the Projects section (in the More tab) and search for "Project X". 


> Since the featured projects section will include some nearby projects, do we still need the nearby project section?

I vote to keep to keep nearby projects so users can quickly see their nearby projects. For now there will be a lot of overlapping, but in the future featured projects may be expanded. 


> Some stuff that would be nice to show in the project info screen instead of just description text: project curators/managers/admins/creator, creation date, terms, associated place, field requirements.

Totally agree, but again was going for MVP for the first version and see these as enhancements that can come down the road. For now, I would love to keep it opening in a screen (as opposed to a pop up modal) and this screen will definitely evolve.


> At what point will users be joined to these projects? During account creation? Or when they first visit the project or news page?

I'm assuming they will not be able to see projects like NPS or OOTW unless they have joined it? It would be nice to be able to see these without having joined them, but I realize this may complicate things for now. I was thinking they would see these news posts after creating an account and we will be automatically joining them to NPS, OOTW, OOTD and Critter Calendar upon account creation. (It's still yet to be determined what we're doing for legacy users) 


> That last comment raises another question for me: what do we do for users who haven't logged in yet? In the current public release, we don't show the projects part of the app until they signed in.



> In the not-logged-in case, what do we show for the news list view? How about the project list view(s)?

I'll mock up the signed out state for news list because since you're signed up/logged in, you're "not a part of" any projects and therefore cannot see their news posts. 


Will get to any comments I have left out.

**Comment by joellebel** [comment]
> The current implementation of the project list view has a pull to search. Is that expected to be in this version as well? If so, how do you think it should function?

Would keep this only if the search can be filtered to the active segment. Before making any decisions though, I am curious to know the answer to my above search question.

**Comment by alexshepard** [comment]
> For the Projects list I would think you could still see them even if you're not logged in so you can get a sense of them find them as one more reason to sign up for iNat. When attempting to join one and not logged in the user can get a prompt to sign up/log in. 

OK, for the project list that makes sense to me.

> If the user has not accepted app location permissions when they go to the Nearby toggle, they would get the location permission prompt.

OK, that's the same as the current implementation. However, what if they say no, or they aren't allowed to say yes due to parental controls/etc?

> From a user standpoint I think it would be informative to see the comments and even more engaging to be able to comment. From an engineering standpoint how complicated is this? As for the UX of the commenting flow I would envision comments appearing below the post and there would be a comment button which would activate a flow similar to that of the Activity Tab commenting flow. If this is something that can be implemented and we all think it's a good idea. I can design it.

From a technical standpoint, under the hood, supporting comments won't be hard. Most of the work will come in the UI implementation, so the simpler that is, the easier it will be.

>> [the "Start Browsing" button]

> Was thinking it would put you in the Featured tab.

OK

> I think it's confusing to the user that the search is not limited to the active segment. Originally, I was trying to change as little as possible with this section due to the deadline.

I agree that the current implementation is confusing, but search is the only way to find non-nearby and non-featured projects so we need something.

> Question: Do we need that refresh button in the navbar?

If we get rid of refresh on this page, then the user won't have any way to refresh stale projects aside from quitting and restarting. Ie - you join a project on the web, then your mobile view is out of date. 

If you want I can add analytics to the projects refresh button to see how often it's used.

Navbars on iOS do allow multiple UIBarButtonItems in the left and right corners of UINavigationBars. See the apple calendar app for an example.

> I vote to keep to keep nearby projects so users can quickly see their nearby projects. For now there will be a lot of overlapping, but in the future featured projects may be expanded.

OK

>> [Showing more project information]

> Totally agree, but again was going for MVP for the first version and see these as enhancements that can come down the road. For now, I would love to keep it opening in a screen (as opposed to a pop up modal) and this screen will definitely evolve.

OK. Please be aware this is a step back from the current implementation, which shows a description, terms, and observation rules on the Project Details screen. It could be argued that we might not want to allow people to join a project without showing them the terms of that project: what they're signing up for, permissions they're granting the project admins, expectations of behavior, etc.

>> [When will users be auto-joined to projects]

> I'm assuming they will not be able to see projects like NPS or OOTW unless they have joined it? 

I don't understand the question. If you browse to the project list on the project page, you will be able to see projects that you haven't joined.

> I was thinking they would only see these news posts after creating an account at which point they are automatically joined to NPS, OOTW, OOTD and Critter Calendar. (It's still yet to be determined what we're doing for legacy users)
> I'll mock up the signed out state for news list because since you're signed up/logged in, you're "not a part of" any projects and therefore cannot see their news posts.

I'd love it if we could put some content in here to show completely new users what an active community we have going, but I guess this works for now.

**Comment by alexshepard** [comment]
> Would keep this only if the search can be filtered to the active segment. Before making any decisions though, I am curious to know the answer to my above search question.

So at that point, you could only search among joined, featured, or nearby projects? That leaves a huge number of projects undiscoverable on this projects list view.

**Comment by joellebel** [comment]
>> Question: Do we need that refresh button in the navbar?
If we get rid of refresh on this page, then the user won't have any way to refresh stale projects aside from quitting and restarting. Ie - you join a project on the web, then your mobile view is out of date.

> If you want I can add analytics to the projects refresh button to see how often it's used.

> Navbars on iOS do allow multiple UIBarButtonItems in the left and right corners of UINavigationBars. See the apple calendar app for an example.

Well I guess what I'm really asking is can we make this section auto update so there is no need for a refresh button? :)



>>> [Showing more project information]

>> Totally agree, but again was going for MVP for the first version and see these as enhancements that can come down the road. For now, I would love to keep it opening in a screen (as opposed to a pop up modal) and this screen will definitely evolve.

> OK. Please be aware this is a step back from the current implementation, which shows a description, terms, and observation rules on the Project Details screen. It could be argued that we might not want to allow people to join a project without showing them the terms of that project: what they're signing up for, permissions they're granting the project admins, expectations of behavior, etc.

Oh whoops. Looks like I've never scrolled down enough on a project page to notice that. Will come up with a simple solution for now. 



>> Would keep this only if the search can be filtered to the active segment. Before making any decisions though, I am curious to know the answer to my above search question.

> So at that point, you could only search among joined, featured, or nearby projects? That leaves a huge number of projects undiscoverable on this projects list view.

Yes, that's why I was asking if we can implement a global project search functionality with the above question...

"Question: Do we... If not, we could put a search button up there since the current search functionality isn't faceted anyways. Later on we can add a more sophisticated search if needed or a scope bar. This would also make it easier on project admins when informing users how to find their projects. They could simply say "Go to the Projects section (in the More tab) and search for "Project X"."




>> I'm assuming they will not be able to see projects like NPS or OOTW unless they have joined it?
I don't understand the question. If you browse to the project list on the project page, you will be able to see projects that you haven't joined.

> I don't understand the question. If you browse to the project list on the project page, you will be able to see projects that you haven't joined.

I meant I'm assuming folks can't see news posts for NPS, OOTW, OOTD, etc. until they've joined thos projects which is not so great for new users that haven't signed up yet and haven't been automatically joined to those projects, but I think this is ok for now. I'll design it in away so they are enticed to sign up so they can see these news posts.



## Here's what's on my design list so far:

- [ ] Project Page
- [ ] Feed Screen when logged out 
- [ ] Nearby Projects Segment screen when user has not given location permissions

Let me know if I left anything out!

**Comment by joellebel** [comment]
@carrieseltzer for the projects we would automatically add folks too which are:

* Observation of the Week
* Observation of the Day
* NPS Centennial 
* Critter Calendar of the Week

The default setting for projects iNat joins you to would be "Don't share private coordinates of your observations with the project curators" We are also in the process of talking about decoupling permissions from following a project, so potentially you could follow a project without worrying about permissions. 

@loarie How did you want to approach Critter Calendar news posts? Automatically join folks to the new project every week so they receive updates since? (Currently there is no umbrella Critter Calendar project)

**Comment by loarie** [comment]
@joellebel, we never really reached consensus on 'pre-joining' projects (e.g. having users join projects without their permissions).  Is this necessary?

**Comment by joellebel** [comment]
@loarie Currently, folks can only see news posts for joined projects which means the Feed section will be empty when people sign up. This was why the need for auto-joining folks to iNat and NPS projects came up in our original discussion. I would love it, if you could just follow a project without having to actually join it, but I thought for the time being we will stick within the current "joining" framework.

**Comment by loarie** [comment]
join v. follow semantics aside (I'll use follow here). I thought one option we discussed if the news feed was empty was something like "get news on the projects you follow here, here are some you should follow..." with some suggestions. But they'd still have to actively follow. 

Is it normal for apps to automatically have you follow stuff?

**Comment by joellebel** [comment]
Ok. If we all have a consensus on that I will mock it up because currently it's mocked up as...

![image](https://cloud.githubusercontent.com/assets/11527994/12463910/213cd1e0-bf7b-11e5-8a91-ae06f521ea98.png)



> Is it normal for apps to automatically have you follow stuff?

Yes, it can be. However, most news apps first ask your interested, but I think that would be a little extreme here. Most importantly, as discussed, it would be a great user experience to see some iNat news by default. I am fine with however we want to technically implement that. (Although, would prefer users to have the ability to simply follow a project as opposed to join.)

**Comment by loarie** [comment]
yeah this is complicated - maybe we should brainstorm more about this

**Comment by alexshepard** [comment]
> Well I guess what I'm really asking is can we make this section auto update so there is no need for a refresh button? :)

That's a lot of scope creep for this "MVP".  We've talked about autoupdating in the past, and we agreed to punt that down the road until we could come up with a technical solution that didn't involve increased network polling. It's on the roadmap, near the bottom (item 18 of 21).

> Oh whoops. Looks like I've never scrolled down enough on a project page to notice that. Will come up with a simple solution for now.

Cool, thanks.

> Yes, that's why I was asking if we can implement a global project search functionality with the above question...

Right, I understand that. I just don't understand why implementing global search functionality also seems to require implementing auto update.

To me, there seem to be ways to change how search works that don't require changing how update works. For example, we could swap "pull to search" for "pull to refresh", like we do on the Me tab observation list, or we could have two buttons in the navigation bar.

> I meant I'm assuming folks can't see news posts for NPS, OOTW, OOTD, etc

Aha, I didn't realize you meant the feed screen. Gotcha.

**Comment by alexshepard** [comment]
Looking over the functional spec for the News List View, I can't tell if the _bacon ipsum_ text is supposed to be the project title, the project post, or both?

**Comment by joellebel** [comment]
> Well I guess what I'm really asking is can we make this section auto update so there is no need for a refresh button? :)

>>That's a lot of scope creep for this "MVP".  We've talked about autoupdating in the past, and we agreed to punt that down the road until we could come up with a technical solution that didn't involve increased network polling. It's on the roadmap, near the bottom (item 18 of 21).

Ok. 


> Yes, that's why I was asking if we can implement a global project search functionality with the above question...
>> Right, I understand that. I just don't understand why implementing global search functionality also seems to require implementing auto update.

>> To me, there seem to be ways to change how search works that don't require changing how update works. For example, we could swap "pull to search" for "pull to refresh", like we do on the Me tab observation list, or we could have two buttons in the navigation bar.

I'm just not nuts about two buttons in the navbar. It's not very iOSy and kinda clunky, but not the end of the world. We could make the refresh button a little smaller and put it directly to the right of the title and the search icon can go in the upper right corner. 

I like pull to refresh, I just don't think folks will think to do that in this section. Just out of curiosity would it be too much to have both pull to refresh and pull to search? Probably. I haven't seen that too much. 

Another idea is a scoped search that slides in as a new screen like on Etsy and Instagram. Let's talk more about it tomorrow in person.

**Comment by joellebel** [comment]
# Projects Screen Search and Refresh Functionality

Alex and I discussed the best way to proceed with this screen. The following modifications will be made:

* Removing pull down search
* Pull down to refresh; Alex will track this event to see if people are using it
* Putting search button (mag. glass) in upper right
* Search searches ALL projects (there will be no scoped search for this release)
* Change search bar hint text to "Search all projects”

**Comment by joellebel** [comment]
# Updates: Location Services and Project Info Screen

@alexshepard 

I've updated the functional spec google doc with the Project list views when location is services are off and added the latest version of the Project info screen. Will work on the styling specs for the project screen and other project screens soon.

**Comment by loarie** [comment]
@joelle, We can delete 
b.) New User
and
c.) Legacy User
from the google doc, right?
Since we decided not to do any pre-joining of new or legacy users to projects?

Re: BioBlitzes, the idea was that we'd come up with some way that users with observations aggregated into a BioBlitz will receive a wrap journal post from the BioBlitz in their dashboard/new feeds even if they haven't joined. So I think we can close the lid on any auto-joining questions, since we're not doing it. Correct?

**Comment by joelle** [comment]
Hey Scott, you have the wrong Joelle. I’m @Joelle on Git but am not the Joelle you need for this project  

_________________________________
* j o e l l e  a l c a i d i n h o


www.thetechbird.com
www.joellewrites.com





www.joelle-a.com
408.256.3553
T @joelle_writes

N @joelle


Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by loarie** [comment]
sorry @joelle! err @joellebel

**Comment by joellebel** [comment]
@loarie, correct. I deleted it from the doc.

**Comment by alexshepard** [comment]
Looking over the spec, when you say "Action menu" do you mean the hamburger button in the navigation bar?

**Comment by joellebel** [comment]
Yes. I just updated the spec. Tnx.

**Comment by joellebel** [comment]
@alexshepard The sketch file for Projects is here: https://www.dropbox.com/sh/8356cznfli3cr6r/AAA4tBTp3QRtVG4O02awEBsqa?dl=0

Along with the screenshots in iphone 6 format for using with TCel. They are in the "Screenshots" folder.

**Comment by alexshepard** [comment]
In the joined project with news, is the "Happy New Big Years..." text the news post title? The first two lines of the body? Some combination of both?

The alignment for the observation / species / observers tab bar items is one way on the joined project screens, another way on the unjoined screens.
Joined:
<img width="427" alt="screen shot 2016-02-07 at 11 53 16 pm" src="https://cloud.githubusercontent.com/assets/515947/12880483/194a7904-cdf6-11e5-92de-9ae37c53e61d.png">
No joined:
<img width="426" alt="screen shot 2016-02-07 at 11 53 27 pm" src="https://cloud.githubusercontent.com/assets/515947/12880484/196a3dca-cdf6-11e5-9da2-6ed7f26f8371.png">
Is this intentional?

**Comment by joellebel** [comment]
> In the joined project with news, is the "Happy New Big Years..." text the news post title? The first two lines of the body? Some combination of both?

Thanks for asking. I was thinking just title. 


> The alignment for the observation / species / observers tab bar items is one way on the joined project screens, another way on the unjoined screens.
Joined:

No. They will be consistent. I'm working on the final visual design today and tomorrow.

**Comment by alexshepard** [comment]
For each of the sub-pages here, we'll need empty states for 1) no network so we can't fetch data, and 2) no data in the project.

**Comment by joellebel** [comment]
Ok. Will get crackin'...

**Comment by alexshepard** [comment]
Also, if you want, we might also be able to use an empty state for "still loading."

**Comment by joellebel** [comment]
# No Network Connection and No Data

![image](https://cloud.githubusercontent.com/assets/11527994/13272418/c17f7384-da50-11e5-86f6-0f8c98311438.png)


# Loading and Still Loading

* I was thinking the "Still loading..." would appear after 3 secs. Let me know what you think. 

![image](https://cloud.githubusercontent.com/assets/11527994/13272426/d3415902-da50-11e5-9eb8-58cfaaeea6d3.png)

**Comment by joellebel** [comment]
@alexshepard I uploaded the latest Project sketch file. https://www.dropbox.com/s/57wmyinwwmu0irr/Projects_v01_r05.sketch?dl=0

Here's a screenshot of the About screen. 

![image](https://cloud.githubusercontent.com/assets/11527994/14443805/61a32c5a-fff6-11e5-8268-0e3150e643f2.png)



Please make the label on the tab black. See screenshot below...

![image](https://cloud.githubusercontent.com/assets/11527994/14443669/8971fb40-fff5-11e5-9f4c-ff159bf1b85a.png)

**Comment by joellebel** [comment]
@alexshepard Projects list view is looking great. One thing...

* Can we give the corners of the project icons 1pt so they match the project list view in the project picker. (I believe they have corner radius, correct?) 

* Also, you can remove the border from the project picker list view. I know this is something you weren't nuts about and now all will be consistent. tnx. ;)

**Comment by alexshepard** [comment]
> remove the border from the project picker list view

you're going to have to be more specific, I don't know what you mean here.

**Comment by joellebel** [comment]
Oh. The 1pt gray border around the project icons on the project picker list view...

![image](https://cloud.githubusercontent.com/assets/11527994/15370926/f9004074-1ced-11e6-9820-f030ab0a40e2.png)
