### ISSUE TITLE
build 287: News Feature Doesn't List Project Title

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/INaturalistIOS#241]
just a piece of insta-feedback: the News tab is intriguing but, as a person who is in a LOT of projects, it is also very confusing. Right now I can't tell which post goes to what and there are lots of 'observations of the month' from different projects all at once. Perhaps it is already in the plan, but I wanted to say it would be great to have the project title on each one after you click on it, or else sort them by project name, or something. Just a thought. Thanks for all your hard work!

C

**Comment by alexshepard** [comment]
Yep, it's in the plan! Thanks for the feedback Charlie. The news items list view has a design from @joellebel that I haven't implemented yet, that's got a lot more context in it.

**Comment by naturalistcharlie** [comment]
exciting, can't wait to see it!

On Wed, Jan 20, 2016 at 7:19 PM, Alex Shepard <notifications@github.com>
wrote:

> Yep, it's in the plan! Thanks for the feedback Charlie. The news items
> list view has a design from @joellebel <https://github.com/joellebel>
> that I haven't implemented yet, that's got a lot more context in it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/241#issuecomment-173410372>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by alexshepard** [comment]
@naturalistcharlie can you try the latest testflight build?

**Comment by naturalistcharlie** [comment]
Oh, yeah that's much better.

On Thursday, January 21, 2016, Alex Shepard <notifications@github.com>
wrote:

> @naturalistcharlie <https://github.com/naturalistcharlie> can you try the
> latest testflight build?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/241#issuecomment-173465394>
> .
>


-- 
Sent from Gmail Mobile
