### ISSUE TITLE
obs creation- manually editing location saves wrong coordinates

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/INaturalistIOS#242]
Tim reported an issue in the google group here: https://groups.google.com/forum/#!topic/inaturalist/b67TZKFGYRg

**Comment by naturalistcharlie** [comment]
this still seems to be happening, i edit a location on the app, and when i look back at it, it's at the original location again. No way to change location on the app when you create an observation. If you save it and then re open it and edit it, it will then allow you to change the location.. but never at first when you create it (that i have seen)

**Comment by alexshepard** [comment]
@naturalistcharlie do you still see this at all?

**Comment by alexshepard** [comment]
keeping open for testing

**Comment by alexshepard** [comment]
ok, i think this should be fixed in 593378fc11c58c1d75461f4d783c88bfb41ba565

**Comment by alexshepard** [comment]
Fixed in 2.6.26
