### ISSUE TITLE
Profile Header Decision

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#244]
We need to decide whether to simple middle align the ob count or put in the ID count as well...

For reference...

![image](https://cloud.githubusercontent.com/assets/11527994/12559730/98320ad0-c34b-11e5-8c15-fa67c2ace713.png)

**Comment by alexshepard** [comment]
We display a bunch of upload state during upload, and when things are pending. Should that change, too?

**Comment by joellebel** [comment]
I would say for now we should leave out ID count and simply middle align the Ob count / Upload progress notification. I have some big ideas for the future of this screen. :)

**Comment by alexshepard** [comment]
ok, sounds good, thanks
