### ISSUE TITLE
read-only observation detail species name frustrations

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/INaturalistIOS#245]
@kueda reports:
> Also, I'm still ​*constantly*​ tapping he species name from me species details screen and expecting the taxon chooser to appear.  i mean from the read-only details screen . it looks identical to the tappable taxon on the edit screen, so i want to tap it and edit

Since this is a user interaction thing, can you advise @joellebel?

**Comment by joellebel** [comment]
Sounds like this will be remedied with this issue: https://github.com/inaturalist/INaturalistIOS/issues/246

Perhaps, we can close this issue?

**Comment by alexshepard** [comment]
sure
