### ISSUE TITLE
Confusing mapping of locations for obscured observations

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#248]
When I manually obscure the location of an observation and look at it in the app, it first loads the actual location but then quickly reloads with the obscured location. This could be really confusing for people because you don't expect your own view of your observations to be obscured.

Can you show people their own observations with the unobscured coordinates?

Version 2.6.6 Build 290.

**Comment by naturalistcharlie** [comment]
I noticed another similar bug that may allow people to see true locations
of obscured coordinates in the app... i don't want to post it here for
obvious reasons but Alex I emailed you about it a while back and it's still
there, let me know if you need me to resend or re-describe. I'm not 100%
certain of the problem but I think it exists.

On Tue, Jan 26, 2016 at 2:25 PM, carrieseltzer <notifications@github.com>
wrote:

> When I manually obscure the location of an observation and look at it in
> the app, it first loads the actual location but then quickly reloads with
> the obscured location. This could be really confusing for people because
> you don't expect your own view of your observations to be obscured.
>
> Can you show people their own observations with the unobscured coordinates?
>
> Version 2.6.6 Build 290.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/248>.
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by alexshepard** [comment]
@carrieseltzer Do you mean on the explore tab or the me tab?

@naturalistcharlie Can you re-send? I think I lost your bug report, sorry. :(

**Comment by carrieseltzer** [comment]
It's in the Me tab.

**Comment by alexshepard** [comment]
@carrieseltzer ok gotcha, I think I can fix that today.

**Comment by naturalistcharlie** [comment]
i resent it to your inaturalist email Alex, is that the best place to send
things?

On Tue, Jan 26, 2016 at 2:37 PM, Alex Shepard <notifications@github.com>
wrote:

> @carrieseltzer <https://github.com/carrieseltzer> Do you mean on the
> explore tab or the me tab?
>
> @naturalistcharlie <https://github.com/naturalistcharlie> Can you
> re-send? I think I lost your bug report, sorry. :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/248#issuecomment-175193668>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by alexshepard** [comment]
@naturalistcharlie yep, got it, thanks!

**Comment by alexshepard** [comment]
@carrieseltzer ok, I think this is fixed as of cdbf813204192fee0e112481dc1abe18b0aa50f3. It will go out in the next testflight build (292) which should go out this evening. When you get a chance, can you take a look and see if it works the way you expect it to? I don't use private/obscured coords a whole lot so I never noticed this!

**Comment by carrieseltzer** [comment]
@alexshepard I'm looking at build 293 now. When I look at the details for my own observations, I see the true location. If I tap on that map, it still takes me to the obscured coordinates. It seems like it should never take you to the random obscured coordinates because I don't think anyone would ever want to see those on their own observations. Does that make sense?

**Comment by alexshepard** [comment]
@carrieseltzer ok, i'll take another look, thanks.

**Comment by alexshepard** [comment]
@carrieseltzer ok, I think it should be finished as of 2a8f5165a5962d8e0b27082a4a7cc310cd77d138 and 399f226c3c59151478d605c7d71c0a711e956ad1. I'll put a build out this afternoon with these fixes.

Thanks again for the bug reports!

**Comment by alexshepard** [comment]
@carrie can you confirm these are fixed in the latest testflight?

**Comment by carrieseltzer** [comment]
Yes, all good in 298 @alexshepard. Thanks!



—

**Comment by alexshepard** [comment]
Cool, thanks!
