### ISSUE TITLE
Feed Section Functional and Styling Spec

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#249]
# Feed List View

## Functional  Spec

![image](https://cloud.githubusercontent.com/assets/11527994/12597023/e1acfcdc-c437-11e5-80af-f9ce970317ee.png)

### Notes

* Feed will be called "News" for now since it only contains newsy items.
* Please use time format that was last discussed which was abbreviated format, but maybe not as truncated. So for example, "h" was "hrs". I'm fine with either. 

## Styling Spec

Let me know if I left anything out...

![image](https://cloud.githubusercontent.com/assets/11527994/12601178/eae6152e-c453-11e5-945e-3cd93ee9cfab.png)

The screenshot for TCel is here: https://www.dropbox.com/sh/2e2co0598vfkpii/AADlstCudrlHtjdu-G9-IyE4a?dl=0

It's at 3x. Let me know if you want 1x.

# Post

## Functional Spec

Please hold off on any changes to the Post screen for now... I'm still working on the profile name treatment.

* We can hold off on the Prev/Next links for a later release. Also, the standard iOS chevrons such as these... 
![image](https://cloud.githubusercontent.com/assets/11527994/12597291/3e6ad808-c439-11e5-967e-8b81a9f3905f.png) can be used.

![image](https://cloud.githubusercontent.com/assets/11527994/12597109/586a8088-c438-11e5-9aa5-16727756fd1e.png)

## Styling Spec

WIP

**Comment by joellebel** [comment]
@alexshepard Styling specs and screenshot of the news list view are ready. Please see the above revisions to the post. Please re-read the notes from the functional spec section as I added some. Let me know if you have any questions.

**Comment by alexshepard** [comment]
The title text looks bold, right?

**Comment by alexshepard** [comment]
Also, what's the overall height of the cells?

**Comment by alexshepard** [comment]
The screenshot you posted for comparison is 1125 × 2001 pixels. I can resize it for my own comparisons, but for future reference, the 5.5" iPhones (the 6+ and 6s+) are 1080 x 1920. The 4.7" iPhones (6 and 6s) are 750 x 1334.

**Comment by joellebel** [comment]
@alexshepard 

> The title text looks bold, right?

It's semibold

> Also, what's the overall height of the cells?

Overall height of the cells is 146pt which includes the hairline (.5pt) bottom border/divider line

**Comment by alexshepard** [comment]
The news item details screen here doesn't show any project information for project news posts. 

It seems to me that it might be helpful to show that here. Sometimes it will be obvious based on the title or the post body, sometimes not so much.

![simulator screen shot jan 27 2016 12 17 55 pm](https://cloud.githubusercontent.com/assets/515947/12626921/10c4089a-c4f0-11e5-9010-fc9a677762a7.png)

**Comment by joellebel** [comment]
@alexshepard 

For now, can we put the title of the project in the navbar?

**Comment by joellebel** [comment]
# Testing for TestFlight Build #293

- [ ] Me > Ob count is still not middle-aligned (Maybe it hasn't been implemented yet)
- [ ] **News Post:** The left and right screen margins are 23pt. Can we make them 15pt for consistency with the rest of the app?
- [ ] **News Post Author Name:** Please give the profile pic a  border of C8C7CC 1pt and move the username and date closer to the profile pic by about three points.
- [ ] **News Post Author Name and Date Color:** Please make this #686868.
- [ ] **News Post Scrollbar:** Anyway to make this scrollbar be closer to the edge of the screen? See gap between scrollbar and right edge of screen in the below screenshot...

![image](https://cloud.githubusercontent.com/assets/11527994/12631322/9d2dbb86-c505-11e5-96b4-c1ba959df466.png)




- [ ] **News List Icon (Project icons) Border:** These icons need a border because many have white backgrounds. Please put a border of C8C7CC 1pt

- [ ] **News List Icons Corners:** Do these currently have a corner radius of .5pt? Doesn't look like it's showing up. If so, can we increase the size of this corner a bit?


Tnx!

## Questions:

* Do we have any control of the date format in posts?

* Can the News snippets in the News list take up the whole cell if there is no photo?

**Comment by alexshepard** [comment]
> Do we have any control of the date format in posts?

Do you mean "3h" instead of "3 hours ago"? I haven't started working on replacing the default translations for the relative strings from YLMoment.

> Can the News snippets in the News list take up the whole cell if there is no photo?

I'll see what I can do.

**Comment by joellebel** [comment]
> Do we have any control of the date format in posts?
>> Do you mean showing "3h" instead of "3 hours ago"? I haven't started working on replacing the default translations for the relative strings from YLMoment.

Oh no. I was referring to this date format...

![image](https://cloud.githubusercontent.com/assets/11527994/12631975/80bd4878-c509-11e5-8776-d1424bdb1b1d.png)

**Comment by alexshepard** [comment]
Oh, it'll be "3 hours ago" in the next build, and then "3h" when I get to replacing the translations in YLMoment.

**Comment by alexshepard** [comment]
I think I did all of the checkboxes except centering the Me tab observation count, which I'll get to someday.

The margins are kind of tricky, since I'm setting the margins in HTML, and I'm not sure how the HTML margins are transformed by the webview and how they compare to native point coordinates. So... if you could take a look at the build and see what you think, we can go from there.

**Comment by alexshepard** [comment]
This text is centered in the space available to it. Is this how you envisioned it?

![simulator screen shot jan 28 2016 12 23 43 pm](https://cloud.githubusercontent.com/assets/515947/12657792/2514a898-c5ba-11e5-9763-75229fdf6119.png)

**Comment by joellebel** [comment]
Thanks for posting. The count just needs to be vertically-middle aligned within that cell like so...

![image](https://cloud.githubusercontent.com/assets/11527994/12657914/b0f0e002-c5ba-11e5-9765-6cee7654e53f.png)

**Comment by alexshepard** [comment]
gotcha
