### ISSUE TITLE
Consider switching to supporting iOS8 and above

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/INaturalistIOS#250]
Apple's recommendations are to support the two most recent iOS releases. 

In the last month, less than 4% of our users were on iOS7 devices.

Users on iOS7 would continue to be able to use the existing app, they just wouldn't get any further updates.

Advantages would be that we could use newer APIs like the new UISearchController, the new UIAlertController, and the new Photos API. Some of the Cocoapods we're using (such as our Gallery view controller) are only supporting iOS8 with their latest updates, so we're also stuck using outdated pods as long as we require iOS7 support. It's also getting harder and harder to test iOS7 as we don't have many devices running it internally, and it's not supported on Apple's TestFlight.

Disadvantages would be that users on iOS7 would not be able to get any bugfixes or further feature updates.

**Comment by loarie** [comment]
4% is pretty small, doesn't seem like thats a huge cost

**Comment by kueda** [comment]
Also, if that 4% refuses to upgrade, won't the app store just continue showing them the last version of the app that works for their OS? It just won't get updated any more.

**Comment by alexshepard** [comment]
Yep, that's right Ken-ichi. But we won't be able to ship any new features or bug fixes, so they'll be locked at that "last version."

**Comment by kueda** [comment]
I think that's fine, and in general, 2 versions of support seems like a reasonable policy to me.

**Comment by alexshepard** [comment]
Done a few weeks ago
