### ISSUE TITLE
Settings Screen Quick Fixes

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#252]
This is a lower priority thang, but was just wanted to propose the following quick UI improvements to the Settings screen when the user is not logged in. 

### Here's a screenshot for reference...

![img_0684](https://cloud.githubusercontent.com/assets/11527994/12632830/cfa5cee6-c50f-11e5-9a7d-d1a7c6fdffc2.PNG)

- [x] Make "Username" the same style as "iNaturalist Network" and "Unknown" the standard iOS table cell value style such as "iNaturalist" in the above screenshot
- [x] Change "Unknown" to "Not Logged In"
- [x] Make the "Sign in" button/link "Log In / Sign Up" and change it to iNat green
- [x] Change "YOUR INATURALIST ACCOUNT" to "ACCOUNT"

**Comment by alexshepard** [comment]
> Make "Username" the same style as "iNaturalist Network" and "Unknown" the standard iOS table cell value style such as "iNaturalist" in the above screenshot

is it OK if the style also changes when the user is logged in?

**Comment by alexshepard** [comment]
fixed in 567ddec37bf714e01c50454d2e19526eccc7da5a

**Comment by joellebel** [comment]
> Make "Username" the same style as "iNaturalist Network" and "Unknown" the standard iOS table cell value style such as "iNaturalist" in the above screenshot

>> is it OK if the style also changes when the user is logged in?

Yes, should be same style. Tnx.

**Comment by alexshepard** [comment]
cool, that's what I did :)

**Comment by joellebel** [comment]
This looks great. One thing I forgot to mention... Can we either remove the heading "VERSION" and just show the version center-aligned. Or leave the heading and remove the word "Version" before the version number. Right now it's redundant. (This is really low priority)

**Comment by alexshepard** [comment]
yep, done in 4881604a2684fd150047cb4dc72dd140244b73a1

**Comment by joellebel** [comment]
Tnx!
