### ISSUE TITLE
Feature Idea: ID Please on App

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/INaturalistIOS#253]
Just a feature idea for the distant future, if the iNat team and other users are interested. 

I mostly only use the iNat app for adding data to the site, which is fine, However,  it might be fun to have a way to help ID observations on the app as well. The new ID Please feature on the website has been great, and I can imagine one on the app as well. You'd put in the filters (and perhaps be able to save filters) and then it would show you an observation. Most prominent would be the photo but the map and other data would need to exist too. You would be able to agree with ID, suggest another ID, or click 'don't know' in which case it would be flagged as reviewed (unless you told it not to). Then when identifiers have a spare minute stuck waiting in line or something they could whip through IDs. I imagine it being kind of like how Tinder works except I've never used Tinder so I'm not really sure if that is right or not. Instead of marking whether you want to date or hook up with someone you would add a species ID.

Anyway maybe low priority since I know there aren't that many people doing IDs... but I think it could be a fun feature, one day.  Anyone else reading... would you use this if it existed?

**Comment by kueda** [comment]
I'm going to close this b/c we're hoping to incorporate a filter for Needs ID stuff in a redesign of the explore section... which will probably come to Android first (sorry, but you iOS users will probably get computer vision stuff first).
