### ISSUE TITLE
Location issues unclear when not online

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#254]
If you create an observation from an existing photo when you aren't connected to the internet, the app confusingly says "no location." or "location not geocoded". I think it means that it can't georeference the place name associated with those coordinates, but I think people will be confused.

What if it just doesn't show any text about the location aside from the coordinates if it isn't online? 

Screenshots:
https://goo.gl/photos/jQkJLhziipzS9CBJ8
https://goo.gl/photos/y2xd8ro4Guw1EYGL7

Build 299

**Comment by alexshepard** [comment]
That field is also where we show the geo obscured or geo private icons. 

In the case where the user is offline do you think it's OK to hide these icons, too?

**Comment by alexshepard** [comment]
Or we could just show lat: and lng: instead of a place name, I'm just now realizing you may be suggesting?

**Comment by carrieseltzer** [comment]
I think that showing just lat long would be preferable to saying "no location" when it actually has one. 



—

**Comment by naturalistcharlie** [comment]
except when it's obscured of course!

On Sat, Feb 6, 2016 at 7:41 AM, carrieseltzer <notifications@github.com>
wrote:

> I think that showing just lat long would be preferable to saying "no
> location" when it actually has one.
>
>
>
> —
> Sent from Mailbox
>
> On Fri, Feb 5, 2016 at 6:49 PM, Alex Shepard <notifications@github.com>
> wrote:
>
> > Or we could just show lat: and lng: instead of a place name, I'm just
> now realizing you may be suggesting?
> > ---
> > Reply to this email directly or view it on GitHub:
> >
> https://github.com/inaturalist/INaturalistIOS/issues/254#issuecomment-180626660
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/254#issuecomment-180753317>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by alexshepard** [comment]
The app now says 
> Unable to find location name

in this case
