### ISSUE TITLE
Photo set default is glitchy

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/INaturalistIOS#255]
On my recent newt observation, trying to change the default instead seems to shuffle the photo sort order.

**Comment by alexshepard** [comment]
This only happens if you're trying to change the default image after a photo has been uploaded. Because of the way I built the observation upload stuff, the locally edited positions get overwritten when the observation is updated.

**Comment by kueda** [comment]
FYI, still happening as of build 312. Recently had a bug report from a user who provided this sequence of steps:

> Open the app
> Click on observation
> Click on edit
> Click on circle next to the second picture which triggers them to switch positions
> Click on save
> Go back to observations
> No change to the default picture
> 
> 
> Sometime I toggle the "help me identify" button because it is always off when I edit.  When I do that he default picture changes. But when I open the app later the default reverted back

**Comment by alexshepard** [comment]
still happening for me

**Comment by alexshepard** [comment]
Released in 2.7
