### ISSUE TITLE
Solution for Lack of Geocoding Scenario

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#257]
Recently, I made about 35 obs while not having network, so the geocoder couldn't work, and the app as built can't recover from that very well.

Currently, the user has to tap Edit and then Done for the geocoding placename to appear in the on the ob detail screen. Otherwise, the label says, "No location." with a map marker on the lat/long coordinates. This can be cumbersome if the user has more than a few observations.

**Comment by alexshepard** [comment]
To tie this to #254, we used to just display the latitude and longitude all over the app if we hadn't gotten a geocoder response. We could just go back to doing that. In other words: how important is the place guess, really?

**Comment by joellebel** [comment]
A couple other things to keep in mind (which I forgot to mention earlier) is that the Edit screen is different from the Ob Detail screen in that it has a placename so it is unclear that the user has to tap Done to save it. Also, there is no confirmation to save or discard edits when tapping Cancel. There could be a dialogue box when tapping Cancel that asks the user if they want to discard placename edits, if that's the only edit that is ocurring. This way it is clear what is and is not getting saved. We can talk more about it today. Just wanted to document this here. It's also referenced here: https://github.com/inaturalist/INaturalistIOS/issues/258

**Comment by alexshepard** [comment]
For posterity, I believe the conclusions we (@joellebel, @kueda and @alexshepard) came to were:

- if needed, server will add a place guess upon new observation upload
- iOS app will not try to geocode a place guess on observation edit (unless location has changed) (done in 1d0f825acc1f14e6d0b8960ab5fd18b069d1774e)
- iOS app observation detail VC will show latitude and longitude if there's no place guess (done in 21ac35d1f7dcf1d8953ac127883b74911dac694b)

If I got anything wrong, please comment.

**Comment by kueda** [comment]
Server-side part of this should now be done.
