### ISSUE TITLE
Agree Loading

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#261]
Currently, there is no feedback to alert the user the app is processing their agreement when they tap agree. This can result in users tapping the agree button twice if the process is taking long. Here's a few options...
## Dir 1: Agree Loader Next to Agree button

Putting the standard iOS loader next to the agree button

![image](https://cloud.githubusercontent.com/assets/11527994/13339953/4d973442-dbe1-11e5-8f50-f65d3f86039a.png)
## Dir 2: Agree Loader Replacing Checkmark Icon

![image](https://cloud.githubusercontent.com/assets/11527994/13340002/a6e13ed0-dbe1-11e5-9c34-dc37de93ed29.png)
## Dir 3: Loading Pop Up Modal

We use a loading pop up modal in other parts of the app. This seems like overkill, but maybe it's the quickest solution?

I'm totally open to other options. 

@alexshepard Please provide any feedback and let us know what some other options or faster solutions are if you have any.

**Comment by alexshepard** [comment]
we are using the pop up modal now. it may indeed be overkill, but it works.

**Comment by joellebel** [comment]
Sure thing. The only thing is that if scrolled down the screen, I don't see a loading state. This is what I see...

![img_6118](https://cloud.githubusercontent.com/assets/11527994/25889639/563fc558-351f-11e7-8888-ec123a3ab7a6.PNG)


Shall I file a bug for this?

**Comment by joellebel** [comment]
I am using the latest test flight build

**Comment by alexshepard** [comment]
Sure, a bug would be great.
