### ISSUE TITLE
Can't save edited location when adding from a guide (stuck on screen/have to quit app)

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#265]
Ran into a tricky bug when adding an observation from a species guide. To replicate:

-Open the app.
-Click into any guide. Click on any species. Click observe.
-Tap the location. Edit.
-See map screen to edit location.
-Save button and cancel buttons both don't work. **The only way to get out is to force quit the app.**

Build 302

**Comment by alexshepard** [comment]
guides new observation now uses the new obs flow which doesn't have this problem
