### ISSUE TITLE
Formatting issues with guides

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#266]
See screen shots of:

-search bar overlapping first row of images
https://goo.gl/photos/zohd8MwWXQZ7btcN9

-tapping into search bar pushes search bar up into main iOS header space
https://goo.gl/photos/y2csS7jvTNzTydwh8

-description of Dyke Marsh guide cut off (compare to the website: http://www.inaturalist.org/guides/2194)
https://goo.gl/photos/NpFSM5RjM8sD7Ls66

Build 302

**Comment by alexshepard** [comment]
description cut off fixed in 39b15a9b3483571972288cf21fa0840dee5136a9
search bar tweaks are in 080d5414f9310cdf3e2389ad8282440d29be1113

**Comment by alexshepard** [comment]
released in 2.7.1
