### ISSUE TITLE
Projects Header Animation

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#267]
The following animations are based off the current animation. Certainly open to ideas. I do like the sophistication of Spotify and Twitter header animations, but thought it was probably best to start out simple. 

Just a reminder... after clicking on a an animation, the page needs to be refreshed to see it again. I was trying to prevent anyone from getting a headache. 

# Direction 1: Sticky Project Title

### Short Title

In this animation the project title remains in the nav bar once it reaches it's project y coordinate. The buttons and project icon fade out.

[animation_v01_d01_r01](https://cloud.githubusercontent.com/assets/11527994/13684291/e731987a-e6bf-11e5-9423-3849d529472a.gif)

### Long Title Scenario

As you can see this wont work well for long titles so there probably needs to be a shorter char. limit than we currently have. 

 
[animation_long_title_v01_d01_r01](https://cloud.githubusercontent.com/assets/11527994/13684746/f220540e-e6c1-11e5-979a-09df67ac3ab2.gif)

### Other Concern

I am also not sure how things will look if there are only say 4 rows of content in the Observations tab and the page is scrolled to the top. If we don't leave some extra padding underneath the last row the scroll could end up in a weird point where the project buttons are halfway faded. 

# Direction 1: Title as Separate Animation

### Title Fades In

Same animation as above but the original project title fades out and a new one fades in.

[animation_v01_d02_r01](https://cloud.githubusercontent.com/assets/11527994/13684292/e7319f50-e6bf-11e5-8d13-fbe62082ba26.gif)

### Title Slides in from Above

Same animation as above but the original project title fades out and a new one slides in from above. 

[animation_v01_d03_r01](https://cloud.githubusercontent.com/assets/11527994/13684294/e7363e16-e6bf-11e5-9aee-a895b20afcd1.gif)

# Conclusion

I like the sticky title the best because it feels the most natural and least complicated.

**Comment by alexshepard** [comment]
these were done as part of the new projects ui going live
