### ISSUE TITLE
app was not allowing more than one photo to be added to observation

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/INaturalistIOS#268]
This one is not reproducing for me now but reporting it anyhow in case others have seen it.

Earlier today I was not able to add a second photo to an observation. Build 302.

I created an observation and took a photo. I tried to add a second photo, but the camera image would freeze or hang and no second photo would be taken. I had to cancel out. I then saved the observation and tried to add a second photo via editing it, and it made the app crash.

However I am trying it now at home and it isn't happening. I will test further tomorrow. but you probably saw the crash in the crash log around 5:30 or so today.

**Comment by kueda** [comment]
This doesn't seem to be happening any more.
