### ISSUE TITLE
Error: Could not find an object mapping for keyPath: "

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#272]
iOS 9.3, iNat Build 302.

Auto-sync is off. I entered 8 observations. I went back and edited one to add more photos before syncing. When I tried to sync, I got this: Whoops! Looks like there was an error: Could not find an object mapping for keyPath: "

Deleted the observation where I'd gone back and edited in case that was the problem. Same error. Deleted the first observation in the queue; same error. Deleted each observation and tried to sync. Same thing. When all observations were deleted, I added a new one and tried to sync. Same problem. Logged out, logged back in (using Google), added new observation, same thing.

Downloaded new version from TestFlight. Still failed with v. 2.6.8 build 314. Tested with and without photos. Same error every time.

Since none of my troubleshooting approaches worked and I'm not sure what triggered this, I'm going to post to the google group too in case other people are having this problem. Hope it's only widespread enough to quickly troubleshoot and solve!

**Comment by pleary** [comment]
Not sure if this is related, but between about 3:30 am and 9:45 am EDT the system was incapable of taking identifications or new observations, perhaps entirely, but at least those with locations. That might have played a role in some of the errors

**Comment by carrieseltzer** [comment]
Works now! That might have been the problem.
