### ISSUE TITLE
allow change of username in the app

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#273]
This has got to be our number 1 support request from both mobile apps. Maybe a link to https://www.inaturalist.org/users/edit would suffice, but something native would be preferable, particularly given that we use the username to construct some URLs.

**Comment by alexshepard** [comment]
Now that the app can support username changes (as of 15c307dd358878933c0b70f72ae3cd0ff888a445) which I thought was the entirety of this issue (oops), we have an issue (#308) that I'm closing this in favor of, because that Joelle is already working on that one.
