### ISSUE TITLE
Taxon search autocomplete for local and remote taxa

### ISSUE THREAD

**Issue by pleary** [inaturalist/INaturalistIOS#274]
It seems to me that when I search for taxa in the iOS app, I do get autocomplete results for things I have searched for before, but not for things I haven't search before and are not in the local app cache (those seem to need me to type in the entire name, which might be tough to spell).

I wonder how hard it would be to use the newish node.js taxon autocomplete API (http://api.inaturalist.org/v1/taxa/autocomplete?q=Tom) in the app. I wonder if it would help users get results faster, and thus make observations faster.

**Comment by alexshepard** [comment]
Should be safe to close, right @pleary?

**Comment by pleary** [comment]
new taxon autocomplete is working great!
