### ISSUE TITLE
can't change location for new observation

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#276]
To replicate:

1. Start a new observation, either take a photo or skip
1. Tap the location to bring up the location editor, drag the map to somewhere other than where you are right now, and tap Done.
1. Confirm that the `place_guess` has changed and tap "Save / Share"
1. Edit the same observation. The `place_guess` is indeed different, but the coordinates are the initial coordinates from the GPS, not the ones you chose by using the location editor.

FWIW, this doesn't seem to happen when you *edit* an observation, only when confirming a new one. First reported at http://www.inaturalist.org/observations/2963130

**Comment by naturalistcharlie** [comment]
Just as an update, still happening, Build 325. Changed a location and it reverted to initial observation location.

**Comment by alexshepard** [comment]
_should_ be fixed as of 17df64a85be0a761a619371b91c576f388eb996b which will be in TestFlight build 341

**Comment by alexshepard** [comment]
@kueda closing this as it's fixed for me.
