### ISSUE TITLE
Sign Up Slideshow Version 2.0

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#277]
Just creating an implementation issue for the Slideshow....

# Final Mock Up

## Slide 1: 
![image](https://cloud.githubusercontent.com/assets/11527994/14959474/5eef52e6-1044-11e6-9512-b8561c097b38.png)

## Slides 2-5:

![image](https://cloud.githubusercontent.com/assets/11527994/14959387/fed48962-1043-11e6-8341-6685e899f3f5.png)

## Sign Up Form

![image](https://cloud.githubusercontent.com/assets/11527994/14959504/83ad92a0-1044-11e6-923e-b550a4dcc5a0.png)

@alexshepard  The trial PNGs for the slides are here on dropbox: https://www.dropbox.com/home/iNaturalist/Design/iOS/Sign%20Up%20Slide%20Show%20V02

Please use this image for all slides and once I see how it's looking I'll create the rest. 

# Specs

Coming...

**Comment by joellebel** [comment]
# Log In Screen

Here's a look at the Log In screen (right). Tapping "Already have an **Account**? takes the user to the Log In screen. Tapping "New to iNaturalist? Sign up now!" takes the user to the Sign Up screen.


@alexshepard can you give us some ideas as to what the easiest transitions between the two are? Tnx.

![image](https://cloud.githubusercontent.com/assets/11527994/14966577/11f55764-1068-11e6-9e5b-bdaaed144a55.png)


### Here's a look at all the slides together just to give you an idea of visuals and flow...

![image](https://cloud.githubusercontent.com/assets/11527994/14966649/6a938bc0-1068-11e6-8182-858ddd7fb6af.png)

**Comment by naturalistcharlie** [comment]
i love the graphics on these

On Mon, May 2, 2016 at 11:59 AM, joellebel <notifications@github.com> wrote:

> Just creating an implementation issue for the Slideshow....
> Final Mock Up
>
> Note this mock up is missing the first slide which is the logo screen and
> the sign up/log in form.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/11527994/14959387/fed48962-1043-11e6-8341-6685e899f3f5.png>
>
> @alexshepard <https://github.com/alexshepard> The trial PNGs for the
> slides are here on dropbox:
> https://www.dropbox.com/home/iNaturalist/Design/iOS/Sign%20Up%20Slide%20Show%20V02
>
> Please use this image for all slides and once I see how it's looking I'll
> create the rest.
> Specs
>
> Coming...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/INaturalistIOS/issues/277>
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by joellebel** [comment]
@alexshepard Here is the Sketch file: 
https://www.dropbox.com/s/8u9ksjmrsgbl9q2/Sign_Up_v02_r03.sketch?dl=0

Please let me know if you have any questions. There is a question in the file regarding margins and different phone sizes. I'm trying to avoid any customized layouts. Probably easier to have a quick discussion about it. 

Just a note that the sign up and log in forms are the same as they are now, but the only difference is color.

**Comment by alexshepard** [comment]
Is "Explore and Connect with Nature" our new tag line?

**Comment by loarie** [comment]
You mean as opposed to 'Explore * Learn * Record' I don't think that was used anywhere other than the old splash screen/home page so I'm not opposed to changing it/deferring to joelle - but curious what @kueda thinks

**Comment by alexshepard** [comment]
Explore! Learn! Record! was on the old homepage, too.

The new homepage has:
> Connect with Nature
> Explore and share your observations from the natural world.

**Comment by kueda** [comment]
I don't feel strongly about the tag line.

**Comment by alexshepard** [comment]
OK

**Comment by joellebel** [comment]
I prefer "Explore and Connect with Nature" over 'Explore * Learn * Record' because it's more specific to nature. 'Explore * Learn * Record' could refer to numerous productivity and educational apps.

**Comment by alexshepard** [comment]
I just thought our new tag line was "Connect with Nature" since that's what's on the website. I don't have a personal opinion on the text.

**Comment by joellebel** [comment]
totes. That one is shorter because there's a subhead and the rest of the page explains the apps. However, eventually we should come up / agree to a tagline we can use everywhere and consistently.... another issue for another time. @alexshepard it's good you brought it up though.

**Comment by alexshepard** [comment]
There's no option to skip login/signup, is that intentional?

**Comment by alexshepard** [comment]
Where do you see the partner prompt showing up?

**Comment by alexshepard** [comment]
The prompt that people in partner geographies see when they have the option of using say Naturalista instead of iNaturalist as their home site.

**Comment by alexshepard** [comment]
@joellebel do you envision this entire flow replacing the signup/login popups in the app? Or will the slideshow only happen on app launch, and something else (just the final screen?) showing up when you should get a login prompt within the app?

**Comment by joellebel** [comment]
Here's what


> @joellebel do you envision this entire flow replacing all of the signup/login popups in the app? Or will the slideshow only happen on app launch, and something else (just the final screen?) showing up when you should get a login prompt within the app?

I was thinking it would be the same as we have now...  The slideshow only happens on app launch and  we only show the final slideshow screen (sign up screen) and if someone taps "Already have an account?" the log in screen would slide in from the right. See below mock ups of both screens. Note the X in the upper right to dismiss.

![image](https://cloud.githubusercontent.com/assets/11527994/17501376/ea004ce6-5d92-11e6-96d6-33a8ee17b65e.png)

I put the sketch file here on dropbox for you to get sizing from, if you need it for the skip button and what not... Design > Sign Up - Log In > Version 2.0


## A couple things...

* "Account" in "Already have an Account?" should be all lowercase
* I changed the "Or log in with:" text to #7B7B7B (This should help with the text heavy-ness of the page)
 
* I made "Already have an Account?" 15pts. It was a little small.

**Comment by alexshepard** [comment]
Ok, cool. What does the back button on Log In do?

**Comment by joellebel** [comment]
It just takes you back to the sign up screen like it currently does. We could always put an X in the upper right of the Log In screen so folks can cancel from there as well. (I was just trying to keep it similar to what we have now) I'm fine either way.

**Comment by alexshepard** [comment]
If you play with the recent TestFlight builds you'll see that this screen just reconfigures rather than having a push animation, so I don't think the back button logically fits. Easier to just keep the close button.

**Comment by alexshepard** [comment]
I probably should have pointed that out in the demo I did this afternoon, sorry if it wasn't obvious.

**Comment by joellebel** [comment]
> If you play with the recent TestFlight builds you'll see that this screen just reconfigures rather than having a push animation, so I don't think the back button logically fits. Easier to just keep the close button.

Sounds good.

**Comment by alexshepard** [comment]
Any further thought on the partner prompt?

**Comment by joellebel** [comment]
@alexshepard Can you show me a screenshot of what it currently looks like and where in the process they get it? tnx.

**Comment by alexshepard** [comment]
![simulator screen shot aug 16 2016 4 14 37 pm](https://cloud.githubusercontent.com/assets/515947/17719064/af1d1cc2-63cc-11e6-8ac4-a3b56fb3cf7f.png)

**Comment by joellebel** [comment]
That works for me. It would be nice if the Naturalista logo was where it says "Use Naturalista?", but I think we've talked about this and an image cannot be in the title of a standard model, correct? If so, definitely not worth the time to do anything custom.


Also, wondering if it's best to bold "No" because it seems a little leading. ...But if the majority of folks who get this message are not people that would use naturalista, I think the bold might make sense.

**Comment by alexshepard** [comment]
For my own memory, in Slack, Joelle said:

> I kinda wanna do the closest thing to what we’re doing now so as not skew the A/B test.  I guess this would mean that the modal pops up when you get to the last screen in the slideshow

**Comment by joellebel** [comment]
Here's what I was originally thinking for the "Skip" button. See below...

![image](https://cloud.githubusercontent.com/assets/11527994/17720947/0672443a-63db-11e6-8e65-72fbb8a3a7a2.png)

Please also see the below direction. It has the "Already have an account? Log in" at the bottom which is more similar to the current slideshow. Was just wondering if it's better to go this route in the interest of a better A/B test? I also like it better because it seems a bit less cluttered. @alexshepard what do you think? If it's time consuming to make this change, no need to proceed with the this direction. 

![image](https://cloud.githubusercontent.com/assets/11527994/17721029/b2b920b0-63db-11e6-8c2f-9c3d52934886.png)

Here's the current for reference...


![image](https://cloud.githubusercontent.com/assets/11527994/17721128/a78ad606-63dc-11e6-9280-bae11109398a.png)


I'll upload the updated sketch file to dropbox once direction is decided.

**Comment by alexshepard** [comment]
Can you only skip from signup, or was that just a quick sketch?

I don't have much of an opinion between the two directions. 
This signup screen is cluttered either direction. There are 13 distinct user-interact able UI elements that each do different things on this screen, which seems like a lot to me.

**Comment by alexshepard** [comment]
@joellebel forgot to add a mention to the above, sorry

**Comment by kueda** [comment]
IMO (for whatever that's worth), I don't think it's that much more complicated than the existing sign up page, mostly just adds the social log in buttons. Also, I much prefer the "Already have an account?" bar at the bottom, and think it could use even more prominence. I don't think we need a redesign if Alex is near completion, but I will say that we do have a minor support problem with web users trying the app, signing in with Facebook / Google, and creating duplicate accounts that need to be merged, so hiding the ability to sign into an existing account won't help that. Of course, my preference has always been for no signup slide show at all, so I'm probably in the minority.

**Comment by joellebel** [comment]
Yes, "Skip" is only on the last screen because I thought we were going to test the difference in slideshows and making folks swipe through the whole slideshow. I can certainly add a skip button to all screens in the slideshow if folks disagree. 

If we want to keep the sign up screen to one screen I'm not seeing much of an alternative to what is above unless we do some hide and show elements on the screen. For example we could show the 3 login type buttons (FB, Google and email) and if email is select the others slide off the screen and  the form is revealed. I think that would look great actually and can show you examples of how other apps do it. @alexshepard Is that type of animation something you'd be interested in or up for?

**Comment by alexshepard** [comment]
> Yes, "Skip" is only on the last screen 

That's not what I was asking about. You added it to the Signup view but not the Login view. Was that intentional?

**Comment by joellebel** [comment]
> Yes, "Skip" is only on the last screen

>> That's not what I was asking about. You added it to the Signup view but not the Login view. Was that intentional?

Oh. No, I thought we didn't need it there because it was going to be dismiss-able with an X in the upper right as discussed here... (https://github.com/inaturalist/INaturalistIOS/issues/277#issuecomment-238427524) Looks like I left that out of the last mock up. My apologies.

**Comment by alexshepard** [comment]
> If we want to keep the sign up screen to one screen I'm not seeing much of an alternative to what is above unless we do some hide and show elements on the screen. For example we could show the 3 login type buttons (FB, Google and email) and if email is select the others slide off the screen and the form is revealed. I think that would look great actually and can show you examples of how other apps do it. @alexshepard Is that type of animation something you'd be interested in or up for?

Honestly I'm looking forward to getting this done and working on other stuff. It sounds like I'm in the minority for my concerns about complexity, so I'd prefer to finish the design we have, and I'll live with my reservations.

**Comment by joellebel** [comment]
Ok. Sounds good.

**Comment by joellebel** [comment]
Sounds like @kueda and I both prefer this guy... (I added the < and X)

![image](https://cloud.githubusercontent.com/assets/11527994/17818716/92d2b142-65f9-11e6-9134-b371a38561f9.png)

**Comment by alexshepard** [comment]
OK, so it looks like the `Already have an account? **Log in**` text goes where the Page Controller (the dots) goes in the previous screens? I'll see what I can do, the UIPageController wasn't built to work this way.

**Comment by joellebel** [comment]
I guess since the screenshots you sent are to scale the skip button size is ok. Just need 3 changes to the screen. See below...

1. Font color change
1. Skip border color change
1. Chevron: Can we use the "Skip" chevron we're currently using. It's smaller and more elegant. 

![image](https://cloud.githubusercontent.com/assets/11527994/18111954/a5cbdb10-6ed8-11e6-90f4-f0fad1af833c.png)


Will share iPad soon...

**Comment by joellebel** [comment]
@alexshepard 
# iPad Fixins'
I've grouped elements together and vertically middle-aligned this group on the screen. This is what the final product would look like... (more details down below)
![image](https://cloud.githubusercontent.com/assets/11527994/18113517/542f3196-6ee5-11e6-8176-4e1c83b713a9.png)

## Slideshow

I moved the logo up by about 100pts. Doesn't have to be precise. Just wanted to give you an idea of the change. Also, the group doesn't have to be perfectly vertically middle-aligned on the screen but just needs to look close. None of these screens have to be precise... just need to looked grouped and somewhat in the middle of the screen.

### Vertical Layout

Left screen is current, middle screen is the proposal and right screen is the specs.  

* Width of text is limited to 500pts on both vertical and horizontal layouts. 

![image](https://cloud.githubusercontent.com/assets/11527994/18113746/e3215f5e-6ee6-11e6-8c6a-d66872e0658e.png)


![image](https://cloud.githubusercontent.com/assets/11527994/18113750/eaf88a7c-6ee6-11e6-8531-95d30936ac8a.png)


### Horizontal Layout

![image](https://cloud.githubusercontent.com/assets/11527994/18113677/7c64466e-6ee6-11e6-8937-eb8dc94ab253.png)


## Form

* I about doubled the space between the Sign Up button and the last input field. I'm sure the spacing
* Elements that have 25pts of spacing between them don't have to have exactly 25pts of spacing between them. It's more important that the spacing just looks consistent. 
* I didn't do specs for everything or design for the vertical sign up form, but let me know if you need it. 

#### Log In Vertical

![image](https://cloud.githubusercontent.com/assets/11527994/18113999/a761783a-6ee8-11e6-8aaa-6724a154b59f.png)

#### Log In Horizontal

![image](https://cloud.githubusercontent.com/assets/11527994/18113957/4ad68722-6ee8-11e6-986d-6f79df5f315a.png)


#### Sign Up Horizontal

![image](https://cloud.githubusercontent.com/assets/11527994/18113965/5f41e300-6ee8-11e6-909f-c0ac9b70da24.png)

**Comment by joellebel** [comment]
Going to close this issue because it looks like we're good to go!
