### ISSUE TITLE
"Unknown" community ID should not be tappable

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#282]
When looking at an "Unkown" ob that is not my own and tapping on the community ID, I get a gray pressed state as in the below screenshot....

![image](https://cloud.githubusercontent.com/assets/11527994/15589324/38823cac-2347-11e6-87df-3a309375ef88.png)

Please remove the pressed state since it's on a road to nowhere.

**Comment by alexshepard** [comment]
Can't remember when, but this has been fixed for a while.

**Comment by joellebel** [comment]
Oh weird. I'm still getting it. I'm on build 340. When I tap it, the bg of the cell turns gray for a second or two then fades back to white.

**Comment by alexshepard** [comment]
Ah, I mis-understood what you were reporting. Should be fixed in build 343.

**Comment by joellebel** [comment]
Tested. Looks good to me.
