### ISSUE TITLE
"Uknown" observation labelled as "Something..." in the Explore >  Grid View

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#283]
We should probably change "Something..." to "Uknown" for consistency sake on this screen...

![image](https://cloud.githubusercontent.com/assets/11527994/15589477/e4e5877e-2347-11e6-90ab-ce53b7535483.png)

**Comment by alexshepard** [comment]
Changed (along with the list view) in https://github.com/inaturalist/INaturalistIOS/commit/4a0d6881f5f8412a95839f4910975d18eee2c986
