### ISSUE TITLE
Map Legal Link Issues

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#284]
- Somehow the "Legal" link on the map has wandered up and to the right. Can we put it back to the lower left corner. 
- I also noticed it doesn't work when I tap it. Should it be linking to a Google legalities web page?
### Current

![image](https://cloud.githubusercontent.com/assets/11527994/15758434/71411c66-28bf-11e6-841d-d4557508c6c8.png)
### Proposed
- "Legal" has a bottom and left margin of 15pts (same as location label white box)

![image](https://cloud.githubusercontent.com/assets/11527994/15758474/a594dc46-28bf-11e6-9d4c-3ca2f9201039.png)

**Comment by joellebel** [comment]
You mentioned we cannot move the "Legal" link. No problem. Just wanted to point out that tapping it doesn't take me to the Google Legal screen. Is that ok? However, the link does work on the map screen.

**Comment by alexshepard** [comment]
should be fixed/moved in c9527e0d68cc18cdde8e3555f0edd3ae07e8ffa9

unfortunately, the link here has to be un-tappable, because we can't let the user interact with the map there. if we do, the user will be able to scroll in the map, and tapping on the map in the detail screen won't open the big map.

**Comment by joellebel** [comment]
Okeedoke. I'll look for the change in the next release. tnx!
