### ISSUE TITLE
False edits being triggered by other interactions with app

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#291]
I was testing out the Korea language versioning and encountered a bug which I was able to replicate when my phone is set to English as well. 

To replicate:
Log in with email address.
Make an observation (I used the camera within the app).
Save, then upload fully. See there are no alert badges on "Me"
Tap "more" (or settings, or view details of an observation)
Tap "Me" again. See badge return and most recent observation shows that it needs to be uploaded again.

Seems like a pretty annoying bug worth fixing right away. Could be a real data hog on auto-update since it's constantly triggering updates.

2.6.12 Build 331

**Comment by alexshepard** [comment]
I'm not able to always reproduce this,Mobutu I see it sometimes. Grr... Will keep looking.

**Comment by alexshepard** [comment]
@carrieseltzer are you still seeing this? if so, can you please re-open?
