### ISSUE TITLE
Options for decreasing the no. obs with no locations or no (photos & taxon names)

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#293]
A large proportion of observations coming through the app have
a) no locations
or
b) no photos or IDs
On the new web obs/upload we added these alerts on submit:
<img width="509" alt="screen shot 2016-06-23 at 6 56 17 pm" src="https://cloud.githubusercontent.com/assets/598026/16325589/2ea637cc-3974-11e6-8f78-c7eb6c2f47af.png">
<img width="511" alt="screen shot 2016-06-23 at 6 56 02 pm" src="https://cloud.githubusercontent.com/assets/598026/16325591/30114372-3974-11e6-8f21-7cf12ef5278d.png">

What should be the approach for mobile?

Option 1:
Put native alerts before save for (a) & (b)

Option 2:
Put native alerts before upload for (a) & (b)

Option 3:
Put alerts from server after upload similar to project validation errors
![img_6781](https://cloud.githubusercontent.com/assets/598026/16325630/8eb9db1e-3974-11e6-96b6-4cd43554578a.jpg)

Thoughts?

**Comment by alexshepard** [comment]
It would be simplest to add a notice to the Save/Done flow. 

We could always add a "don't show me this alert again" button if people complain, but I doubt anyone is making legit observations missing these properties, unless they have some corner-case workflow where  they take photos with their DSLR but make observations with their phone (for geo for example), and then later add the DSLR photos to the observation.

It looks like the flow is:
```
if !taxon AND photos.count == 0 {
  alert("the combo of no photos and no taxon is bad")
} else if !date OR !location {
  alert("either no date or no location is bad")
}
```

If the user has 30 observations pending when an upload starts, option 2 might make it hard to tell what to fix if only one or two are missing needed data.

@joellebel?

**Comment by joellebel** [comment]
Adding a notice to the Save/Done flow sounds good to me.

**Comment by alexshepard** [comment]
Initial stab at this is in dde5f6ee8950fc700d98fd07444970267a0aee65

Which will be in TestFlight build 342

**Comment by joellebel** [comment]
Tested. Looks good to me.
