### ISSUE TITLE
feedback on new taxa chooser

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/INaturalistIOS#295]
Testing out the new species chooser for build 335. Mostly, it's really great. It's uch faster and requires less clicking and when you search by genus the genus level tag is first instead of way at the bottom.

My only concern is the filter seems to only work for one word. For instance I can write in Carex and get a long list of the more common Carex, but they aren't all there and some are way at the bottom. I'd rather be able to write "Carex int" and have Carex intumescens pop up. Likewise if you use a descriptor that many taxa have, such as "white" or "lesser" you will get some but not all taxa. For instance white gets you white oak and white pine right at the top, but white ash is way at the bottom and I'd rather type 'white a' and see white ash. 

Of course I can just write in the taxa full name or the six letter code so it's not a big deal. But it would be a positive change if it's not too hard to do

**Comment by alexshepard** [comment]
Fixed in b1057a83fc51a94a803659f09409832277ba5a57 thanks for the report. Will be in the next beta build.

**Comment by naturalistcharlie** [comment]
awesome! And great work on it, other than that little thing i really like it. so fast.

**Comment by joellebel** [comment]
I'm really liking the new taxon chooser as well. The only thing I miss is the list of iconic taxa that used to appear below the search box. As a novice naturalist I tend to use those frequently. Plus, I think it gives some direction to newbs that may not realize we have these major categories.

**Comment by alexshepard** [comment]
Can you open a new issue about the iconic taxa, @joellebel? I'd like to close this issue since the bug that Charlie reported is fixed.

**Comment by joellebel** [comment]
@alexshepard sure thing.

**Comment by alexshepard** [comment]
Thanks!
