### ISSUE TITLE
Ghost observations created

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#297]
About 530 empty observations were created from the iOS on my account this morning around 7:30am. I was not using the app at the time. Please let me know if you need any other info. 

Here's what I'm seeing for visual reference...

![image](https://cloud.githubusercontent.com/assets/11527994/16812714/36aca310-48e3-11e6-80ee-e53ee9aef730.png)

**Comment by alexshepard** [comment]
Should be fixed in the current TestFlight build.
