### ISSUE TITLE
Edit Observation Default Photo Button Padding

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#298]
Currently there isn't ample space around the default button and I find myself tapping the thumbnail as opposed to the radio button. See screenshots below...

### Current

![image](https://cloud.githubusercontent.com/assets/11527994/16817768/3888fc9a-48f9-11e6-8d29-0843bfcdf1d9.png)

### Proposed

![image](https://cloud.githubusercontent.com/assets/11527994/16817782/4a870aea-48f9-11e6-8ecc-3385c1a326cb.png)

### Current

![image](https://cloud.githubusercontent.com/assets/11527994/16817849/a4ba8d84-48f9-11e6-8b65-159994e00438.png)

### Proposed

![image](https://cloud.githubusercontent.com/assets/11527994/16817799/67875320-48f9-11e6-9dac-5ad301315194.png)

**Comment by alexshepard** [comment]
Works for me. Glad to see this revisited, thanks!

**Comment by alexshepard** [comment]
done in ce0ec408d2e44b40947051e71bcda034d59da506
