### ISSUE TITLE
Uninitiated "Deletes to sync" in build 340

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#299]
I downloaded the latest build from TestFlight, and when I opened the app, it popped up with the "deletes to sync" message that has deleted my observations in the past. Once again my phone is pretty full. Last night I added 50+ observations on the website and 2 on the app. I can't seem to find the issue from last October when I first noticed it (maybe I only posted to the Google Group?). 

Do you want me to test this and see what it deletes for troubleshooting purposes? If it's any of the most recent 100 I can just re-enter them, but if it does anything older than that will you restore from a cache because in that case I won't easily be able to find what was deleted.

My biggest concern about this issue is that if it is also happening when someone has auto upload then it might be syncing deletes without any warning at all.

![2016-07-18 09 32 54](https://cloud.githubusercontent.com/assets/7501183/16916745/7fa148ea-4ccc-11e6-866e-92a8e49d42e6.png)

**Comment by alexshepard** [comment]
Hi Carrie,

Is there any chance you deleted an observation on the web in the last day?

That (1) above the Me indicates that only a single observation is pending delete sync. I think there's a bug where notifications to the app from the server about stuff deleted on the server can get the app confused such that it thinks those deletes now need to be synced/uploaded to the server. I have a fix that I'm working through now.

**Comment by carrieseltzer** [comment]
Ooh yes. I did upload a batch and then delete one. That might be it!

**Comment by alexshepard** [comment]
Thanks! Did you upload the batch from the web app or from mobile? And did you delete that one on mobile or the web app?

**Comment by alexshepard** [comment]
Should be fixed in 99b5d25dc6cca9ca952a88e7949c08a047fe52a2 

This will be in build 342.
Thanks for the report!

**Comment by carrieseltzer** [comment]
Sorry I missed those clarification questions last night. I used the website
uploader for 50+, added two more on mobile, then deleted one on the website
that I had uploaded on the website.

I deleted the app (to escape the deletes to sync) and installed build 343
from Test Flight.

**Comment by carrieseltzer** [comment]
Ok. I deleted an observation on the website then pulled down to refresh the
app. My number of observervations decreased by one without giving the
"deletes to sync" message. I think it's set!

**Comment by carrieseltzer** [comment]
I've gotten the "deletes to sync" message again twice in the last few days using build 343 (auto upload is turned off). The first time I couldn't remember if I'd deleted something on the website (probably), but when I got it just now I definitely had deleted 2 observations on the website that I had uploaded on the website. They are already gone from my list in the app though. As long as it isn't actually deleting anything this probably is fine, but I wanted to let you know it's still happening.

**Comment by alexshepard** [comment]
Ok, thanks for the heads up, I'll take another look today!

**Comment by alexshepard** [comment]
Another tweak to fix this, in 3acfaa933b2f065ace5977d299251bcd31756166, will be in the next build (344)

**Comment by alexshepard** [comment]
@carrieseltzer have you seen this in the last few builds? happy to keep this bug open for a while to make sure it's truly squashed, but I'll keep it on the back burner unless it's still happening for you.

**Comment by carrieseltzer** [comment]
I'll keep an eye out and try to test it as well with the conditions known to trigger it before. Thanks!

**Comment by alexshepard** [comment]
thanks!

**Comment by alexshepard** [comment]
@carrieseltzer can you re-open if you're still seeing this?
