### ISSUE TITLE
Me Screen Quick Clean Up

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#301]
I realize we're revamping the Me tab at some point, but it could really benefit from some housekeeping in order to look consistent with the rest of the app. ...that is if we all agree and these are quick and easy changes. @loarie @kueda @alexshepard 

The right screenshot has the proposed changes.

![image](https://cloud.githubusercontent.com/assets/11527994/16959542/7927545e-4d9a-11e6-9ebc-702bcd45251f.png)

Here's a list of the changes in order of priority:

1. Scooch thumbnails to right 11 so they line up with the divider lines
1. Use regular weight font for ob name (Bold is typically used to indicate unread)
1. Scooch right-hand side elements such as the time and activity notification to the left so there is a 
1. Give the profile pic a left margin of 16pt. The spacing between the profile pic and ob count is fine. If this is difficult due to the sync progress notifications, we don't have to do it.  
1. 6pt margin on the right (see below margin diagram for visual reference
1. Give thumbnails 1pt radius and 1pt border of #C8C7CC
1. Move activity notification chat bubble icon up 4pt.

Note: Let me know if the border around the thumbnail is an issue for iconic taxa. Will they be able to to be centered with ample padding?

Here's some red lining to illustrate the margins:

![image](https://cloud.githubusercontent.com/assets/11527994/16959826/b0eaa2aa-4d9b-11e6-8fd9-80d5c047cb69.png)

**Comment by alexshepard** [comment]
Looks great. Any advice on handling these other states?

![image](https://cloud.githubusercontent.com/assets/515947/16961641/414f38d6-4da3-11e6-9a23-7c9705c7c642.png)

**Comment by joellebel** [comment]
Yes. 

* Cell bg colors stay the same, but overall screens margins and text weights should get the new treatment. 
* The header animation stays the same just with the new margins. 

Also, forgot to mention earlier... I wanted to bring up these quick fixes before tackling/moving forward with issue: https://github.com/inaturalist/INaturalistIOS/issues/288 Will these changes make issue #288 harder more cumbersome, if we decide to move forward with them?

**Comment by alexshepard** [comment]
Thanks for the advice.

No worries about interaction with issue #288. Do you want to move forward with it? If so, what direction?

**Comment by joellebel** [comment]
Just double checking... Are you asking if I want to move forward with #288 or this issue. The answer would be both. However, if issue #288 is over time consuming, issue #288 can certainly come down the road.

**Comment by alexshepard** [comment]
I was asking about #288.

**Comment by alexshepard** [comment]
Can you finish your thought for item 3? Looks like the text got cut off.

**Comment by alexshepard** [comment]
For item 5, do you mean a right margin of 16pts? Because that's the width of all the left margins, and in the visual reference they look the same width.

**Comment by alexshepard** [comment]
Aside from what's in item 3, and assuming you meant 16pts for item 5, this is in 6a142e4a6548ed66d98377f77a40158681d2fbb6 which will be in the next (346) build.

**Comment by joellebel** [comment]
Awesome. Yes, I meant 16pts for item 5. tnx!


Whoops My apologies...

> Scooch right-hand side elements such as the time and activity notification to the left so there is a

Should be... "Scooch right-hand side elements such as the time and activity notification to the left so there is a 16pt margin on the right"

**Comment by alexshepard** [comment]
OK, I think this is all done in the build that's in review at Apple. It'll be available on TestFlight this afternoon or tomorrow morning.

Is there any way we can tone down the inactive chatboxes? Now that the rest of the screen is pretty subtle, the row of black on white icons on the right are the highest contrast items on the screen and they draw my attention away from the photos and the text. That's my opinion anyways. ;)

**Comment by alexshepard** [comment]
![image](https://cloud.githubusercontent.com/assets/515947/17232289/d06319c2-54db-11e6-9803-267c8a70026e.png)

**Comment by joellebel** [comment]
Fabulous. Love the profile pic too ;)

**Comment by alexshepard** [comment]
You can change it in the app now!

(In this upcoming release)

**Comment by joellebel** [comment]
tested the profile pic changing feature and it worked for me.
