### ISSUE TITLE
Proposal for Uploading Cloud Icon

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#315]
@alexshepard I agree the cloud icon should not be green while uploading. However, a sudden disappearance of ui elements can seem like something is wrong. Typically I don't like to remove ui elements, but rather change their state to match the operation so the user is better informed. I would recommend making the cloud icons the same gray as the text in the rest of the cell. 

Here's some screenshots below to show the contrast in the current state change.

![image](https://cloud.githubusercontent.com/assets/11527994/17409961/64fa94c6-5a26-11e6-8c53-a7e13dbb15b9.png)

**Comment by alexshepard** [comment]
> However, a sudden disappearance of ui elements can seem like something is wrong

When you go from not uploading to uploading to finished uploading, UI elements (the upload button, the progress bar, the date and comment labels) appear and disappear alongside color changes as the observation behind a row transitions from one state to the next. 

So I don't really understand this explanation. However, I'm fine putting the icons back and changing them to a gray if that's your preference.

**Comment by joellebel** [comment]
> However, a sudden disappearance of ui elements can seem like something is wrong
>> When you go from not uploading to uploading to finished uploading, UI elements (the upload button, the progress bar, the date and comment labels) appear and disappear alongside color changes as the observation behind a row transitions from one state to the next.

>> So I don't really understand this explanation. However, I'm fine putting the icons back and changing them to a gray if that's your preference.

IMO those elements aren't really disappearing though. They're just being replaced/changed with others to indicate where the app is at in a process. Also, the rest of the elements in the cell are disabled so in my opinion it would be consistent with the logic of the rest of the elements.

**Comment by alexshepard** [comment]
uploading buttons show during upload session, but are disabled gray in 8cee65d97afd327077ecc72b39a8132cdf7ff55f
