### ISSUE TITLE
 projects API calls might not be sending a language

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#317]
Here are screenshots with both the device and inat account local set to Korean:
![img_7222_720](https://cloud.githubusercontent.com/assets/598026/17450020/95b39ab6-5b90-11e6-9048-a27a3bedef64.jpg)
![img_7221_720](https://cloud.githubusercontent.com/assets/598026/17450021/98860832-5b90-11e6-8931-cb81576542ca.jpg)
![img_7220_720](https://cloud.githubusercontent.com/assets/598026/17450024/99ad6b92-5b90-11e6-90a8-8948cceb6b53.jpg)

**Comment by alexshepard** [comment]
Should be fixed in 9d978ae38167610fc091eeeb95cba9f9e2a30e12
