### ISSUE TITLE
Taxon selector only displaying limited subset of options 

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/INaturalistIOS#318]
I searched for "polygonum" and the genus was not an option nor were most of the species.

Trying to add a screenshot but not sure if possible from iPhone.

**Comment by naturalistcharlie** [comment]
![image](https://cloud.githubusercontent.com/assets/7171475/17451045/d9816732-5b31-11e6-8ea0-9fab982f4dd8.png)

**Comment by naturalistcharlie** [comment]
Those you can see were the only options.

**Comment by alexshepard** [comment]
An initial attempt at this is in c77287f6677bc06b9158a0a8efddc8403cb3a3e5

**Comment by alexshepard** [comment]
We don't have room for showing the matched term like on the web, so the matched term is not displayed, but the results should be there.

**Comment by alexshepard** [comment]
Updated sorting in 939b7e43c9b3579296d7d606407924b869d02833
