### ISSUE TITLE
coordinates reset after choosing location

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#327]
1. Start a new observation, let the coordinates get set
2. Tap the location to bring up the map viewer and choose a different location. Save.
3. Coordinates on the obs form are the same as before. Sometimes the place guess changes, sometimes not.

For me this is only happening when creating a new obs, not when editing an existing one. Version 2.6.17, build 357.

**Comment by alexshepard** [comment]
I think this is related to the comment that @Dunnart-at-large made in #262

**Comment by kueda** [comment]
Fixed in build 425.
