### ISSUE TITLE
Black Background Missing to Top Bar of Photo Capture Screen

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#330]
On iPhone 7 the black bg is missing to the top bar on the photo capture screen. My iphone 5 is at the office so I can't test that at the moment. 

![image](https://cloud.githubusercontent.com/assets/11527994/19255299/5433d6fa-8f11-11e6-8593-16bd0c43cac5.png)

**Comment by alexshepard** [comment]
apparently Apple fixed in this 10.2 beta

**Comment by joellebel** [comment]
sweet!

**Comment by joellebel** [comment]
shall we close this issue?

**Comment by alexshepard** [comment]
Let's wait until we know it's fixed and released.

**Comment by kueda** [comment]
Pretty sure this is fixed as of build 425.
