### ISSUE TITLE
Loading Observation Images on Observation Detail Screen States

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#331]
# Loading State
- The spinner is the default iOS spinner.

![image](https://cloud.githubusercontent.com/assets/11527994/19278023/ab528416-8f90-11e6-80f3-82424590b67d.png)
# Cannot Load Image State
- Direction A and B use a blurred version of the low rez image with messaging superimposed over it. 
- Direction C is showing a low rez version of the image which would be hard to tell exactly how it's going to look and feel without seeing it on the phone. I'm open to this idea, but it could leave the user wondering why the image looks so bad. We could superimpose some messaging over this photo about its state, I guess (but might be overkill).

![image](https://cloud.githubusercontent.com/assets/11527994/19278705/341b3584-8f93-11e6-82d0-0cb628284410.png)

Question: Maybe we don't want to mention connectivity because that might not be the problem?
### Alternative Text for Messaging

Feel free to add your own...
- No Connectivity (Cannot Download Image)

Once we're good to go, I'll make some styling specs.

**Comment by alexshepard** [comment]
It looks like the loading state shows a spinner on top of a blurred version of the low res file. 

Why wouldn't we just just the low res file while the high res file is loading, potentially with a spinner on top?

The low res file _might_ be useful or helpful to the user. The blurred version is definitely not.

**Comment by joellebel** [comment]
That's fine. I really wasn't sure all the details around the low rez version. For example, will we always have a low rez version? Is it possible to make a demo of this?

**Comment by joellebel** [comment]
...by demo, I meant can we implement the above idea you proposed? (Why wouldn't we just just the low res file while the high res file is loading, potentially with a spinner on top?)

**Comment by joellebel** [comment]
...my only concern is that you might not be able to see the spinner but we can give the spinner a background or something.

**Comment by alexshepard** [comment]
If the network hasn't been able to load the small image, then we won't be able to display it, sure. 

But if we have the small image, I don't think it's helpful to blur it.

**Comment by joellebel** [comment]
> If the network hasn't been able to load the small image, then we won't be able to display it, sure.

Ok. So that's when folks would get the "Unable to load image" state, right?



> But if we have the small image, I don't think it's helpful to blur it.

Ok. I have a feeling it's going to look a little unpolished which is why many apps blur it (like instagram)... but let's see how it looks.

**Comment by alexshepard** [comment]
Huh, I don't see any blurring of photos in Instagram.

Also, even if they do, Instagram is _about_ photos, so pixelated photos make the platform look bad. On iNat, I think even bad or blurry photos are still informational and diagnostic.

![img_1266](https://cloud.githubusercontent.com/assets/515947/19287982/e3146338-8fb8-11e6-8ab4-a019656bd02a.PNG)
![img_1269](https://cloud.githubusercontent.com/assets/515947/19287983/e316ab02-8fb8-11e6-8be2-cc1ed842a4a5.PNG)

**Comment by joellebel** [comment]
This is what I see... (Left is loading; Right is no connectivity)

![image](https://cloud.githubusercontent.com/assets/11527994/19292028/e6af6e1a-8fcd-11e6-9d5b-1480231ac135.png)

Which reminds me, @alexshepard @kueda do we want to put a button in there like the above righthand screen which allows the user to re-attempt a download? ...or is that just kinda futile because users won't be able to download it anyways? 

@alexshepard I'm going to hop on other things now. Don't have a huge opinion either way at the moment. Just interested in seeing what the low rez version implementation looks like.

**Comment by alexshepard** [comment]
Can I mark this as finished?

**Comment by joellebel** [comment]
yass
