### ISSUE TITLE
FB Sign Up: Enter Username Screen

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#332]
See below Enter Username interstitial screen options. 

Note: The screen you see after this flow would either be the Settings screen (if you came from there) or the Me screen in the case of an initial launch. 
# Dir. A

![image](https://cloud.githubusercontent.com/assets/11527994/19396222/e619da50-91f6-11e6-812b-5a4b004b0b6d.png)
# Dir. B

![image](https://cloud.githubusercontent.com/assets/11527994/19396239/f824149a-91f6-11e6-9e4a-cc23c10479c8.png)
# Dir. C

![image](https://cloud.githubusercontent.com/assets/11527994/19396263/1b78596a-91f7-11e6-85c5-199a7da80d82.png)
# Conclusion

I think I like C the best because it's the simplest, but realize it might require a little more work because of the alterations to the input field. Don't have a huge preference here. 

@alexshepard Please let me know if I'm leaving anything out.

**Comment by alexshepard** [comment]
We can show them the username that the server has generated for them at this point.

**Comment by joellebel** [comment]
Oh. Ok. Will design a rendition of that for comparison. Also, I will make any of these designs work for all iphones. Just wanted to get the layout and content down first.

**Comment by joellebel** [comment]
I made sure to leave enough room under the "Otherwise, your username will be: Joelle3629" in case the username goes to two lines.

![image](https://cloud.githubusercontent.com/assets/11527994/19405096/c9a26716-9228-11e6-9dff-982a3d60103f.png)

**Comment by joellebel** [comment]
# iPhone 4 Design

All content, font sizes and spacing within the content is the same on both phones. Just wanted to show how they look. 
![image](https://cloud.githubusercontent.com/assets/11527994/19653392/400774c6-99c9-11e6-9607-d195a0fd30fb.png)



## With Guides

It would be nice if the content could be vertically middle-aligned on all phone sizes, but if not, no biggie. 

![image](https://cloud.githubusercontent.com/assets/11527994/19653354/12eb1038-99c9-11e6-8554-eeb570e7b009.png)

**Comment by kueda** [comment]
Personally I think this is unnecessary. People can do this in the app now if they want to from the Settings screen. Can we close?

**Comment by joellebel** [comment]
Yes, I do, but lower priority. People don't think to go to settings. We could hold off until we redo the me section, I guess? Sounds like there's a lot or other open issues. Okeedoke.
