### ISSUE TITLE
Feature request: app setting for default Geo Privacy

### ISSUE THREAD

**Issue by englishm** [inaturalist/INaturalistIOS#333]
I like to upload all of my observations with Geo Privacy set to Obscured, but it can be easy to forget and expose exact location data unintentionally, especially for new users.

It would be nice to have an app setting to change the default Geo Privacy setting for new observations from Open to Obscured.

**Comment by kueda** [comment]
People ask for this from time to time. First, if we do this, I think I'd prefer to make it a preference that you can set on the web first and it would affect all your observations made from that point on, from any platform. Second, it's kind opposed to our mission to share information, though I toptally understand the backyard use case. Why don't you post this to the Google Group and see if there are any other people interested in it, and if so we might try it out the web first. For now I'm going to close this, though, b/c I'd rather not see it as a setting in the apps just yet.
