### ISSUE TITLE
Issues with camera in ios10

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#336]
- [ ] Photo Capture: Top bar missing black bg and extra black above photo capture button during photo capture. See screenshot below. (Found in build 386)
![image](https://cloud.githubusercontent.com/assets/11527994/20253263/c23597b4-a9de-11e6-9bd8-bfbd4a673db5.png)

**Comment by alexshepard** [comment]
For reference, this start appearing in iOS 10 and was independent of any changes in code in iNat.

**Comment by alexshepard** [comment]
This was already reported in #330
