### ISSUE TITLE
support iCloud photos in the photo chooser

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#337]
Currently we don't, which is severely limiting for people who don't have much remaining storage space on their devices because iOS automatically moves photos to iCloud to save space when you're running out of disk. As a result, these users only see a handful of their photos when they're trying to import pics to iNat. This has been a recurring support issue for 5-6 months.

The path to accomplishing this is long and twisted, like coyote poop. Modern 3rd party photo choosing libs mostly rely on Swift or other more modern libraries, but we can't incorporate them *and* continue to use Restkit, a vestige of a bygone era. We've been slowly moving away from Restkit and toward Realm, but it's never really been a priority. So the path to choosing photos from iCloud looks sort of like

1. Completely remove RestKit and transition to Realm
1. Choose a 3rd party photo chooser that meets design requirements, may need a new design for incorporating it into our observation flow
1. Add the 3rd party lib we choose

Questions:

1. We're using a 3rd party lib for the camera right now, but is that also the same as the photo chooser? Can we keep the same camera lib but just use a new photo chooser? Isn't the photo chooser button we're using right firing some kind of custom action anyway?
1. Realm transition deserves an issue of it's own, but roughly, what are the steps to getting there?

**Comment by alexshepard** [comment]
Done in release 2.6.21
