### ISSUE TITLE
App Immediately Asks for Notifications Permissions

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#338]
Just to recount...

The app currently asks the user for notifications permissions at first launch immediately after installation. (like it's the first thing they see.)

Sounds like @alexshepard is going to look into this. Then get back to me so I've assigned this issue to both @alexshepard and myself. Once Alex checks it out, I think we should look into whether or not we need it, a better place to make it appear and perhaps more tailored text about iNat notifications.

**Comment by alexshepard** [comment]
Gone in 2.6.20.
