### ISSUE TITLE
Reordering of photos not working in Ob Detail Edit screen

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#339]
I go into the edit screen of an ob detail, re-order the photos by tapping the radio buttons below the thumbnails and tap Done. When the ob detail is displayed, the photos are not in the new prescribed order. 

Let me know if you have any questions.

**Comment by alexshepard** [comment]
Is this a duplicate of https://github.com/inaturalist/INaturalistIOS/issues/255?

-alex

**Comment by joellebel** [comment]
Oh look at that. 'tis. I shall close.
