### ISSUE TITLE
Can't enter time field for projects

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#340]
A user says he can't enter the "time of sighting" field when trying to add a project to the Milwaukee County Coyote Watch project, using iOS version 2.6.20, build 395. I was able to reproduce the issue on my iPhone 7. That field doesn't look like the other fields (which work), and when you tap on it it just turns grey and the observation can't be submitted to the project. 

![img_4886](https://cloud.githubusercontent.com/assets/15896181/20915269/a7863826-bb39-11e6-96db-e0eb89361b18.PNG)

**Comment by alexshepard** [comment]
OK, I think I have this settled, and it should be fixed in the next build. However, I feel that an observation field like "time of sighting" misuses the project observation fields considering that the observation itself has an attached date and time.

**Comment by alexshepard** [comment]
fixed in 13f64a2ed955f99f971188decfd93af9294db140

**Comment by tiwane** [comment]
Agreed.
