### ISSUE TITLE
Can't enter decimal point in numerical keypad for numerical project field

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#341]
When entering a project field that asks for numerical data, the numerical keypad pops up, but the keypad doesn't have a decimal point key, which makes it hard to entire precise data.

![img_4890](https://cloud.githubusercontent.com/assets/15896181/20955420/05c6e0fc-bbf8-11e6-890b-cbac8788625d.PNG)

**Comment by tiwane** [comment]
Here's another project observation field where this is happening: 

![image1](https://cloud.githubusercontent.com/assets/15896181/25204611/328bf1ac-2513-11e7-9bf2-fe0389945087.PNG)

**Comment by alexshepard** [comment]
we need to switch to using `UIKeyboardTypeDecimalPad`

**Comment by alexshepard** [comment]
should be fixed in 43cb24cecc388cc8983f79a75c66517c34f7bcaa

**Comment by alexshepard** [comment]
@tiwane is this safe to close?

**Comment by tiwane** [comment]
Yup, looking good to me in 2.7 (455). thanks!
