### ISSUE TITLE
show taxon.name instead of species_guess in explore

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#342]
I was watching C use the most recent App Store build the other day and she was confused by the discrepancy in names, which I'm *pretty* sure was due to the ol' `species_guess` / `taxon.name` issues. We show taxon.name pretty much everywhere else, so if we're still using `species_guess` in Explore, we should switch to `taxon.name`. I guess what we do else where is something like `taxon ? taxon.name : species_guess`.

**Comment by alexshepard** [comment]
I'm assuming you mean the explore grid view?  

Fixes with a preferred order: common name -> scientific name -> species guess in explore grid view and project details observation list are in build 403, which just went out to testflight.

If you meant something else, let me know.

**Comment by kueda** [comment]
You assume correctly. Thanks! Fixed in build 403.
