### ISSUE TITLE
Unable to change Profile Pic in iOS

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#343]
Tapping on my profile pic and uploading a new pic (either immediately or after removing my current profile pic) just brings back my original profile pic. Original profile pic is visible when I check in the browser as well.

**Comment by pleary** [comment]
likely caused by inaturalist/inaturalist#1229

**Comment by tiwane** [comment]
ah yes. the profile pic did eventually change when i logged-on later.

**Comment by alexshepard** [comment]
does it change in the app after a few hours as well?

**Comment by alexshepard** [comment]
is this still happening @tiwane ?

**Comment by kueda** [comment]
This isn't an iOS issue, I think.
