### ISSUE TITLE
Photos taken within app do not have metadata when saved to phone

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#344]
When taking a photo in the app, the photo that's saved to the Library is lacking a lot of metadata, including location.

version 2.6.22, build 403

**Comment by naturalistmellis** [comment]
I think this should be marked as 'bugs' rather than 'enhancement'.

**Comment by alexshepard** [comment]
fixed in f4b36c4bd9352153fcf6432c15ea7ea0bf180bc7 and released in 2.7.3
