### ISSUE TITLE
app badge doesn't reflect uploads or updates

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#349]
Used to be that the app badge showed the number of observations you needed to upload. As of build 403, I'm not sure what it's showing. Yesterday I uploaded 20+ observations successfully. Today the badge says "18". When I uninstall the app and reinstall it and sign in as a different user, it still says 18. I thought maybe it was showing me the number of unread updates from the Activity tab, but it doesn't look like it. 

I propose that we return to showing the number of un-uploaded observations in the app badge. If that's impossible for some reason, I recommend just removing the badge.

**Comment by alexshepard** [comment]
Hm, I think as part of the activity stuff going in, we removed the app badging. I don't see badges myself anymore. 

So either something in the app is still applying the badge, or a previous version of the app set the badge state to 18 and the app now can't clear it. You might think that deleting and re-installing the app would clear the badge, but a lot of stuff is persisted across deletions, including things like privacy permission and such.

I'll take a look.

**Comment by alexshepard** [comment]
Maybe ask apple support about this, or in the Apple support forums.

**Comment by alexshepard** [comment]
If nothing else, we can turn this back on for un-uploaded observations.
