### ISSUE TITLE
Change "login has already been taken" error message

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#354]
A user wrote in, confused by the "login has already been taken" error message, saying he had never signed up for an iNat account before. He believed that the error message referred to his email address/password, and not username. 

Can we change the error message to "Username has already been taken"?

**Comment by alexshepard** [comment]
That message comes to mobile from the server, can you make this issue on the repo at http://github.com/inaturalist/inaturalist ?

**Comment by kueda** [comment]
Closing in favor of https://github.com/inaturalist/inaturalist/issues/1357

**Comment by GaneshKalumbe** [comment]
I am not able to change name of Organization
getting same error

**Comment by kueda** [comment]
This isn't really an error in the code, it's a validation error. If the username you're choosing has already been taken, you need to try a different username.

**Comment by GaneshKalumbe** [comment]
same error on delete also.

**Comment by idbjava** [comment]
same with me

**Comment by ViksYelapale** [comment]
Same issue.

**Comment by demonzoo** [comment]
> I am not able to change name of Organization
> getting same error

It means your target organization name has been taken by someone else. Try another name.

**Comment by hoangtranson** [comment]
`Login is already taken` still get this message. I think this mean that  org name is already taken.
