### ISSUE TITLE
IOS app crashing frequently when creating new observation

### ISSUE THREAD

**Issue by dmcglinn** [inaturalist/INaturalistIOS#355]
I haven't found a clear pattern to the crashes but they tend to occur when editing the metadata around an observation such as adding notes or modifying the placement of the observation on the map.

**Comment by alexshepard** [comment]
@dmcglinn the latest release (2.6.25, just out a few hours ago) has a bunch of crash fixes. can you upgrade to that?

**Comment by alexshepard** [comment]
@dmcglinn can you re-open if you're still having problems? thanks!
