### ISSUE TITLE
Species name click to optionally link to map of species observations

### ISSUE THREAD

**Issue by dmcglinn** [inaturalist/INaturalistIOS#356]
Currently when you click a species name in the app it provides info from Wikipedia which is nice but it would be great to have another option to see a map of that taxon's records with the current observation colored differently so it would be clear how it fits into the context of the species' range.

**Comment by alexshepard** [comment]
we've been thinking about this as an enhanced taxon page, that includes things like links to other observations, range maps, more photos, etc.  something like this: 
http://www.inaturalist.org/taxa/56617-Ceanothus-thyrsiflorus

does that roughly meet your expectations, @dmcglinn?

**Comment by kueda** [comment]
Yeah, this would be a part of a taxon page, which is in the pipeline.
