### ISSUE TITLE
Landscape Mode Tabs Incorrectly Showing in Activity Tab

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#358]
I opened the Activity section to find the tabs were still in landscape mode. To my knowledge I had not put the phone in landscape mode during that testing session. I then put the phone in landscape and back to portrait and the problem was fixed.

Build 416 - iphone 7

![image](https://cloud.githubusercontent.com/assets/11527994/25411803/bed3934e-29d3-11e7-85b9-8d3ed33fa55e.png)

I have not been able to reproduce the and I have not seen the problem in build 417.

**Comment by alexshepard** [comment]
i'm unable to reproduce this.

**Comment by joellebel** [comment]
Me too. Hasta la vista!
