### ISSUE TITLE
Flickering Map Marker on Ob Detail Map

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#359]
In the latest testflight build and previous testflight build… when I scroll up and down on an ob detail (info tab) it’s kinda jumpy and the location map marker disappears and reappears. It kinda seems like the faster I scroll the more it happens, but hard to tell. 

Here's a link to our dialogue on slack if needed (Patrick mentioned he saw it too): https://inaturalist.slack.com/archives/C02F8RN5Q/p1492631398124260

**Comment by alexshepard** [comment]
the newer testflight builds should make this a lot better, but it will still happen when you first click into an observation as we reload all of the metadata from the server. once we're migrated to the node api, which will let us request full observations, this will be less of a problem.

**Comment by alexshepard** [comment]
we may be able to avoid reloading the map row if the observation location hasn't changed upon refresh?

**Comment by alexshepard** [comment]
it looks like multiple flickers (observation reloads) can happen if you put the phone to sleep and then wake up on an observation detail screen.

**Comment by joellebel** [comment]
Ok. Will test the latest build.

**Comment by alexshepard** [comment]
Should be fixed as of 397fda3294874136edae0123818b4549ee12dcc8

**Comment by alexshepard** [comment]
Fixed in 2.6.26
