### ISSUE TITLE
multiple project taxon rules don't show on about page

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#360]
http://www.inaturalist.org/projects/test-project-of-unfathomable-awesomeness currently has two rules:

1. must be in taxon Amphibia
1. must be in taxon Reptilia

However, the "About" section of the project view in the iPhone app only shows one of those rules:

![photo apr 27 12 00 09 pm](https://cloud.githubusercontent.com/assets/22691/25499772/6a14e528-2b41-11e7-960d-47be2dffeeb1.png)

I think it might just not be showing more than the first rule, b/c it looks the same when I add more rules.

**Comment by alexshepard** [comment]
should be fixed in 37ea1e79baac952f780b01eee559edf74589b29a

**Comment by kueda** [comment]
Fixed as of build 425.
