### ISSUE TITLE
Serious location accuracy error for photoless observations

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#370]
Ver 2.6.25, build 425

Make a new observation without a photo.
Tap to edit location.
Zoom out way beyond city level.
Save, then watch accuracy return to 5 m (even though your circle on the map was huge).

I tested this with photos and it seems ok, so it this problem seems unique to photoless observations.

**Comment by alexshepard** [comment]
part of what's happening here is that we're continuing to query your current location even after you've set the location via the edit location/map UI, which is a bug.

**Comment by alexshepard** [comment]
should be fixed in 593378fc11c58c1d75461f4d783c88bfb41ba565

**Comment by alexshepard** [comment]
Fixed in 2.6.26
