### ISSUE TITLE
Raise Tab Icons on Ob Detail Screen

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#382]
Ok. Would love to raise the tab icons 6pts. They've always been a little too low IMO. This will hopefully insure a nicely cushioned, tappable area. See below...

![image](https://cloud.githubusercontent.com/assets/11527994/26258389/67075ae8-3c79-11e7-8c0a-f266c18512dc.png)

Let me know how you would like to proceed. I can close this issue and make a new one if that's better. I realize this is a very old issue.

**Comment by alexshepard** [comment]
Fixed in 2.6.26
