### ISSUE TITLE
The "Forgot?" link disappears if one enters the wrong password

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#383]
Not sure if this is a bug or a design issue. Regardless, someone in Texas was having a difficult time figuring out how to request a password reset via her app and I watched her get this series (and I can replicate it with newest TestFlight). I think this may be why some folks are emailing us about this.

1. Enter your username and (incorrect) password and sign in.
![img_6532](https://cloud.githubusercontent.com/assets/15896181/26532243/9c0b4414-43b0-11e7-9017-20918e20dea9.PNG)

2. Pop-up alert tells you it's wrong username or password. Note that the "Forgot?" link shows up when the alert is on screen.
![img_6533](https://cloud.githubusercontent.com/assets/15896181/26532245/a09843e2-43b0-11e7-9aa5-d481a897f0a2.PNG)

3. If you tap "OK" the login screen returns but the Password form still has dots in it and the "Forgot?" link disappears. 

![img_6534](https://cloud.githubusercontent.com/assets/15896181/26532246/a8102c70-43b0-11e7-92fe-717c49f92b77.PNG)

The "Forgot?" link should stay there once you tap OK on the alert. Preferably (I think) with the password dots filled in, but that's not necessary.

**Comment by alexshepard** [comment]
I'm just going to clear that password field after login failure, which will show the Forgot button. This is pretty common approach.

**Comment by joellebel** [comment]
Works for me. Most apps don't clear the field after you get the error messaging, but that's because they have a separate "Forgot your password?" link outside of the field. I say let's do as Alex prescribed. If that doesn't work, we can do something more showy like a "Did you forget your password?" link under the Login button.

**Comment by alexshepard** [comment]
Fixed in 2.6.26
