### ISSUE TITLE
Bug in activity feed - photos repeated

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#391]
I haven't been able to replicate, but user 9950, on 2.6.26, build 437, shared a screenshot showing photos in the activity feed being repeated, but for different observations: 
![image2 1](https://user-images.githubusercontent.com/15896181/27442757-f25faf70-5725-11e7-9859-f9b51a69f432.PNG)

**Comment by alexshepard** [comment]
fixed in 2d5f55c

**Comment by alexshepard** [comment]
Released in 2.7
