### ISSUE TITLE
Missing Taxon Thumbnail

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#394]
I think there may be a problem with taxa that don't have a default photo. This is what happens after i select Brown Recluse from Suggestions...

![image](https://user-images.githubusercontent.com/11527994/27609708-94d619a6-5b40-11e7-8086-9c8beb3eeabb.png)

![image](https://user-images.githubusercontent.com/11527994/27609671-745e518e-5b40-11e7-8a3f-73e2908a056e.png)

Here's the image that gave me the problems. Note: Brown recluse doesn't have a default photo. 

![image uploaded from ios](https://user-images.githubusercontent.com/11527994/27609682-7cc7c4cc-5b40-11e7-94dd-b975f192d7b1.jpg)

Hard to reproduce this because I need to make an ob of a taxon with no default photo, I think.

**Comment by alexshepard** [comment]
Brown recluse does have a default photo:
https://www.inaturalist.org/taxa/50181-Loxosceles-reclusa

But iOS doesn't seem to want to display it.

**Comment by joellebel** [comment]
Ok. Thanks for the follow up. Guess I found some weird edge case. I'll let you know if it's happened with any others.

**Comment by joellebel** [comment]
Haven't run into this problem anymore so I'm closing this issue.
