### ISSUE TITLE
location editor does not show existing coordinates on first edit

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#4]
Worst kind of bug: the intermittent kind. Sometimes when you tap "Edit location" while editing an observation with coordinates the map zooms to 30,40 or something, instead of the coordinates. Canceling and editing again seems to show the coordinates correctly. Will try to grab a screenshot the next time it happens.

**Comment by alexshepard** [comment]
Is this still happening?

**Comment by kueda** [comment]
Not as far as I can tell, and I have no heard any support requests related to this recently. Closing for now.
