### ISSUE TITLE
Credit specific users in vision results

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#400]
Currently we show a nice message at the bottom of our vision suggestions:

> Suggestions based on observations and identifications provided by the iNaturalist community.

We've talked about adding some actual names to that, so it might say

> Suggestions based on observations and identifications provided by the iNaturalist community, including Greg Lasley, Susan Hewitt, paloma, and many others.

So let's do it! Initially, let's just take the list of suggested taxon IDs and grab the top 3 observers or the top identifiers (can choose which one randomly), e.g.

http://api.inaturalist.org/v1/observations/observers?taxon_id=58421,486453,53809,61881,157990
http://api.inaturalist.org/v1/observations/identifiers?taxon_id=58421,486453,53809,61881,157990

If that works, great. If it's kind of slow, we can try putting together an endpoint that aggregates over a smaller set of observations, like the latest 1000 or something. You could also localize it to place, but I don't really think that's necessary, since theoretically people who identified or observed the relevant taxa anywhere helped train the model.

It would be great to link to user profiles, but since we don't have those in the iPhone app, maybe hold off until we do? We could also link to their profiles on the website, not sure if that's weird.

**Comment by alexshepard** [comment]
done in 2.7.1
