### ISSUE TITLE
Color tweak to loader in suggestions

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#404]
Don’t mind the fact that my loader is different from the standard one. I want to use the standard one. I just want to change it and the text to #8E8E93 and make the bg of the screen the same used for when there are suggestions

![image](https://user-images.githubusercontent.com/11527994/29056366-65f1b1bc-7bb7-11e7-93ab-63cc99f0d90d.png)

**Comment by alexshepard** [comment]
done in 2.7.1
