### ISSUE TITLE
Suggest an ID Comment Screen Fixes

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#407]
@alexshepard Before writing up the fixes, I was wondering if it's relatively easy to make the "Identification Taxon" field on the Add Identification screen look and act like the species field on the edit/conf screen. This would be the most consistent. See below screenshots of the two for reference. 

## Edit/Conf. Screen
![image](https://user-images.githubusercontent.com/11527994/29205521-5352e152-7e32-11e7-96e0-7e5604f339cb.png)

## Add Identification Screen
![image](https://user-images.githubusercontent.com/11527994/29205546-77064ef4-7e32-11e7-973c-986f70ed22b1.png)

**Comment by alexshepard** [comment]
Yep that will be do-able.

**Comment by joellebel** [comment]
Ok. Great. Stay tuned!

**Comment by joellebel** [comment]
# Proposed Changes

* Make the "Identification Taxon" field on the Add Identification screen look and act like the species field on the edit/conf screen.  Please include the top and bottom gray border for the cell we use on the edit/conf screen.

* Remove the title "NOTES" and give that cell the following hint text "Tell us why..." This way it is consistent with the web. 

* Give the "Tell us why..." field the same top and bottom gray border for the cell. 

* Make the "Tell us why..." field a little longer so it is about 30% longer the "IDENTIFICATION TAXON" field. Doesn't have to be exact. 

Please let me know if you have any questions.

**Comment by alexshepard** [comment]
multi-line text views don't get placeholders in iOS (only single line text fields do) so I just changed the title.

**Comment by alexshepard** [comment]
this is done in release 2.7.1
