### ISSUE TITLE
Photo rotated and squished on suggestions view

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#410]
Build 464, iPhone 5, iOS 10.3.2 (also happening on my old iPad Mini running iOS 9.3.5). Here's the photo in a modal:

![photo sep 18 12 57 18 pm](https://user-images.githubusercontent.com/22691/30561929-936eda18-9c71-11e7-9e69-2e767de65b63.png)

and here's what it looks like on the suggestions view:

![photo sep 18 12 57 26 pm](https://user-images.githubusercontent.com/22691/30561934-9a9f8968-9c71-11e7-8d09-7878cad54f4a.png)

This might only be happening for new photos that haven't been uploaded yet.

**Comment by naturalistmellis** [comment]
I also have this problem on all my observations lately.

**Comment by alexshepard** [comment]
should be fixed as of d6c3f8a320a567ce369106e1f036069b6d2939e3
