### ISSUE TITLE
Allow pasting in search box on the Explore tab.

### ISSUE THREAD

**Issue by mellis32** [inaturalist/INaturalistIOS#411]
Currently cannot paste species names into search box of the Explore tab. I mentioned this problem in #389.

**Comment by alexshepard** [comment]
note to self: this is likely caused by the same root issue as #167, the search bar in the explore tab is a little buggy due to how the view hierarchy is setup.

**Comment by mellis32** [comment]
Alex can you take another look at this?

The app would save me a great amount of time and frustration in the field if this bug were fixed.

**Comment by alexshepard** [comment]
Hi @mellis32 yep, I added this (along with #390) to my list of things I'll try to look in the next week or two.
