### ISSUE TITLE
Quick Usability Fixes to Slideshow

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#414]
In response to significant drop offs on the first screen, here is an alternative design...

Would love to track when we launch this so we can see if it's making a difference.

I was thinking the chevron could have a similar subtle bounce like this animation... https://codepen.io/dodozhang21/pen/siKtp (Imagine it was bouncing left and right, not up and down)

#  Dir 1:

![image](https://user-images.githubusercontent.com/11527994/32021433-3a4bd646-b988-11e7-83f5-4b295925bd6a.png)
* "Swipe" is 20pt medium weight. 
* I used the same chevron that's in the "Skip" button except increased its size by 1pt. 

# Dir 2: 50%

Same as 1, I just made the indicator circles about 30% bigger. I kinda like this. 

![image](https://user-images.githubusercontent.com/11527994/32023730-049499e6-b98f-11e7-92ad-a28b8d4513c3.png)

# Dir 2.1: 30ish%

![image](https://user-images.githubusercontent.com/11527994/32023821-4acf2a7a-b98f-11e7-84cc-a527c21b9f8a.png)

Note: On the iphone 7 the indicator circles are at the very bottom of the screen and harder to find. Was this because we needed a one-size fits all solution for all phones? If it's possible to easily raise these up about 10pt for the iphone 7 and/or for all phones without them interfering with the content, that would be great. If not, no biggie.

**Comment by loarie** [comment]
I think this is a good idea. I've anectodally seen people stall on this screen because its not clear they have to swipe. No pref on Dir 1 vs Dir 2

**Comment by joellebel** [comment]
The button could also be tappable and say "Next" instead of "Swipe."

**Comment by tiwane** [comment]
I think if one needs to tap it on the first page but swipe on the rest, that wouldn't be helpful. I think swipe is fine.

**Comment by joellebel** [comment]
@alexshepard Just a little low priority nitty pick… for the chevron in the “Swipe >” label, can we use the same chevron we’re using for the “Skip >” button on the Sign Up screen? The current chevron is the greater sign, I believe.
