### ISSUE TITLE
iOS 11 Updates to Tab Bar

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#418]
In efforts to stay looking so fresh and so clean clean, it would behoove us to update the tab bar with the latest iOS 11 styles. The new style is pretty much the same as the old style, but entails filled in icons as opposed to outlined. Feel free to brush up on it [here](https://developer.apple.com/ios/human-interface-guidelines/overview/whats-new/). 

For most of the icons, this means changing them to their corresponding filled in version. Since we're revisiting the tab bar, I thought it might be a good opportunity to update the Explore icon which I've never felt is the right fit for the following reasons: 

* The current iOS globe has always struck me as looking more like a language choosing or network icon. Here's some (not definitive) but some examples of language picker icons [Noun Project (Popular source for icons),](https://thenounproject.com/search/?q=language) [Google Search for "language icon"](https://www.google.com/search?q=language+icon&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiZ2KvZu-LXAhVW5GMKHbgdD6IQ_AUICigB&biw=1431&bih=1053)

* This can definitely be overly subjective, but I find the icon boring, cold and unfriendly which is the opposite of the iNaturalist brand. It really doesn't inspire me to want to "Explore" 

* I often feel like the term "Explore" is a verb and therefore the icon should describe this action as opposed to what you're exploring. For example, a compass can often be used to represent "explore" 

**Here's some compass examples:**

[Pinterest](https://www.pinterest.com) uses a compass in the upper right to signify "explore"
![image](https://user-images.githubusercontent.com/11527994/33349886-f42620e8-d450-11e7-9963-ba8b3de66d23.png)

* [Noun Project search for "Explore"](https://thenounproject.com/search/?q=explore)
* [Google search for "explore icon"](https://www.google.com/search?biw=1431&bih=1053&tbm=isch&sa=1&ei=E_cdWtLEMtaCjwOw-pWwBg&q=explore+icon&oq=explore+icon&gs_l=psy-ab.3..0l2j0i7i30k1l4j0i7i5i30k1l4.278533.279284.0.279619.7.7.0.0.0.0.130.650.5j2.7.0....0...1c.1.64.psy-ab..1.6.556...0i67k1j0i13k1.0._xj4X5-Alb8)

Below are some studies with different icons. The names of the specific directions are in fuschia above each mock up. 

Also, if anyone else has any other ideas, I am happy to mock them up. Just let me know. I know @alexshepard was interested in a compass rose. I can still mock up that up. However, in the past, it turned out too complex looking in comparison to the other icons. Happy to re-try. Just may delay things a bit.

# Globe Study

![image](https://user-images.githubusercontent.com/11527994/33351117-0fbafce2-d457-11e7-98c7-e538fe44ba15.png)

* Globe 4 is looking a little too detailed compared to the other icons, but wanted to show for comparison

# Compass Study

![image](https://user-images.githubusercontent.com/11527994/33351241-a79f9fcc-d457-11e7-8405-47b822e01656.png)

* Just a note the "Streamlined Compass" is the Android compass icon. Funny, how it can fit with the iOS icons. If we choose this one, I will alter it a bit. I first just wanted to see where we stand with things. 

# Binoculars Study

![image](https://user-images.githubusercontent.com/11527994/33351249-adcd2298-d457-11e7-80a6-c31b2c649926.png)

* Binocs 1 might be too detailed than the other icons in the tab bar, but I can tweak it
* Binocs 2 seems a bit on the sterile side

I really could probably be convinced of any of these icons. I can play with style. Right now, more importantly, I'm just trying to determine content.

When giving feedback think of what first comes to mind when thinking of "Explore"  and use what you've seen other places. 

I'll hold off on what I like the best until there's some feedback.

# Activity Revisit Maybe

The Activity icon has always struck me as blah.

Here's some ideas, but I'm not glued any of them. I realize the bell is more so used for notifications than news and this section is about notifications and news. Open to other ideas. I just didn't want to spend too much time on this icon if everyone else is fine with it. 

![image](https://user-images.githubusercontent.com/11527994/33351670-c5c437fe-d459-11e7-8ece-9bb0fb134da6.png)

**Comment by alexshepard** [comment]
The only feedback I have about this is that I'm not crazy about Globe 4, although I'm not sure I could put my finger on exactly why.

**Comment by joellebel** [comment]
@alexshepard ya I think it's too illustrative looking compared to the other more iconic-looking icons.

**Comment by joellebel** [comment]
Have to admit I like the Compass 2 direction the best. All the globes all seem too complicated next to the other icons and it's kinda hard to make a globe not look as clean as the other icons while including all the continents. 

A compass also illustrates the act of "exploring" more to me. The binoculars could work but we use them to illustrate "observations" on other platforms and really the Explore section has more than simply observations. 

Also, we'd have some platform parity with Android:
![image](https://user-images.githubusercontent.com/11527994/33580030-93cba74a-d900-11e7-8779-144185d76421.png)

Also, what do you guys think about using the iOS "people" icon for the Activity section? See below:

![image](https://user-images.githubusercontent.com/11527994/33580728-254f7578-d903-11e7-98d9-e46f98eddf1a.png)

I kinda like it because it's a little less narrowly-focused as the bell. The bell typically means notifications only.

**Comment by alexshepard** [comment]
to me the icon you're using for activity here indicates contacts or groups of people.

**Comment by tiwane** [comment]
Yeah, I like the bell, it's pretty universal for notifications/updates, which is kind of what that tab is. I do like the compass though.

**Comment by joellebel** [comment]
@alexshepard Looks like we're ready to go! Actually, I don't need to make any icons. All icons are found in ionicons. Here's there names:

![image](https://user-images.githubusercontent.com/11527994/34233414-1128784e-e59a-11e7-92cd-9c878176a2fd.png)


![image](https://user-images.githubusercontent.com/11527994/34233564-021ba38e-e59b-11e7-8902-e28976fe1547.png)

![image](https://user-images.githubusercontent.com/11527994/34233585-201cbe86-e59b-11e7-8783-b7cf9877ee30.png)


![image](https://user-images.githubusercontent.com/11527994/34233447-4bc74214-e59a-11e7-8f9c-dbecac8389f1.png)

As for the inactive state for the icons, we can use the default iOS gray for inactive tab bar icons.

**Comment by alexshepard** [comment]
done in c02e645b6cfb0d0fd06303374f260b420d848f84

**Comment by alexshepard** [comment]
released in 2.7.6
