### ISSUE TITLE
Slider dots in slideshow in wrong location on iPad

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#421]
![image](https://user-images.githubusercontent.com/11527994/33850568-215e6044-de69-11e7-9b26-7ba5d32da8d0.png)

**Comment by alexshepard** [comment]
fixed in 5062f683477dd0d7a13ce68813327cbe94d1f83e

**Comment by alexshepard** [comment]
released in 2.7.6
