### ISSUE TITLE
Fixes to Sign Up / Log In Screen Usability Issues

### ISSUE THREAD

**Issue by joellebel** [inaturalist/INaturalistIOS#424]
Here's what I was thinking...

![image](https://user-images.githubusercontent.com/11527994/35168705-c93f4486-fd0e-11e7-94d1-07adba5e4251.png)

* I merely removed the bottom (login/sign up) footer and put the content below the big green button.

* The text is the same gray we use for the other darker gray text on the screen is 15pt. Feel free to work with the text. The shorter the better.

@Alex I leave the transition of this new text during the switch from log in to sign up to you. I think a simple fade would do. So if you in your Sign Up and tap "Already have an Account?" the form shrinks up to the Log In form (like it does now) and the "Already have an Account?" would follow the green button up, but fade into "New to iNaturalist? Sign up now!"

**Comment by alexshepard** [comment]
ok, this would be very easy to implement

**Comment by tiwane** [comment]
Looks good.

**Comment by alexshepard** [comment]
released in 2.7.6
