### ISSUE TITLE
New observations screen bounces after taking photo and scrolling to the bottom

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#428]
To replicate:
1. Tap observe.
2. Take a photo with the camera (does NOT happen if selecting from the camera roll) and tap next.
3. See observation detail screen. Before tapping anything else, scroll to the bottom of the screen to see the bottom of "Projects".
4. See the screen "bounce".

Tapping into a field that brings up a new view (e.g. location, what did you see, or projects) appears to make the problem go away. 

If these steps don't work, try quitting the app, reopen, and try again.

Version 2.7.6 build 479, iphone 6s 11.2.6

**Comment by tiwane** [comment]
I can replicate on my iPhone 8.
