### ISSUE TITLE
NatureWatchNZ host needs to be updated

### ISSUE THREAD

**Issue by pleary** [inaturalist/INaturalistIOS#439]
For reasons beyond our control, NatureWatchZ has moved from http://www.naturewatch.org.nz/ to http://inaturalist.nz/ . We cannot set up a server-side redirect. It looks like the host is saved somewhere in the app as users are getting unknown host errors.

Could we update any references of http://www.naturewatch.org.nz/ to http://inaturalist.nz/ ?

![image1](https://user-images.githubusercontent.com/48566/40387032-5ade6c5c-5dd9-11e8-9c01-239e18e91f84.PNG)

**Comment by pleary** [comment]
(updated the description to reflect new, hopefully stable this time, domain of http://inaturalist.nz/)

**Comment by gailtv** [comment]
I am having the same problem with the NZ based iNaturalist app for iPhone. It seems to do everything except load observations.  Not fixed at this time.

**Comment by alexshepard** [comment]
fixed in c048936d30b40ac32f4e94db2e42e30bff6637da
