### ISSUE TITLE
Make app default to Log In screen rather than Sign Up screen 

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#447]
A recurring issue on the mobile apps is that people who already have accounts will get the app and trying to log in on the Sign Up screen, since it's displayed by default. They usually get an "email address has already been taken" error which confuses them. I think we should make "Log In" the default screen on the mobile apps to reduce the chances of this happening.

**Comment by alexshepard** [comment]
done in affa0c2ce6837e48cef9911a8a80f6d79646e051
