### ISSUE TITLE
Strange behavior when observation doesn't fit project requirements

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#455]
1. If you haven't already, join [Tony's Test Project](https://www.inaturalist.org/projects/tony-s-test).

2. In the iOS app (build 498), add an observation with a location anywhere but in Knowland Park, Oakland and add it to Tony's Test.

3. Upload the observation. You will get a 422 error because the observation doesn't fit the project's requirements, the observation will look pink, and the Me tab will say you still have 1 observation to upload. If you check on the web, though, the observation will have been uploaded.

![img_9c5f096b9ede-1](https://user-images.githubusercontent.com/15896181/44013179-c7da5c46-9e78-11e8-9e86-72ece3612f60.jpeg)

![img_a34763efa573-1](https://user-images.githubusercontent.com/15896181/44013180-c7ee4b3e-9e78-11e8-9b40-87ebdf12bf17.jpeg)

4. In the iOS app, remove the observation from Tony's Test. 

5. 422 warning and pink coloration will still be on the observation in the app until you log out and log  back in.

**Comment by alexshepard** [comment]
is this a duplicate of #444?

**Comment by tiwane** [comment]
Apparently it is. I can close it.
