### ISSUE TITLE
Revisit tutorial

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#457]
We have an out of date tutorial linked to from the Settings screen should we:

1) pull tutorial

2) commit to maintaining / maintain tutorial

?

**Comment by tiwane** [comment]
@alexshepard just bumping this as we still get some emails from people asking why they can't mark something as "Needs ID". I say either link to the current tutorial video (https://vimeo.com/162581545) or pull the tutorial.

**Comment by tiwane** [comment]
I say until we have time to make a new one, let's remove it from the app. Still getting emails about the lack of a "Needs ID" button.

**Comment by alexshepard** [comment]
Internal poll suggested we should link to the tutorial video (if the user is online).

**Comment by alexshepard** [comment]
done in 61a1d1e2faee1f28a941a472f511b6c1dc5cdb03

**Comment by alexshepard** [comment]
released in 2.7.19
