### ISSUE TITLE
Searching for people, locations, and projects in Explore tab not working in build 504

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#463]
In Explore, tapping on Find people named, Find locations named, and Find projects named makes the search field disappear but nothing pops up to show results.

**Comment by tiwane** [comment]
Just noticed that when I try to tap on the X to clear my organism filter, nothing happens. Gray bar still there.

**Comment by tiwane** [comment]
In build 505 searches are working (woohoo!) but I'm still not able to clear searches by tapping on the X in the gray bar. Also, the users modal is displayed weirdly:

![image](https://user-images.githubusercontent.com/15896181/47119157-c23c4780-d2a4-11e8-9bbe-42116bb4979d.png)

**Comment by alexshepard** [comment]
> I'm still not able to clear searches by tapping on the X in the gray bar

should be fixed, safe to close?

> the users modal is displayed weirdly

i'm inclined to not touch this stuff since i'll be revamping explore to match android soon-ish
