### ISSUE TITLE
Layout issues on iOS 12

### ISSUE THREAD

**Issue by jtklein** [inaturalist/INaturalistIOS#469]
The camera screen has some layout issues on iOS 12

![252291ae-c4b4-4e31-9074-8b470a36266e](https://user-images.githubusercontent.com/17345891/47017063-8cd31500-d151-11e8-9563-21ddc601dbe9.png)

**Comment by alexshepard** [comment]
Thanks for the bug report @jtklein what version of the app and what model of phone do you have?

**Comment by jtklein** [comment]
iNaturalist v 2.7.12
iPhone 7
iOS 12.0.1

**Comment by alexshepard** [comment]
Released today in 2.7.15, thanks for the bug report and apologies for the delay in fixing it.
