### ISSUE TITLE
Add link to donation page from iOS app settings

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#475]
On the settings page, add a link that says "Donate to iNaturalist". 

![ios_2](https://user-images.githubusercontent.com/7501183/49384514-28601b00-f6e9-11e8-84bb-9ff46a8b0c17.png)

Clicking "Donate to iNaturalist" should open their device browser (external) and take people to http://www.inaturalist.org/donate?utm_source=iOS

Hold for release until payment system integration is confirmed.

**Comment by alexshepard** [comment]
done in 1b370b32edee11850bbed21bd767280e0da188f0

**Comment by alexshepard** [comment]
Released today in 2.7.15.
