### ISSUE TITLE
changes to partnership alerts

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/INaturalistIOS#494]
- [x] on about screen, selection should come before popup
- [x] don't allow changing network partnership from the about screen more than 1x per 24 hours in the app (using NSUserDefaults)
- [x] change about screen popup text (see below)
- [x] change login screen popup text (see below)

new about screen popup text:

```
[iNaturalist Canada] is a member of the iNaturalist Network in [Canada]. Local institutions supporting [iNaturalist Canada] will have access to your email address and access to the true coordinates for observations that are publicly obscured or private. Would you like to change your affiliation? 

Yes, change my affiliation
No, don’t change my affiliation
Learn more (links to https://www.inaturalist.org/pages/network)
```

new login screen popup text:

```Join [iNaturalist NZ]?
[New Zealand] is part of the international iNaturalist Network. Would you like to join [iNaturalist NZ — Mataki Taio] to localize your experience of iNaturalist and share data with local institutions? 
[logo]
No
Yes```

**Comment by alexshepard** [comment]
@carrieseltzer do we still need to say `Please do not experimentally change your affiliation if you have more than 1000 observations` if we're enforcing it by only allowing you to change your affiliation once per 24 hours?

**Comment by carrieseltzer** [comment]
No, I think if we're enforcing it in the app we can ditch that line. Thanks!
