### ISSUE TITLE
Make minimum character number for taxon search 1 character rather than 3

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#497]
(via Cheng-Tao Lin)

Many common names in Taiwanese and Chinese (Traditional) are one character, but the app doesn't start searching iNat's taxon database until three characters are entered. Would it be possible to reduce the minimum number of characters that instigate a search from 3 to 1? From Cheng-Tao:

"The code is:

if (searchController.searchBar.text.length < MIN_CHARS_TAXA_SEARCH) {

default value is 3
source: https://github.com/inaturalist/INaturalistIOS/blob/b8f4ed4b42d1ef982bd7cd5d12cba27c34580238/INaturalistIOS/TaxaSearchViewController.m#L126"

**Comment by alexshepard** [comment]
released in 2.7.18
