### ISSUE TITLE
Don't use address-level place guesses

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#500]
One of the most frequent topics of help@inat emails is the address-level place guesses the mobile apps give. These are often inaccurate, and users ask how they can change the place guess, which can't be easily done in the mobile apps. 

Rather than share this specific and often inaccurate information, is it possible to just return a city or county level place guess?

**Comment by alexshepard** [comment]
done in 8bd718366f745a179d2e5628341733d655be9eae

**Comment by alexshepard** [comment]
released in 2.7.19
