### ISSUE TITLE
Show a pop-up message if someone tries to add an observation to a collection project

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#503]
Currently, when someone tries to add an obs to a collection project, nothing happens when they tap on the collection project's name and they don't understand why that is so. Can we have a pop-up message appear when someone taps on a collection project that says something like

"Observations cannot be manually added or removed from a collection project, but they will be included in it if they meet its requirements."

**Comment by alexshepard** [comment]
done in 4ec8b70

**Comment by alexshepard** [comment]
released in 2.7.19
