### ISSUE TITLE
Add branding to splash screen

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#509]
Add branding to splash screen - the spacing is the same as the nat geo rectangle
<img width="592" alt="Screen Shot 2019-06-21 at 10 14 19 AM" src="https://user-images.githubusercontent.com/598026/59939628-69154c80-940d-11e9-9a8a-d03dd1d8bc59.png">

**Comment by abhasinat** [comment]
@loarie @alexshepard do you need anything from me on this? happy to send over assets if necessary.

**Comment by alexshepard** [comment]
released in 2.7.19
