### ISSUE TITLE
Add Ecuador to network

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#517]
Please add Ecuador to the list of options for account affiliation and set up the corresponding affiliation prompt for app users in Ecuador. Please hold for release until INABIO is ready.

base url: https://ecuador.inaturalist.org
logo image: https://static.inaturalist.org/sites/14-logo.png?1560952555
Short name: iNaturalistEc
Long name: iNaturalist Ecuador
Site ID: 14

**Comment by alexshepard** [comment]
done in 26f03a5797bc34bced02ae9009d0b995449f0e07

**Comment by alexshepard** [comment]
released in 2.7.20
