### ISSUE TITLE
Undefined constants when building iOS iNat app in XCode 10.3.

### ISSUE THREAD

**Issue by shuetrim** [inaturalist/INaturalistIOS#518]
As part of unravelling the mysteries of how to do OAUTH authentication with iNat, I am trying to build the latest GITHUB source code for the iNaturalist iOS app using XCode 10.3, having modified the config.h file, and the bundle identifier and having set the clang warning Unintentional Root Class to be something other than Yes (Error) for the RestKit target in the Pods project (I set it to No).

Everything goes OK except for 2 constants: 

- INatAnonymousAPISecret 
- INatPartnerLearnMoreURL

which do not seem to be defined anywhere within the project. For my purposes I can comment out the code using those values but it would be good to know how to properly build the app.

**Comment by alexshepard** [comment]
Hi @shuetrim these constants are provided in the config.h. The first is iNat internal, and the second is just a URL on the iNat site. 
The code that uses the constants should be wrapped in #ifdefs, so I'll fix that!
Thanks for the issue!

**Comment by shuetrim** [comment]
Thanks @alexshepard.
