### ISSUE TITLE
Show species complex rank in taxon chooser

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#522]
iNaturalist a relatively new taxonomic level, the "species complex", which sits below genus and above species. eg https://www.inaturalist.org/taxa/894751-Laphria-canis However, this rank is not specified in the mobile apps, meaning if I type in _Laphria canis_, I'll see:

![image](https://user-images.githubusercontent.com/15896181/62903577-03ac5080-bd18-11e9-8f0a-bee43da54118.png)

Can we show the species complex rank in situations like this so that one can differentiate between them?

**Comment by alexshepard** [comment]
So for the complex, this should say "Complex Laphria canis" with no italicization?
