### ISSUE TITLE
Add Argentina to network

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#538]
Please add ArgentiNat to the list of options for account affiliation and set up the corresponding affiliation prompt for app users in Argentina. Launch date is Nov 21. Will notify when site is out of draft mode.

base url: https://www.argentinat.org
logomark + workmark image: https://static.inaturalist.org/sites/16-logo.png?1573064864
Short name: ArgentiNat
Long name: ArgentiNat
Site ID: 16

**Comment by alexshepard** [comment]
done in 2.8.6
