### ISSUE TITLE
in My Observations, cannot cancel Add ID without picking a taxon first

### ISSUE THREAD

**Issue by inaturalist** [inaturalist/INaturalistIOS#54]
When you tap "Add ID", the ID form shows, but the taxon choose dialog pops up immediately. Tapping "Done" from the taxon chooser closes it, but it immediately re-opens.

**Comment by alexshepard** [comment]
hmm, the Add ID button on an ObservationDetail should probably just push the TaxonChooser directly? not sure what value the AddIdentificationViewController provides...

**Comment by alexshepard** [comment]
dup of #19
