### ISSUE TITLE
Swiping down photo on Details screen causes problems

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#542]
On iPhone XS running 13.2.2, using 2.8.5 (551)

1. Make a new observation by taking a photo in the app
2. On the Details screen, tap on the obs photo
3. Swipe down on the photo to make it go away
4. App shows new obs screen (with camera), and it's unworkable. App needs to be closed

Related:

1. Go to Details screen of existing observation
2. On the Details screen, tap on the obs photo
3. Swipe down on the photo to make it go away
4. App shows regular view of the observation, but slightly smaller (see black border). Tapping on the screen makes the observation show full screen and app goes back to normal.

![image](https://user-images.githubusercontent.com/15896181/69372597-dc3e1b80-0c56-11ea-901f-b239470ce6cd.png)

**Comment by tiwane** [comment]
Related: 

1. Tap on "i" for a computer vision suggestion.
2. Tap on the default photo for the taxon and swipe left through the photos.
3. If you swipe to the left on the last photo, the photo will disappear to the bottom left corner and the new obs screen will appear. It does not work and the app needs to be quit and restarted.

**Comment by tiwane** [comment]
@alexshepard 

This is still happening in 3.1, both for existing observations and when making a new observation from one's camera roll.

1. Go to Details screen of existing observation
2. On the Details screen, tap on the obs photo
3. Swipe down on the photo to make it go away
4. App shows regular view of the observation, but slightly smaller (see black border). Tapping on the screen makes the observation show full screen and app goes back to normal.

**Comment by alexshepard** [comment]
done in 6d5343a4f408da5f599d362667ecb75fc16d5b3c
