### ISSUE TITLE
Add link to iNat Store from iOS app settings

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#544]
On the settings page above "Donate to iNaturalist", add a link that says "Shop the iNat Store".

Clicking should open a browser and take people to:
 https://store.inaturalist.org/?utm_source=iOS&utm_medium=mobile&utm_campaign=store

**Comment by alexshepard** [comment]
done in 254d95dbaf790833092f16eca30757bdc1e6ff5c, i18n in c5688b1120cc12c416000a13bf594beaf5e6571a
