### ISSUE TITLE
Update About text to add more network members

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#550]
Please add (in alphabetical order):

Argentina: Fundación Vida Silvestre Argentina supporting ArgentiNat (www.argentinat.org)
Australia: Atlas of Living Australia supporting iNaturalist Australia (inaturalist.ala.org.au/)
Ecuador: Instituto Nacional de Biodiversidad (INABIO) supporting iNaturalist Ecuador (ecuador.inaturalist.org)
Israel: University of Haifa supporting iNaturalist Israel (israel.inaturalist.org)
Finland: Finnish Museum of Naturalist History (Luomus) supporting iNaturalist Finland (https://inaturalist.laji.fi)

Sorry I missed this when we added them originally. From now on I'll include the appropriate "About" text in the issues for adding new network members, unless you'd prefer those be two separate issues.

**Comment by alexshepard** [comment]
done in ba81152b9671a8bbc774979ddb23e02b36c55abc
