### ISSUE TITLE
Spinner on Project Page Never Stops

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#556]
In Version 2.8.7 (558), the spinner in the upper right-hand corner never stops or goes away.

![image](https://user-images.githubusercontent.com/15896181/80147619-a0daac80-8568-11ea-8603-5cfb5a0d7fc8.png)

**Comment by bhostetler18** [comment]
Hello! I'm interested in helping with iNaturalist and I believe I've fixed this bug (though I do have some questions about further improvements to the activity indicator). Should I open a pull request? I sent an email but I'm not sure if it went through
