### ISSUE TITLE
Change default branch to main

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#564]
Since I'm not sure what affect this will have, I'm assigning you, Alex. Here are the steps I've been following in other repos:

1. Try to close as many pull requests as you can. PR's made against master will still be against master after you switch and will have to be updated, which might cause weirdness
1. `git branch -m master main` to switch locally
1. `git push origin main` to push to github. Now github has both master and main branches
1. At https://github.com/:you/:your-rep/settings/branches, change the default branch to main
1. Locally again, `git remote set-head origin --auto` to set the local HEAD reference
1. `git branch main -u origin/main`
1. Change extant PRs against master to be against main instead
1. Update any 3rd party integrations like Crowdin, which pulls from the master branch for web and Seek
1. Delete master
1. Somehow notify developers of the change so they can get their local repos in sync

**Comment by alexshepard** [comment]
✅
