### ISSUE TITLE
Support user preferences for common and scientific names

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#575]
We allow users on both the web and in the Anrdroid app to control which names are displayed, and quite a few people have asked that this functionality be added to the iOS app. 

It would be great to allow the third party data sharing preference as well.

![image](https://user-images.githubusercontent.com/15896181/93944762-69745580-fcea-11ea-96c2-0b7152637918.png)

**Comment by alexshepard** [comment]
changed title, data sharing was added in 3.1

**Comment by alexshepard** [comment]
merged in 30b2db193a1988161f9aba0c8ea8c751ee01b183
