### ISSUE TITLE
New comments showing at the top of the comments/IDs screen

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#587]
Version 3.1. I replied to the comment by sea-kangaroo on [this observation](https://www.inaturalist.org/observations/68830266), but my comment shows at the top of order. This observation was added via the web, my comment was added in the iOS app. 

![image](https://user-images.githubusercontent.com/15896181/106522338-6f4a2680-6494-11eb-8500-6722b77c99fe.png)

[This observation](https://www.inaturalist.org/observations/68777344) was added via the iOS app but my comment was added via the web, and my comment is showing at the top of the list:

![image](https://user-images.githubusercontent.com/15896181/106522637-dbc52580-6494-11eb-8579-ae97e47f0a8f.png)

**Comment by alexshepard** [comment]
tentatively fixed in 3741f1be64f61cca45514bead57ec9df7d22c89d but this might actually be a node bug
