### ISSUE TITLE
Add 3 more new network members

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/INaturalistIOS#596]
Please add these three sites to the list of options for account affiliation and set up the corresponding affiliation prompt for app users in their respective countries. Launch dates are between May 14-20, so please aim to include in the next release if possible.

For wordmarks, please refer to the folder Abhas created with all network member wordmarks in different sizes.

base url: https://costarica.inaturalist.org
Short name: NaturalistaCR
Long name: Naturalista Costa Rica
Site ID: 17

base url: https://guatemala.inaturalist.org
Short name: iNaturalistGT
Long name: iNaturalist Guatemala
Site ID: 24

base url: https://www.inaturalist.se
Short name: iNaturalist.Se
Long name: iNaturalist Sweden
Site ID: 21

In the About section, please add (inserting in existing alphabetical order by country name):
Costa Rica: Comisión Nacional para la Gestión de la Biodiversidad (CONAGEBIO) supporting Naturalista Costa Rica (costarica.inaturalist.org)
Guatemala: Consejo Nacional de Áreas Protegidas (CONAP) supporting iNaturalist Guatemala (guatemala.inaturalist.org)
Sweden: SLU Swedish Species Information Centre supporting iNaturalist Sweden (www.inaturalist.se)

**Comment by alexshepard** [comment]
done in d6ed04216730e7cd20ffc187397b701607144e07
