### ISSUE TITLE
"already added to project" is a pointless error message

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#6]
If the phone gets that response from the site, it should just update the local error instead of showing an error message.

**Comment by alexshepard** [comment]
when does this error occur, during sync?

**Comment by kueda** [comment]
Yes, but it might have been due to problems with local data getting out of date with the site, or local project observation records getting duplicated for some reason. Not a very well-articulated issue, I'm afraid, and I haven't seen or heard of it in ages, so I will close.
