### ISSUE TITLE
Spam projects show up in projects search results

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#601]
1. On the Projects screen, search for "desales"
2. Results include this test project of mine, which I've flagged as spam. 

![image](https://user-images.githubusercontent.com/15896181/121065966-34c40380-c77e-11eb-912c-81734a208dcf.png)

**Comment by alexshepard** [comment]
done in dc49ac9835cf8e59ec24ef670d8c329fdde059b4
