### ISSUE TITLE
When offline, one's Projects list no longer loads

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#602]
From: https://forum.inaturalist.org/t/empty-projects-list-in-ios-app-and-error-422/21648

Not too long ago, it seems as though joined projects were cached in the app. This allowed folks to made new obs and add them to traditional projects (and fill out obs fields) while in airplane mode. This is no longer the case, however - part of the memory clearing stuff the app is doing now?

**Comment by alexshepard** [comment]
can't reproduce, maybe fixed as part of 6ce3d87?
