### ISSUE TITLE
Activity tab only shows common names regardless of name display preference 

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#603]
From: https://forum.inaturalist.org/t/activity-tab-in-ios-app-only-shows-common-names-not-scientific-ones/23006

Pretty much what the title says. I think if the user has turned off `Show common names` or `Show scientific names first` we should honor that in the Activity tab. Currently it shows common names regardless of user's settings.

![image](https://user-images.githubusercontent.com/15896181/121743742-aa014280-cab6-11eb-9fb6-d9c2e3066455.png)

**Comment by alexshepard** [comment]
done in c6e332fa075cb9dafafdb0ba0fddbb86d7a8734c
