### ISSUE TITLE
In Explore, obs detail screen doesn't show date/time info

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#604]
iOS 3.2.1

1. Go to Explore
2. Go to obs show of any observation.
3. No date or time info is shown, eg

![image](https://user-images.githubusercontent.com/15896181/123681292-7fc1bb80-d7fe-11eb-9571-2118a8ab900f.png)

**Comment by alexshepard** [comment]
time added back in 45727a1b
