### ISSUE TITLE
Setting an obs geoprivacy settings to Priate in app removes location of obs in app, but not website

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#606]
Version 3.2.1

1. Make a new observation, make sure it has a location.
2. Set geoprivacy to private.
3. Share observation.
4. Tap on observation and tap on Edit.
5. App shows "No location" on the edit page and if you tap on the location, you'll see the map showing 0,0.
6. Go to the observation on the website and it has a location.

**Comment by alexshepard** [comment]
fixed in 845ea708
