### ISSUE TITLE
Taxa names fluctuate between scientific and common in the My Content pane under the Activity page

### ISSUE THREAD

**Issue by groeneveld** [inaturalist/INaturalistIOS#607]
iOS 14.6 iNat 3.2
Preferences: Show common names = false; Show scientific names = true
Test conducted on fresh install of app.

Steps to reproduce:
-Visit My Content tab under Activity page. The observation names are in common name format despite the preferences described above. 
-Tap on an observation
-Tap on the taxa of the observation (right under the observation photo) to go to the taxa page
-Tap the back button twice to go back to the My Content page and that specific observation name is now in scientific format. No other observation names have changed until the above procedure is repeated for that observation.

Restarting the app changes the names back to common name format.

![IMG_6660](https://user-images.githubusercontent.com/7132765/123884684-0bc00a00-d909-11eb-82da-c06a115c49cc.PNG)
![IMG_6661](https://user-images.githubusercontent.com/7132765/123884653-f64ae000-d908-11eb-97fc-47684e3340cf.PNG)

**Comment by alexshepard** [comment]
thanks for the bug report @groeneveld will get this done for the next release!

**Comment by groeneveld** [comment]
:). I also noticed pulling down to refresh the page also initiates the switch from scientific to common.

**Comment by alexshepard** [comment]
done in c6e332fa075cb9dafafdb0ba0fddbb86d7a8734c
