### ISSUE TITLE
Stop restricting web view by URL in forgot password flow, maybe close based on POST response

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#608]
Currently when a user says they forgot their password, the app sends them to https://www.inaturalist.org/forgot_password.mobile, but it should be sending them to https://www.inaturalist.org/users/password/new. I recently tried redirecting requests for https://www.inaturalist.org/forgot_password to the current URL, but that broke the iPhone app b/c it currently detects the end of the reset password flow by shutting down the web view when it goes anywhere other than https://www.inaturalist.org/forgot_password.

Instead, maybe we could just not restrict that web view by URL and instead close it when it makes a POST request and receives a 2xx or 3xx response.

**Comment by alexshepard** [comment]
done in 7bb9c9d
