### ISSUE TITLE
Distinguish genus from nominate subgenus in iOS app 

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#610]
From: https://forum.inaturalist.org/t/distinguish-genus-from-nominate-subgenus-in-ios-app/24340

Right now we don't distiguish one from the other, so when a subgenus has the same name as its parent genus, the user can't tell which one is used for an ID. eg 

![image](https://user-images.githubusercontent.com/15896181/124840373-adfe7400-df3f-11eb-821c-19ca62e0dcb2.png)

Here's how it looks in Android:

![image](https://user-images.githubusercontent.com/15896181/124841108-5d881600-df41-11eb-96b1-559bfa9014e8.png)

I think we should follow that model.

**Comment by alexshepard** [comment]
done in 17f5b568d80449299ab47030ec17ba83ec5c4542
