### ISSUE TITLE
Expand tappable area for radio buttons under photos 

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#613]
They're pretty narrow ([see this Forum thread](https://forum.inaturalist.org/t/ios-observation-photo-selection-radio-buttons-hard-to-select/25070)) and after talking with @alexshepard we think they should be expanded from 28 px tall to 44 px tall.

**Comment by alexshepard** [comment]
done in bdd7e2431bf1c6b9a971f06c2c27b16f152d74b1
