### ISSUE TITLE
Authenticate registration requests

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#616]
I want to lock down account creation to prevent automatic creation of spam accounts (see https://github.com/inaturalist/inaturalist/issues/3122). To do this, clients will need to authenticate `POST /users.json` requests with an application JWT, the same way they authenticate CV requests for signed out users. It should be safe for clients to implement this change before the server starts requiring the JWT.

**Comment by alexshepard** [comment]
done in baac854bf4675b32ed79ec4b7502e14903da279b
