### ISSUE TITLE
Don't require hyphens when searching hyphenated common names

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#622]
From https://forum.inaturalist.org/t/suggestion-optional-hyphens-in-ios-app/26623

Not sure if this is a bug or intentional, but when searching for taxa, if one skips the hyphen when searching for a hyphenated common name (eg [white-throated swift](https://www.inaturalist.org/taxa/6553-Aeronautes-saxatalis)), one gets no results:

![image](https://user-images.githubusercontent.com/15896181/134558190-8c4be086-f365-48bb-94dc-9a6c6f6c33ef.png)

But on both the website and Android app, that's not the case:

![image](https://user-images.githubusercontent.com/15896181/134558519-d7973cee-ab06-425e-b3bc-2aa6718d67a0.png)

![image](https://user-images.githubusercontent.com/15896181/134558879-563400d7-18a1-44d1-8acd-224677a5e66d.png)

It would be great if the iOS app didn't require a hyphen when searching for taxa.

**Comment by alexshepard** [comment]
can we close this @tiwane ?
