### ISSUE TITLE
Can't add sound to existing observation

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#628]
Version 3.2.3. From https://forum.inaturalist.org/t/adding-sound-recording-to-observation-in-app-closes-observation-without-saving/27959 and I can replicate. 

    Step 1: Create observation, either without media or with photo (in-app or from photo library)
    Step 2: Add sound recording, press ‘save recording’ when finished
    Step 3: Observation will briefly show two recordings before closing the observation without saving

Screen recording from my device:

https://user-images.githubusercontent.com/15896181/142476253-0e147c43-5d1a-47a4-920e-0c21bb4536ed.MP4

**Comment by alexshepard** [comment]
this is fixed, right @tiwane ?

**Comment by tiwane** [comment]
Yes, although now I can't delete a sound from an observation. I'll make a new issue for that.
