### ISSUE TITLE
Handle 201 CREATED response to POST /users.json

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#631]
As a part of the upcoming required email validation, creating a new user account will not be the same thing as authenticating that user, because after the account is created, the user cannot authenticate until they have verified their email address. Because of this, a successful `POST /users.json` request will respond with a `201` status to indicate the user was created, and a JSON body like

```json
{
  "message": "A message with a confirmation link has been sent to your email address. Please follow the link to activate your account."
}
```

If `POST /users.json` includes a `locale` key in the request body, the `message` in the response should be localized.

So here are some todos:

- [x] The app should include the user's / device's `locale` when making the request to create the account
- [x] The app should respond to a `201` response status by showing the user a message and not signing them in
- [x] The message should be the `message` in the JSON response

**Comment by alexshepard** [comment]
done in dc1a9a9ef4f9b869f6f1ea83c05f318e2cd1472d
