### ISSUE TITLE
Removing images from existing observation crashes app (3.2.6)

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#637]
From https://forum.inaturalist.org/t/editing-observation-crashes-app/36097 I can replicate.

Step 1: from Me page, tap existing observation

Step 2: from Observation Detail page, tap Edit.

Step 3: from Edit Details page, delete two of three images.

Step 4: Tap Done. App crashes/closes.

Step 5: Open app. Edited Observation shows “waiting to upload”status. Press Upload, and deleted images remain.

**Comment by alexshepard** [comment]
fixed in 3.2.12
