### ISSUE TITLE
Geoprivacy shows "Unknown" by default for new observations in 3.2.6

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#638]
From https://forum.inaturalist.org/t/geoprivacy-shows-unkown-by-default/36174 I can replicate

1. Make a new observation that has a location (eg from a geotagged photo or with the iNat camera)
2. Details screen shows "Unknown" in Geoprivacy field:

![image](https://user-images.githubusercontent.com/15896181/194171064-4ceab215-9380-4003-8562-5e5ed9063c73.png)

If you upload the observation without changing the Geoprivacy, it uploads as `Open` geoprivacy, which should be what is displayed on the Details page by default.

**Comment by alexshepard** [comment]
same as #655
