### ISSUE TITLE
Default to user's geolocation when location cannot be received from photos

### ISSUE THREAD

**Issue by Chrischuck** [inaturalist/INaturalistIOS#644]
When location cannot be determined from the photo and the user attempts to manually set the location, default to user's location. Personally, when uploading images from my gopro, it was a bit annoying to have to move to my location every time. If this change seems reasonable, I would love to work on this and make a pr.

Image w/o geolocation
![IMG_2103](https://user-images.githubusercontent.com/13311268/210021535-ff480bef-aadb-439d-a90b-7b2bd5d76b79.PNG)

Map view defaults to 0,0 - would be nice if it defaulted to your current general area
![IMG_2104](https://user-images.githubusercontent.com/13311268/210021752-bd077758-270e-4f90-b058-a2e5bafe5e71.PNG)

**Comment by Optilete** [comment]
Relevant Feature request: https://forum.inaturalist.org/t/make-current-location-default-in-android-app-instead-of-south-atlantic-ocean-0-0/23167

**Comment by rainhead** [comment]
Is this just to save yourself a tap of the compass button?

What makes sense to me is for the map to show any recent observations, so you can locate this one relative to them.

Regardless, the behavior should be the same across platforms.

**Comment by alexshepard** [comment]
We use github issues for technical issues that we know we're going to work on, not for open discussions of ideas. 
Once there is consensus in the forum on an issue, we might move it here.
