### ISSUE TITLE
Native/non-native tags

### ISSUE THREAD

**Issue by rachadele** [inaturalist/INaturalistIOS#650]
It would be nice if users could add and filter through conservation-related tags for observations (e.g. native, non-native/invasive) on the iOS UI.

**Comment by alexshepard** [comment]
Hi @rachadele ,

Thanks for the feature request!

This codebase is in bugfix mode while we work on a replacement app. My suggestion to raise attention to your feature request would be to post on the [iNat forums](https://forum.inaturalist.org).

Thanks,
Alex
