### ISSUE TITLE
Remove Facebook Login

### ISSUE THREAD

**Issue by kueda** [inaturalist/INaturalistIOS#651]
Facebook has removed our access to the platform, so we should remove all of our Facebook integrations, including:

- [ ] Any Facebook SDKs
- [ ] The Facebook button on the Log In views

**Comment by kueda** [comment]
@alexshepard did ca5b95d7c6845d55b6c42d8dd64d6b7f126f011d take care of this?

**Comment by alexshepard** [comment]
yep
