### ISSUE TITLE
3.2.8 (686) - Toggling "Suggest species" in Settings affects other preferences

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#656]
From https://forum.inaturalist.org/t/iphone-app-when-you-turn-on-suggest-species-it-also-turns-on-automatic-upload/43148

1. Make sure Autocomplete Names, Automatic Upload, Suggest Species, and Show Common Names are toggled on.
2. Turn off Automatic Upload and Suggest Species, then go back to your obs list
3. Go back to Settings. Automatic Upload, Suggest Species, and Show Common Names are toggled off.
4. Turn on Suggest Species then go back to your obs list.
5. Go back to Settings and both Suggest Species _and_ Automatic Upload are turned on.

**Comment by tiwane** [comment]
See screen recording here: https://inaturalist.slack.com/archives/C02F8RN5Q/p1688754359698639

**Comment by tiwane** [comment]
Related: toggling show common names also affects other settings

1. Go to Settings in the app
2. Turn off Show common names
3. App now displays scientific names only
4. Refresh observations in Me tab and they switch to scientific name only
5. Go back to Settings and turn on Show common names
6. Go back to Me tab and tap on an observation. You now see scientific names first and common names second
7. Go back to Settings. YOu now see "Show scientific names first" toggled on.

**Comment by alexshepard** [comment]
think this is fixed, right @tiwane ?
