### ISSUE TITLE
Chinese language mixup on iOS

### ISSUE THREAD

**Issue by lizzyd710** [inaturalist/INaturalistIOS#657]
My phone’s language is set to simplified Chinese, and when I am using the app, I see the traditional Chinese names for certain species. (Example: red eared slider)

![4A50D9F3-5155-4AAD-A8B5-F3C265F72920](https://github.com/inaturalist/INaturalistIOS/assets/12602768/0014cd96-bb03-47f6-9196-81f7e9ffd8f0)
![C1AD62AE-CF44-49D4-9E8C-51D5961A9C1D](https://github.com/inaturalist/INaturalistIOS/assets/12602768/e67d9286-dd64-4a5b-a0fc-d7a16e12ccd7)

When using the website and manually setting the language to Simplified Chinese it displays fine. 

I know that iNaturalist integrates with Wikipedia for certain species, and Wikipedia does not have separate pages (kinda) for traditional vs simplified, so perhaps that could be contributing to the issue.

**Comment by alexshepard** [comment]
yep, duplicated of #584. closing, but also fixed in e819e70fa156a315f452212ac45c59bbddb5c409 so will be in the next release.
