### ISSUE TITLE
Ability to report many observations in one upload

### ISSUE THREAD

**Issue by tttalshaul** [inaturalist/INaturalistIOS#660]
As we do in web version. 
I think that this ability might accelerate the number of reports people add to iNaturalist, because it's pretty tough to report 50 observations one by one from iOS app. 
In the web version we upload all the pictures, drag them one on the other to group them, and then add identifications. It's much faster, but most people tend to use the iOS app rather then the website.. 
(An improvement idea)

**Comment by alexshepard** [comment]
Hi,

Please post this to https://forum.inaturalist.org/ where feature ideas from users are discussed.

We are working on a new version of iNaturalist Mobile that I believe may have a feature like this. I are only doing bug fixes on this app in the meantime, so I won't implement this in the current iOS app. 

Best wishes,
alex
