### ISSUE TITLE
Change 'Seen Nearby' to 'Expected Nearby'

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#664]
ideally make this change by Sept 23
<img width="328" alt="Screenshot 2023-09-12 at 3 25 49 PM" src="https://github.com/inaturalist/INaturalistIOS/assets/598026/a9a496a8-7fb1-495e-a587-a16332e7bcf1">

**Comment by alexshepard** [comment]
strings are on Crowdin for translation

**Comment by alexshepard** [comment]
this is done and release 3.2.14 is rolling out to App Store starting today
