### ISSUE TITLE
Make top text easier to see on location editor

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#666]
Depending on the map tile, the "Cancel" and "Save" text at the top of the location editor can be very difficult to see (and the Lat doesn't show her at all on my iPhone 13 Pro): 

![image](https://github.com/inaturalist/INaturalistIOS/assets/15896181/2998583a-3a6c-4eb7-a291-7aca93bb8ac4)

This is related an iOS update a few years ago, unfortunately. The lower buttons are also difficult to see as well, but I'd say the top ones should be given priority if there's a way to make them more visible. Are you able to add gray stable backgrounds to the top and bottom of the location editor and not have the map take up the entire page?

**Comment by alexshepard** [comment]
can we close this @tiwane ?
