### ISSUE TITLE
Allow users to select 8 photos in the photo picker

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#674]
See https://forum.inaturalist.org/t/increase-number-of-image-uploads-at-once-on-ios-app/24782/

There's a request to increase the number of photos one can choose in one go in the photo picker. For some organisms, including more than four photos is helpful for ID, and going back to the photo picker can sometimes mean scrolling to find more photos of the same organism. If possible, let's increase the total to 8.

**Comment by alexshepard** [comment]
can we close this @tiwane ?
