### ISSUE TITLE
Endless "Creating observation" spinner when importing photos sometimes

### ISSUE THREAD

**Issue by tiwane** [inaturalist/INaturalistIOS#675]
Version 3.2.15 (708)

See https://forum.inaturalist.org/t/stuck-on-creating-observation/44349/ for some examples. It's been hard to consistently replicate the issue, but it definitely seems to be related to iCloud Photos. Basically, when you import photo(s) into iNat, an endless "Creating Observation" spinner happens. 

Some situations I've seen this in

iPad/iPhone both running iOS 17. iCloud Photos is on, and "Optimize Storage" is chosen.

1. I take a photo with my iPad Mini 4, which syncs to iCloud.
2. On my iPhone 13 Pro, make sure the photo appears in Photos via iCloud.
3. Open iNat and import that photo.
4. Endless spinner.
5. On my iPhone, go to that photo, tap Edit, then tap Cancel
6. Try to import photo into iNat again. Import sucessful.

iPhone running iOS 17, while out on a walk:

1. Take a photo. 
2. Open iNat, try to import photo.
3. Endless spinner. 
4. Go to Photos, look at info for that photo. See that it's not in iCloud (icon of cloud with line through it)
5. Sync iCloud
6. Import photo into iNat again. Import works

**Comment by alexshepard** [comment]
fixed in 3.3
