### ISSUE TITLE
Observation Detail View should show how many photos are in an observation

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/INaturalistIOS#77]

**Comment by alexshepard** [comment]
is this sufficient?
![ios simulator screen shot feb 18 2015 5 49 02 pm](https://cloud.githubusercontent.com/assets/515947/6260635/bd8daa9e-b796-11e4-81a4-12725fd33fa5.png)

**Comment by kueda** [comment]
I would prefer something simpler like "1 of 2" or "1 / 2". Do you have the count info?

**Comment by alexshepard** [comment]
We do have count, so the icon isn't necessary. I'll do another treatment tomorrow.

**Comment by alexshepard** [comment]
@joellebel can you chime in here? or i can just wing something

**Comment by joellebel** [comment]
I think the number of photos would be more descriptive. It's only necessary to show when there's multiple photos. Here's a quick mock up of a temporary solution until the redesigned Ob Detail View is implemented:

![image](https://cloud.githubusercontent.com/assets/11527994/8656400/2ae8842a-294c-11e5-9f41-b19b81259209.png)


The box bg is black at 50%, 30pt x 30pt and the text is Helvetica Neue Reg. 12pts, white.

**Comment by alexshepard** [comment]
easy enough, thanks
