### ISSUE TITLE
Some Places do not show up on app search

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/INaturalistIOS#78]
When I try to search for Montpelier, Vermont it does not show up in the app even though it is a place with a defined boundary (see http://www.inaturalist.org/places/montpelier-vt-us). It also does not show up when i trigger 'search near me' when within the boundaries, and instead the entire county is searched.

**Comment by alexshepard** [comment]
I'm closing this, as it doesn't seem fix-able in the iOS app. @kueda please correct me & re-open if I'm wrong?

**Comment by kueda** [comment]
Would a `with_geom` on `/places/search.json` let you deal with this?

**Comment by alexshepard** [comment]
I think so...
