### ISSUE TITLE
Project list order strange and missing listed_taxa beyond page 1

### ISSUE THREAD

**Issue by loarie** [inaturalist/INaturalistIOS#8]
It would be nice if the project list on the iNat iPhone app for the iSeahorse project would show 47 taxa ordered by name: http://www.inaturalist.org/lists/84817.json?order_by=name&page=2

Rather, it shows 45 taxa (probably because its just fetching the first page?) by an (random?) order that is neither order_by=name or order_by=observation count

**Comment by loarie** [comment]
taxon.name fine with me

**Comment by alexshepard** [comment]
project ordering by taxon.name in 4c6c3e6579a322dcb6a55b9752de805de3b6690d, will be in 2.5.8

**Comment by alexshepard** [comment]
@loarie does this look good for you now?
